### ISSUE TITLE
Support request for DS-KB8113-IME1

### ISSUE THREAD

**Issue by dsylex** [pergolafabio/Hikvision-Addons#100]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

Hey!

Is there any chence you could add support for DS-KB8113-IME1? 

Thanks in advance!

**Comment by pergolafabio** [comment]
Hi

have tiy tried it? Try running the beta addon, it supports more, its not because its not in the compatible list, that it doesnt work
those devices are just confirmed devices :-)

If it doesnt work, past the addon log

**Comment by dsylex** [comment]
> Hi
> 
> have tiy tried it? Try running the beta addon, it supports more, its not because its not in the compatible list, that it doesnt work those devices are just confirmed devices :-)
> 
> If it doesnt work, past the addon log

Yeah, my bad, i just realised it's an addon, which I currently cannot use as I'm running HA in a docker container. For some reason I thought it was an integration. Either way, nice addon, keep up the good work :)

**Comment by pergolafabio** [comment]
Hi, its possible to run as docker container, have a  look in dev branch:

https://github.com/pergolafabio/Hikvision-Addons/blob/dev/hikvision-doorbell/docs/docker.md
