### ISSUE TITLE
Integration of DS-HD1

### ISSUE THREAD

**Issue by mrelion** [pergolafabio/Hikvision-Addons#101]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

Hello everybody.
I have the Hikvision doorbell camera DS-HD1.
Kindly ask for assistance to investigate this device to Homeassistant. 
Regards

**Comment by pergolafabio** [comment]
Hi, try the beta addon, it does everything automatically, MQTT is required tough, but once you add the doorbell config, and start the addon , sensors and switch are created... Let us know if you still need help or if you are stuck somewhere
