### ISSUE TITLE
sensor prefix and names

### ISSUE THREAD

**Issue by thiagofperes** [pergolafabio/Hikvision-Addons#102]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

Hello,

I would like to know if it is possible to make this change in the addon, as I believe it will be more flexible.

sensor_name_door = "sensor." + config["sensor_door"]

It could be:
sensor_name_door = config["sensor_door"]

So we could use whatever entity we wanted.

I, for example, prefer to use input_boolean and then create the sensors manually, so as not to lose the icons and class configs.

I made the code change for my needs, but every time I update I lose the changes.

Excellent addon, much appreciated for the effort.

**Comment by pergolafabio** [comment]
Hi, thnx for feedback,...

You are using the first addon, try using the beta, it's completely different, can do a lot more, based on MQTT devices now, and you change change names...

The one you are using will be overwritten by beta soon
