### ISSUE TITLE
Support for Hikvision DS-KH6320

### ISSUE THREAD

**Issue by prj32** [pergolafabio/Hikvision-Addons#104]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

Looking for Hikvision DS-KH6320 support with electric strike support to open gate whilst gaining access to voice and lock ideally. Looks like initial testing has started with @Torarev. I have deployed non-beta build which has lots of errors with add-on. Do you recommend beta build? Happy to assist with testing.

**Comment by pergolafabio** [comment]
yes, dont use the normal addon anymore, use the beta, we dont update the "normal" anymore, will be replaced soon by the "beta" one
