### ISSUE TITLE
Can't edit configuration

### ISSUE THREAD

**Issue by Nitinraigugliani** [pergolafabio/Hikvision-Addons#105]
### What happened?

After installing Hikvision doorbell beta, when I try to edit configuration, it doesn't take any input. If I try to start it without inputing any configuration, it obviously shows error "Missing required option 'name' in Hikvision Doorbell (Beta) (aff2db71_hikvision_doorbell_beta)." Is there something wrong I am doing? I am running home assistant on raspberry pi.

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

3.0.0 beta 19

### Installation type

Home Assistant add-on

### Relevant log output

```Text
No log output
```

**Comment by Nitinraigugliani** [comment]
If I use YAML to add configuration, following screenshot shows, its not editable.
<img width="1131" alt="Screenshot 2023-04-17 at 20 45 12" src="https://user-images.githubusercontent.com/87187370/232531704-3d164b1f-6955-4071-bf2b-d2482cf35b8a.png">

**Comment by pergolafabio** [comment]
Hmm, should look like below:

![image](https://user-images.githubusercontent.com/43251136/232535456-e5d1730a-7b3b-4b19-96d4-80cff3cd31b1.png)


or in yaml : 

![image](https://user-images.githubusercontent.com/43251136/232535656-ecfa3424-3e5f-400a-aab8-a126034dd560.png)

**Comment by Nitinraigugliani** [comment]
Hi.. Can you pls suggest any solution..

**Comment by pergolafabio** [comment]
I have no idea? The addon should work, is also working for lots of other users?
Maybe you have somekind of frontend issue? Have you tried another browser? Is everything uptodate?

**Comment by Nitinraigugliani** [comment]
Hi

I tried it twice but there was no change. Can you pls share a version prior to current one.. I wish to see if this problem occurs there or not.

Regards

**Comment by pergolafabio** [comment]
Hi , I can't do that , will have impact on all users...

What you can do, just fork my GitHub repository, and then change the beta version in this file...

Then load your custom repository into HA...

https://github.com/pergolafabio/Hikvision-Addons/blob/main/doorbell_beta/config.yaml

**Comment by Nitinraigugliani** [comment]
I am newbie to this so pls help me. I have forked it. How do select other beta version? It is showing main version only.

**Comment by pergolafabio** [comment]
In HA you need to remove first this repository... And also uninstall the beta first...

Then edit that file on GitHub, change it to beta 18 or earlier
Then add again your forked repository into HA

**Comment by Nitinraigugliani** [comment]
I shall be grateful if you can specify some steps to edit file to change beta version. I tried doing that by going to Go to file -> selecting config.yaml ->selecting editor -> edit link is non-clickable.

**Comment by pergolafabio** [comment]
? Can you show me a screenshots? You are editing it on your GitHub page, right?

**Comment by pergolafabio** [comment]
I can do this:


![Screenshot_20230426-071235](https://user-images.githubusercontent.com/43251136/234475718-fb107450-63e1-45b2-b60e-45fc59ec66ff.jpg)

**Comment by Nitinraigugliani** [comment]
Yes. I had sent the screenshot in last mail. Sending again.

￼

**Comment by pergolafabio** [comment]
Hmm, I don't see it

**Comment by Nitinraigugliani** [comment]
Looks like some firewall is deleting it. Here is the link to screenshot

https://ibb.co/105trBr

**Comment by pergolafabio** [comment]
Seems you are in 04e... branche, it needs master and dev...can you fork them both?
But this is not the issue , it won't solve anything, there is no issue with the beta release, and notching changed in past versions...

Have you tried another browser/pc ?

**Comment by Nitinraigugliani** [comment]
Ok. Will create new HA instance in spare raspberry pi and will confirm. Thanks.

**Comment by pergolafabio** [comment]
Ok, gonna close for now
