### ISSUE TITLE
Status not changed when the 'Exit' button is used

### ISSUE THREAD

**Issue by igor-epam** [pergolafabio/Hikvision-Addons#107]
### What happened?

Thank you for the great work! I am using a Docker image and it is working well. I can confirm that the Home Assistant app is able to display the status of a call and the lock state. Whenever I open the door using a Mifare or the app, the status gets updated accordingly. However, if I open the door using an external ‘Exit’ button located within the perimeter, the doorbell indicates that ‘The door is opened’, but the status in Home Assistant does not change. Is there a bug that needs to be fixed?

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

 image: ghcr.io/pergolafabio/hikvision-doorbell:3.0.0-beta.16

### Installation type

Docker container (standalone)

### Relevant log output

```Text
No status changes when the 'Exit' button is used.
```

### Relevant configuration

```YAML
KV6113 + external 'Exit' button.
docker HA, MQTT moquitto
```

**Comment by pergolafabio** [comment]
that possibly another type of event , do you see something in the log when you open the door with the exit button? It’s probably classified as an alarm I/O event… You can also build automations based on this type of event

**Comment by pergolafabio** [comment]
The exit button is new to me, can you tell me more about it? Is it hooked up on the alarm input or output? Is it connected to indoor or outdoor?

**Comment by igor-epam** [comment]
I hope/think this event should help:
EVENT_ACS_DOOR_BUTTON_PRESS https://tpp.hikvision.com/Wiki/ISAPI/Access%20Control%20on%20Person/GUID-3DA08C41-78D4-41C4-A22C-5B0B57D23C15.html

**Comment by pergolafabio** [comment]
Yeah but I think those events are for ACS controllers, not door intercoms

**Comment by igor-epam** [comment]
Is there any way to query for all event types supported by device via ISAPI?

**Comment by pergolafabio** [comment]
Hmm,  not sure, I stepped away from Isapi for event stream, since it was not compatible for all devices and a real struggle...

But I have another look next week with the ACS

**Comment by igor-epam** [comment]
Ok. Let me know if I can assist somehow. It will be really cool to make this fully functioning and get notifications about door opening via an exit button.

**Comment by pergolafabio** [comment]
Perfect, thnx in advance

**Comment by pergolafabio** [comment]
had a look, but i dont think its possible

this addon listens for these events:

https://open.hikvision.com/hardware/definitions/NET_DVR_StartListen_V30.html

When there is somekind of event, we trigger this, for example:

COMM_UPLOAD_VIDEO_INTERCOM_EVENT
or
COMM_ALARM_VIDEO_INTERCOM
 ...

we are also listening for : 

COMM_ALARM_ACS  : https://open.hikvision.com/hardware/structures/NET_DVR_ACS_ALARM_INFO.html

those are the events you want, like exit button ... but its not triggered by the device
My guess this only works with an Hikvision ACS controller , dont think a standalone Intercom can create those events
Or 
Maybe these events need to be enabled somehow on the intercom itself with ivms, like with motion detection, if not enabled, we dont see it as an event

**Comment by pergolafabio** [comment]
gonna close for now, since i dont think we can grab this event

**Comment by igor-epam** [comment]
Hi, FYI
I just got a reply from a support team. They confirmed, that KV6113 doesn't support eventing on exit button press.

Dear Client  I did the test, I got the same results as yours, and I checked with the R&D team, the device does not upload door open/lock events when you use the exit button. If you think it is necessary, please check with our local pre-sale team, and discuass abount the customization request,

**Comment by pergolafabio** [comment]
That's too bad indeed :-(
