### ISSUE TITLE
Running on Home Assistant Container

### ISSUE THREAD

**Issue by wiuwiu** [pergolafabio/Hikvision-Addons#11]
Hi @pergolafabio .

Thank your fot his awesome work.
I have a question about MariaDB. As I want to run your integration on Home Assistant Container I need to known where you put database config because I have a MariaDB on seperate container.

**Comment by pergolafabio** [comment]
Hey , I use it in the Sql.sh file, where I populate it... And a few times in the opensips.cfg file
