### ISSUE TITLE
MQTT devices are unavailable

### ISSUE THREAD

**Issue by niraviry** [pergolafabio/Hikvision-Addons#112]
### What happened?

After moving from the latest beta version which was OK, I have removed the beta, rebooted, and installed the release version.
All MQTT sensors under the front door and in-door unit are there but unavailable. 
I use on the latest version of HA and all add-ons. I and using HASS on RPi.
I suspect the MQTT topic was not created or so although it was supposed to be created.

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

2.1

### Installation type

Home Assistant add-on

### Relevant log output

```Text
Nothing that shows any error or info.
```

### Relevant configuration

```YAML
I use a different name for my sensors template configuration (not hikvision_door etc.)
```

### Anything else?

All was OK in the beta version.

**Comment by pergolafabio** [comment]
Hi, use the beta, don't use the general addon anymore, only the beta is using mqtt... It will replace the main release soon

**Comment by niraviry** [comment]
OK. I noticed the general one has no documentation on MQTT. Could not figure out why.

**Comment by pergolafabio** [comment]
Yeah, that's the reason :-)

It was the first project, but it's old, beta is better and more events and more functions, we are still working on it

**Comment by lobmarib** [comment]
I'm currently using 3.0.12 and I'm experiencing the same problem. All MQTT entities are unavailable. Any hint?

**Comment by pergolafabio** [comment]
Maybe the addon is not running, then they become unavailable

**Comment by lobmarib** [comment]
It's running. I even set the log level to debug and I can't see nothing suspicious

**Comment by lobmarib** [comment]
Done it and now the mqtt device wasn't re added

**Comment by lobmarib** [comment]
I've managed to kind of get it to work.
Now I'm receiving all the time fake events (door realy 1 on/off, ringing/dismissed)

**Comment by pergolafabio** [comment]
yes, give it a while :-)
once backlog is finished, the device is cleared
