### ISSUE TITLE
Clarification in asterisk.as.indoor.md for rookies

### ISSUE THREAD

**Issue by CV8R** [pergolafabio/Hikvision-Addons#113]
### What happened?

I am very greatful to report that I have this working!  Thank you!!!

I did have a few issues following the setup guide in asterisk.as.indoor.md that I thought I should feedback for clarification in case it catches out others. Apologies if this is the wrong place for that.

1. ```#### Setup this in confbrifge.conf``` should be ```#### Setup this in confbridge.conf```
2. Example 2 requires the outgoing section from Example 1 inserted.
3. Mac address in regXML - what MAC address is this?

Item 1. is a basic typo - f instead of d which caught me out because I cut n pasted it.
item 2. maybe implied but it wasn't clear.  Perhaps repeat the requirement for pjsip_custom.conf in Example 2.
Item 3. The indoor panel registered with with the script regardless but I am not sure if this is the panel or a doorbell device?

Thanks again, this is awesome to have working!

Cheers,
CV8R

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

2.1

### Installation type

Home Assistant add-on

### Relevant log output

```Text
N/A
```

### Relevant configuration

```YAML
N/A
```

### Anything else?

`https://github.com/pergolafabio/Hikvision-Addons/blob/dev/asterisk/asterisk.as.indoor.md`

**Comment by pergolafabio** [comment]
Hi, thnx for feedback, will change typos soon :-)


The Mac address, you can just a random one, doesn't matter, as long its there :-)

**Comment by pergolafabio** [comment]
typos corrected :-)
