### ISSUE TITLE
Asterisk support calling two (or more) extensions with early media

### ISSUE THREAD

**Issue by CV8R** [pergolafabio/Hikvision-Addons#114]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

None

### Your feature request

An Asterisk configuration to support dialing 2 (or more) SIP numbers, with early media, and whomever answers first wins the call. For example, when someone presses the call button on one of the doorbells a call is initiated to indoor station the indoor station rings and so does my wife and my phone showing early media.

**Comment by pergolafabio** [comment]
If you are using sip.linphone.org, you can register both on the same account, both accounts ring, their flexisip server support it...
If you are using local accounts, just do a second orginate and copy paste the local channels, should work

**Comment by CV8R** [comment]
Hi @pergolafabio, i am new to Asterisk so forgive me.  I have duplicated api.php with api2.php and changed to Local/9002@default. I then duplicated the code blocks in extensions.conf, I also duplicated 9000 with 9002 and 9001 to 9003. I also added hangup requests for each in the last finish call block.

Both phones ring now and I early media works to both devices.  However, when I answer on one phone the other continues to ring (it can also join the conference).   Any tips on hanging up the line that did not answer?

**Comment by pergolafabio** [comment]
I think you are are managing asterisk fine if you already accomplished this :-)

You see in my example code I have a finishcall macro , to cancel all calls ( all local channels)

You can create 2 more like 

finishcall-9001
finishcall-9003

Add that new hangup handler to both local extensions, so So if 9001 answer, you kill 9003 and visa versa...

Let me know if it's unclear, then I write it down in code...

**Comment by CV8R** [comment]
I had added the lines to the finish call macro, what I am not sure about is how to add the hangup handler to 9002 and 9003 if one sip phone answers. If one sip phone answers the other sip phone continues to ring. The indoor panel does stop ringing as expected.  If the ringing sip phone that has not answered hangs up all calls are disconnected.

Below is my extensions.conf

```
;Hikvision setup
exten => 10000000005,1,NoOp()
 same => n,Progress()
 same => n,Set(CHANNEL(hangup_handler_push)=default,finishcall,1(args)) 
 same => n,Set(GLOBAL(CHANNEL-IN)=${CHANNEL})
 same => n,System(/usr/bin/php "/config/asterisk/agi.php")
 same => n,System(/usr/bin/php "/config/asterisk/agi2.php")
 same => n,Set(i=1)
 same => n,While($[${i} < 60])
 same => n,NoOp(Confbridge number of participants : ${CONFBRIDGE_INFO(parties,1)})
 same => n,GotoIf($["${CONFBRIDGE_INFO(parties,1)}" >= "1"]?startconf) 
 same => n,Wait(1) 
 same => n,Set(i=$[${i} + 1]
 same => n,EndWhile()
 same => n(startconf),ConfBridge(1,myconferenceroom,default_user) 
 same => n,Hangup()


exten = rtsp,1,Answer()
 same => n,RTSP-SIP(rtsp://auser:apass@10.0.6.21:554/Streaming/Channels/102,0,asterisk,5060)
 same => n,Hangup() 
 
exten => 9000,1,NoOp()
 same => n,Progress()
 same => n,Set(CHANNEL(hangup_handler_push)=default,finishcall,1(args))  
 same => n,Set(GLOBAL(CHANNEL-9000)=${CHANNEL}) 
 same => n,Dial(Local/9001@default,,G(join_caller))
 same => n(join_caller),ConfBridge(1,myconferenceroom,marked_user) 
 same => n,ConfBridge(1,myconferenceroom,admin_user)
 same => n,Hangup()

 exten => 9002,1,NoOp()
 same => n,Progress()
 same => n,Set(CHANNEL(hangup_handler_push)=default,finishcall,1(args))  
 same => n,Set(GLOBAL(CHANNEL-9002)=${CHANNEL}) 
 same => n,Dial(Local/9003@default,,G(join_caller))
 same => n(join_caller),ConfBridge(1,myconferenceroom,marked_user) 
 same => n,ConfBridge(1,myconferenceroom,admin_user)
 same => n,Hangup()
 
exten => 9001,1,NoOp() 
 same => n,Progress()
 same => n,Set(CHANNEL(hangup_handler_push)=default,finishcall,1(args))  
 same => n,Set(GLOBAL(CHANNEL-9001)=${CHANNEL})
 same => n,Set(__DYNAMIC_FEATURES=door)
 same => n,Set(CALLERID(num)=Doorbell)
 same => n,Set(CALLERID(name)=Doorbell)
 same => n,Set(COUNT=1)
 same => n,While($[ ${COUNT} < 60 ]) 
 same => n,Dial(PJSIP/outgoing/sip:sipuser1@sip.provider.net)
 same => n,Set(HANGUPCAUSEKEYS=${HANGUPCAUSE_KEYS()})
 same => n,Set(HANGUP_CAUSE=${HANGUPCAUSE})
 same => n,Verbose(2, HANGUP_CAUSE=${HANGUPCAUSE})
 same => n,GotoIf($["${HANGUP_CAUSE}" == "21"]?exitdialplan)
 same => n,Wait(3) 
 same => n,SET(COUNT=$[${COUNT} + 1])
 same => n,EndWhile()
 same => n(exitdialplan),NoOp(Exiting dialplan: HANGUP_CAUSE=${HANGUPCAUSE}) 
 same => n,Hangup()

exten => 9003,1,NoOp() 
 same => n,Progress()
 same => n,Set(CHANNEL(hangup_handler_push)=default,finishcall,1(args))
 same => n,Set(GLOBAL(CHANNEL-9003)=${CHANNEL})
 same => n,Set(__DYNAMIC_FEATURES=door)
 same => n,Set(CALLERID(num)=Doorbell)
 same => n,Set(CALLERID(name)=Doorbell)
 same => n,Set(COUNT=1)
 same => n,While($[ ${COUNT} < 60 ]) 
 same => n,Dial(PJSIP/outgoing/sip:sipuser2@sip.provider.net)
 same => n,Set(HANGUPCAUSEKEYS=${HANGUPCAUSE_KEYS()})
 same => n,Set(HANGUP_CAUSE=${HANGUPCAUSE})
 same => n,Verbose(2, HANGUP_CAUSE=${HANGUPCAUSE})
 same => n,GotoIf($["${HANGUP_CAUSE}" == "21"]?exitdialplan)
 same => n,Wait(3) 
 same => n,SET(COUNT=$[${COUNT} + 1])
 same => n,EndWhile()
 same => n(exitdialplan),NoOp(Exiting dialplan: HANGUP_CAUSE=${HANGUPCAUSE}) 
 same => n,Hangup()

exten => finishcall,1,NoOp() 
 same => n,System(/usr/sbin/asterisk -rx "confbridge kick 1 all")
 same => n,System(/usr/sbin/asterisk -rx "hangup request ${CHANNEL-IN}")
 same => n,System(/usr/sbin/asterisk -rx "hangup request ${CHANNEL-9000}")
 same => n,System(/usr/sbin/asterisk -rx "hangup request ${CHANNEL-9001}")
 same => n,System(/usr/sbin/asterisk -rx "hangup request ${CHANNEL-9002}")
 same => n,System(/usr/sbin/asterisk -rx "hangup request ${CHANNEL-9003}")
 same => n,Return()

[parkedcallstimeout]
exten => s,1,Hangup()
```

**Comment by pergolafabio** [comment]
try it like below, so when 9001 answers, the macro finish-call 9003 runs , so 9003 channel should quit... and visa versa ...
```

exten => 9001,1,NoOp() 
 same => n,Progress()
 same => n,Set(CHANNEL(hangup_handler_push)=default,finishcall-9001,1(args))  
 same => n,Set(GLOBAL(CHANNEL-9001)=${CHANNEL})
 same => n,Set(__DYNAMIC_FEATURES=door)
 same => n,Set(CALLERID(num)=Doorbell)
 same => n,Set(CALLERID(name)=Doorbell)
 same => n,Set(COUNT=1)
 same => n,While($[ ${COUNT} < 60 ]) 
 same => n,Dial(PJSIP/outgoing/sip:sipuser1@sip.provider.net)
 same => n,Set(HANGUPCAUSEKEYS=${HANGUPCAUSE_KEYS()})
 same => n,Set(HANGUP_CAUSE=${HANGUPCAUSE})
 same => n,Verbose(2, HANGUP_CAUSE=${HANGUPCAUSE})
 same => n,GotoIf($["${HANGUP_CAUSE}" == "21"]?exitdialplan)
 same => n,Wait(3) 
 same => n,SET(COUNT=$[${COUNT} + 1])
 same => n,EndWhile()
 same => n(exitdialplan),NoOp(Exiting dialplan: HANGUP_CAUSE=${HANGUPCAUSE}) 
 same => n,Hangup()

exten => 9003,1,NoOp() 
 same => n,Progress()
 same => n,Set(CHANNEL(hangup_handler_push)=default,finishcall-9002,1(args))
 same => n,Set(GLOBAL(CHANNEL-9003)=${CHANNEL})
 same => n,Set(__DYNAMIC_FEATURES=door)
 same => n,Set(CALLERID(num)=Doorbell)
 same => n,Set(CALLERID(name)=Doorbell)
 same => n,Set(COUNT=1)
 same => n,While($[ ${COUNT} < 60 ]) 
 same => n,Dial(PJSIP/outgoing/sip:sipuser2@sip.provider.net)
 same => n,Set(HANGUPCAUSEKEYS=${HANGUPCAUSE_KEYS()})
 same => n,Set(HANGUP_CAUSE=${HANGUPCAUSE})
 same => n,Verbose(2, HANGUP_CAUSE=${HANGUPCAUSE})
 same => n,GotoIf($["${HANGUP_CAUSE}" == "21"]?exitdialplan)
 same => n,Wait(3) 
 same => n,SET(COUNT=$[${COUNT} + 1])
 same => n,EndWhile()
 same => n(exitdialplan),NoOp(Exiting dialplan: HANGUP_CAUSE=${HANGUPCAUSE}) 
 same => n,Hangup()

exten => finishcall,1,NoOp() 
 same => n,System(/usr/sbin/asterisk -rx "confbridge kick 1 all")
 same => n,System(/usr/sbin/asterisk -rx "hangup request ${CHANNEL-IN}")
 same => n,System(/usr/sbin/asterisk -rx "hangup request ${CHANNEL-9000}")
 same => n,System(/usr/sbin/asterisk -rx "hangup request ${CHANNEL-9001}")
 same => n,Return()

exten => finishcall-9001,1,NoOp() 
 same => n,System(/usr/sbin/asterisk -rx "hangup request ${CHANNEL-9001}")
 same => n,Return()

exten => finishcall-9003,1,NoOp() 
 same => n,System(/usr/sbin/asterisk -rx "hangup request ${CHANNEL-9003}")
 same => n,Return()
```

**Comment by CV8R** [comment]
Hi, doesn't appear to work. The following line doesn't appear to trigger when a call is answered on that line. As a test I put hangup requests in the finishcall macro for each 9000, 9001, 9002 and 9003 and no calls are terminated.

`same => n,Set(CHANNEL(hangup_handler_push)=default,finishcall-9001,1(args))`

**Comment by pergolafabio** [comment]
ok, another way, you see i added an hangup cause key:

```
 same => n,Set(HANGUPCAUSEKEYS=${HANGUPCAUSE_KEYS()})
 same => n,Set(HANGUP_CAUSE=${HANGUPCAUSE})
 same => n,Verbose(2, HANGUP_CAUSE=${HANGUPCAUSE})
```

If you answer with 9003 , what KEY number do you see in the log? 

You can make an extra IF construction , right after the dial command
```

 same => n,Dial(PJSIP/outgoing/sip:sipuser2@sip.provider.net)
  if construction here ...   
```

https://www.voip-info.org/asterisk-func-if/

if key = XX then => System(/usr/sbin/asterisk -rx "hangup request ${CHANNEL-9003}")

something like that maybe?

**Comment by pergolafabio** [comment]
then run a maco that will send the hangup :-)

**Comment by CV8R** [comment]
Ok, that was a steep learning curve but i believe I have nailed it.

1. M flag calls a macro which is now deprecated needed to use U.
2. Needed to pop the hangup_handler when hanging up the other sip line so that the door stations and conf would hang up.  Otherwise, they would not hangup until the next call request. Meaning, that you needed to press the door station call button once, then again to make the call.
3.  Added a GoSub routine after hangup cause 21 that detected if only 1 party left in the conference remaining (the input) otherwise the confbridge and IN call would stay up if both sip lines happened to reject the call.

Onto the next challenge - 2 door stations have the rtsp extension for early media follow the originating door station ( I have two).  Not sure how to pass args to and from the PHP.

```
;Hikvision setup
exten => 10000000005,1,NoOp()
 same => n,Progress()
 same => n,Set(CHANNEL(hangup_handler_push)=default,finishcall,1(args)) 
 same => n,Set(GLOBAL(CHANNEL-IN)=${CHANNEL})
 same => n,System(/usr/bin/php "/config/asterisk/agi.php")
 same => n,System(/usr/bin/php "/config/asterisk/agi2.php")
 same => n,Set(i=1)
 same => n,While($[${i} < 60])
 same => n,NoOp(Confbridge number of participants : ${CONFBRIDGE_INFO(parties,1)})
 same => n,GotoIf($["${CONFBRIDGE_INFO(parties,1)}" >= "1"]?startconf)
 same => n,Wait(1) 
 same => n,Set(i=$[${i} + 1]
 same => n,EndWhile()
 same => n(startconf),ConfBridge(1,myconferenceroom,default_user) 
 same => n,Hangup()


exten = rtsp,1,Answer()
 same => n,RTSP-SIP(rtsp://auser:apass@10.0.6.21:554/Streaming/Channels/102,0,asterisk,5060)
 same => n,Hangup() 
 
exten => 9000,1,NoOp()
 same => n,Progress()
 same => n,Set(CHANNEL(hangup_handler_push)=default,finishcall,1(args))  
 same => n,Set(GLOBAL(CHANNEL-9000)=${CHANNEL}) 
 same => n,Dial(Local/9001@default,,G(join_caller))
 same => n(join_caller),ConfBridge(1,myconferenceroom,marked_user) 
 same => n,ConfBridge(1,myconferenceroom,admin_user)
 same => n,Hangup()

 exten => 9002,1,NoOp()
 same => n,Progress()
 same => n,Set(CHANNEL(hangup_handler_push)=default,finishcall,1(args))  
 same => n,Set(GLOBAL(CHANNEL-9002)=${CHANNEL}) 
 same => n,Dial(Local/9003@default,,G(join_caller))
 same => n(join_caller),ConfBridge(1,myconferenceroom,marked_user) 
 same => n,ConfBridge(1,myconferenceroom,admin_user)
 same => n,Hangup()
 
exten => 9001,1,NoOp()
 same => n,Progress()
 same => n,Set(CHANNEL(hangup_handler_push)=default,finishcall-9001,1(args))
 same => n,Set(GLOBAL(CHANNEL-9001)=${CHANNEL})
 same => n,Set(__DYNAMIC_FEATURES=door)
 same => n,Set(CALLERID(num)=Doorbell)
 same => n,Set(CALLERID(name)=Doorbell)
 same => n,Set(COUNT=1)
 same => n,While($[ ${COUNT} < 60 ]) 
 same => n,Dial(PJSIP/outgoing/sip:sipuser1@sip.provider.net,30,U(subHangup-9001))
 same => n,Set(HANGUPCAUSEKEYS=${HANGUPCAUSE_KEYS()})
 same => n,Set(HANGUP_CAUSE=${HANGUPCAUSE})
 same => n,Verbose(2, HANGUP_CAUSE=${HANGUPCAUSE})
 same => n,GotoIf($["${HANGUP_CAUSE}" == "21"]?exitdialplan)
 same => n,Wait(3) 
 same => n,SET(COUNT=$[${COUNT} + 1])
 same => n,EndWhile()
 same => n(exitdialplan),NoOp(Exiting dialplan: HANGUP_CAUSE=${HANGUPCAUSE})
 same => n,GoSub(subTerminateConf,s,1)
 same => n,Hangup()

exten => 9003,1,NoOp() 
 same => n,Progress()
 same => n,Set(CHANNEL(hangup_handler_push)=default,finishcall-9003,1(args))
 same => n,Set(GLOBAL(CHANNEL-9003)=${CHANNEL})
 same => n,Set(__DYNAMIC_FEATURES=door)
 same => n,Set(CALLERID(num)=Doorbell)
 same => n,Set(CALLERID(name)=Doorbell)
 same => n,Set(COUNT=1)
 same => n,While($[ ${COUNT} < 60 ]) 
 same => n,Dial(PJSIP/outgoing/sip:sipuser2@sip.provider.net,30,U(subHangup-9003))
 same => n,Set(HANGUPCAUSEKEYS=${HANGUPCAUSE_KEYS()})
 same => n,Set(HANGUP_CAUSE=${HANGUPCAUSE})
 same => n,Verbose(2, HANGUP_CAUSE=${HANGUPCAUSE})
 same => n,GotoIf($["${HANGUP_CAUSE}" == "21"]?exitdialplan)
 same => n,Wait(3) 
 same => n,SET(COUNT=$[${COUNT} + 1])
 same => n,EndWhile()
 same => n(exitdialplan),NoOp(Exiting dialplan: HANGUP_CAUSE=${HANGUPCAUSE})
 same => n,GoSub(subTerminateConf,s,1)
 same => n,Hangup()

exten => finishcall,1,NoOp() 
 same => n,System(/usr/sbin/asterisk -rx "confbridge kick 1 all")
 same => n,System(/usr/sbin/asterisk -rx "hangup request ${CHANNEL-IN}")
 same => n,System(/usr/sbin/asterisk -rx "hangup request ${CHANNEL-9000}")
 same => n,System(/usr/sbin/asterisk -rx "hangup request ${CHANNEL-9002}")
 same => n,Return()


exten => finishcall-9001,1,NoOp()
 same => n,System(/usr/sbin/asterisk -rx "hangup request ${CHANNEL-9001}")
 same => n,Return()

exten => finishcall-9003,1,NoOp()
 same => n,System(/usr/sbin/asterisk -rx "hangup request ${CHANNEL-9003}")
 same => n,Return()

[subHangup-9001]
exten => s,1,System(/usr/sbin/asterisk -rx "hangup request ${CHANNEL-9003}")
 same => n,Set(CHANNEL(hangup_handler_pop)=default,finishcall,1(args))
 same => n,Return()

[subHangup-9003]
exten => s,1,System(/usr/sbin/asterisk -rx "hangup request ${CHANNEL-9001}")
 same => n,Set(CHANNEL(hangup_handler_pop)=default,finishcall,1(args))
 same => n,Return()

[subTerminateConf]
exten => s,1,Gotoif($["${CONFBRIDGE_INFO(parties,1)}" = "1"]?kick)
 same => s,n,Return()
 same => s,n(kick),Noop(Kicking all participants from conference)
 same => n,Verbose(2, Kick all participants)
 same => s,n,System(/usr/sbin/asterisk -rx "hangup request ${CHANNEL-IN}")
 same => n,System(/usr/sbin/asterisk -rx "confbridge kick 1 all")
 same => n,Return()
```

**Comment by pergolafabio** [comment]
Nice, it provably can be simplified a lot, with less code lness using arguments, :-) it's all repeating code, something for later....

Maybe this is useful for your second doorbell?

https://stackoverflow.com/questions/11448366/asterisk-server-pass-variable-from-dialplan-to-agi-script

**Comment by CV8R** [comment]
Passing the args works - simple. Hit a snag - I am unable to identify which of the door stations is calling. Any clues on how to identify the caller?

**Comment by pergolafabio** [comment]
you are probably using this config without user/pass auth and have the script running twice?

```
[hikvision]
type=aor
contact=sip:10000000004@192.168.0.71:5060

[hikvision]
type=endpoint
....
```

WHy not register the second script as user 10000000004 instead?

so you have a call coming in for 10000000005 and 10000000004 , so you can see the difference

Then just copy/paste part below and change the number

```
exten => 10000000005,1,NoOp()
 same => n,Progress()
...
```

**Comment by CV8R** [comment]
My initial thought was to run the script twice to do exactly as you suggest.  I chose 10000000004  but the script wont connect complaining about the same IP address and Port.

**Comment by pergolafabio** [comment]
ahh , yeah, thats possible, the script uses an port too ... 
if you want to register twice, you need to run it also twice, just copy/paste the script, search for the line with port 5061
just changed it in your second script to port 5062 , and it should run ..

**Comment by CV8R** [comment]
Will only register if being run from a different IP address - Replicated it.  If trying to run two scripts from the same IP it registers the most recent connection from that IP.  If I run from another IP it registers twice successfully.  Confirmed changing port to 5063 (5062 doesn't work) and changed the S/N, Name and MAC in regXML.

**Comment by pergolafabio** [comment]
hmm, thats a diffucult one , script is indeed verry basic

maybe an approach is to create a virtual NIC on your system, so you can use a second IP ?

**Comment by pergolafabio** [comment]
if you are running HassOS on proxmox or esxi, maybe an idea to add a second NIC adapter ?

**Comment by CV8R** [comment]
Ha ha, we are on the same page.  I just tested it on my macbook and using an alias it works.  I had to modify the bind address in each script.  HA is running on Proxmox so about to throw in another NIC. I'll report back.

**Comment by pergolafabio** [comment]
ok , i hope it works :-)

**Comment by pergolafabio** [comment]
in future, pyVoip will be integrated native in HA itself, we should be able to use HA to make register, or just use pyVoip

i already requested to have regXML support in pyVoip, and it was approved, so no fancy script needed anymore

as you can see in the project  : https://github.com/users/tayler6000/projects/2

but still in backlog state , so unclear when it will be available ...

**Comment by CV8R** [comment]
I have given up on the approach of 10000000004 and 10000000005. I was able to add a second IP and have HA register twice but the issue is I do not see a way to have the door stations call only one or the other.  Both door stations calls get routed to the two registered stations. I haven't got the HA integration working as yet (external MQTT) but there maybe an option (kludge) there to have HA detect the calling door station and change the rtsp address.

**Comment by pergolafabio** [comment]
Ahhh , yeah you only have one indoor station? ok, that makes sense indeed, i thought you had  2

so 10000000004 for first one and 10000000005 for second one


Hmm, it should be possible with even 1  x registered 10000000005 

did you play with sngrep tool? Can you make a capture of an incoming call from doorstation 1 and 2 ? i think the contact header or sip number should be different, maybe in asterisk we can check this header and based on that header you have the argument ... for the correct rtsp stream

**Comment by pergolafabio** [comment]
see here : 

https://community.asterisk.org/t/get-contact-data-for-current-user/91424

**Comment by CV8R** [comment]
Works! Video now follows the calling station!

Put a descriptive name in the door stations which make their way into the header.

added the following to the 10000000005 exten

`same => n,Set(SIP_CALLER=${CUT(CUT(PJSIP_HEADER(read,From),<,1), ,-2)})`

The cuts are to work around the fact that I like spaces instead of underscores in the names on the devices. I called them "Front Gate" and "Front Door".  I then add an underscore back in to the agi.php script so that it passes on "Front_Gate" and "Front_Door" to allow the exten dial plan to work.

FYI and unrelated.  I added the following line to the dialplan for the sip exten so that it doesn't continually try to ring the phone if the phone is not reachable. I am sure there is a downside to this...

` same => n,GotoIf($["${HANGUP_CAUSE}" == "1"]?exitdialplan)`

 That was fun and thank you for all the work and support! I learnt a lot over the last few days.

**Comment by pergolafabio** [comment]
anyway, i'm still investigating why the video is not in the call, ity should be there by default
i have a second indoor station, did some wireshark;, and the video is sended also in the sip message
so for me still unclear why its missing in asterisk ... otherwise all this fancy dialplan and that agi originate script was not needed at all ....

**Comment by pergolafabio** [comment]
thnx for sharing

**Comment by Boxieeee** [comment]
> thnx for sharing

how do i add local extension like 8003 and 8002 to it?

**Comment by pergolafabio** [comment]
if you dont care about video, then dont use the dialplan or conference, just use groups or follow me system
this difficult dialplan is for video

**Comment by Boxieeee** [comment]
just use groups or follow me system  , this rings everyone  and if i reject from one then others keep ringing

**Comment by pergolafabio** [comment]
thats probably a setting you can define in asteriks, lots of possibilities there
i dont use it anymore, so cant help :-(

**Comment by Boxieeee** [comment]
ah okay  .. it world be a great help  in current config  (i mean the video script)  same => n,Dial(PJSIP/outgoing/sip:USER1@sip.linphone.org)  i can use 8003 and 8002 local extension . i can  ring through normal groups works but here i   have no clue how they will enter  conf , new to this using freepbx 17 but good with cli :)
