### ISSUE TITLE
Intercom door relay state does not update

### ISSUE THREAD

**Issue by kanemari** [pergolafabio/Hikvision-Addons#119]
### What happened?

I have a DS-KV8102 intercom. It seems to auto-discover most of its functions and work normally at face value. However, I noticed that when triggering the door to open via the relay switch generated by the integration, the state topic does not update. It gets set to 'ÓFF' upon startup, then doesnt change after that.

I have tried listening to the command and state topics. The command topic shows the payload 'ON' and the door relay does trigger, but the state topic stays the same. The log files show a warning when this happens.

[2023-06-18 22:46:12.884][DBG] Remote control dwCommToDVR[0x126009] dwDVRReturn[0]  dwoutBufSize[172]
2023-06-18 22:46:12.918 | INFO     | doorbell:unlock_door:116 -  Door 1 unlocked by SDK
2023-06-18 22:46:15.340 | INFO     | event:video_intercom_event:98 - Video intercom event from Front Gate
2023-06-18 22:46:15.340 | WARNING  | mqtt:video_intercom_event:196 - Received unknown lockID: 39687

Also noticed there is no state topic change nor any event or log data when the relay is activated directly from the door or the hikvision app. Those actions are completely invisible to this integration. I had hoped to be able to detect any opening of the door within HA through this integration but at the moment I cant detect anything.

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

3.0.0-beta.20

### Installation type

Home Assistant add-on

### Relevant log output

```Text
2023-06-18 22:46:12.884][DBG] Remote control dwCommToDVR[0x126009] dwDVRReturn[0]  dwoutBufSize[172]
2023-06-18 22:46:12.918 | INFO     | doorbell:unlock_door:116 -  Door 1 unlocked by SDK
2023-06-18 22:46:15.340 | INFO     | event:video_intercom_event:98 - Video intercom event from Front Gate
2023-06-18 22:46:15.340 | WARNING  | mqtt:video_intercom_event:196 - Received unknown lockID: 39687
```

**Comment by pergolafabio** [comment]
Hi, the 8102 is indeed a problematic device , its a quite old one... Is latest firmware active on it?

If I remember correct, the call sensor doesn't work either...

About 39687, is that lock id always the same in the log?

**Comment by pergolafabio** [comment]
If there is nothing to see in the log, whenopening door from hikvision/door, there is nothing i can do about it, that device doesnt support all functions

about the state not going to off again, seems the lockid is somekind of weird number, what we can do in below code, is just setting the state to off again, for lock 1 & 2 

```
            entity_id = f'door_{door_id}'
            # Extract the entity from the dict and cast to know type
            door_sensor = cast(Switch, self._sensors[doorbell].get(entity_id))
            # If the SDK returns a lock ID that is not starting from 0, 
            # we don't know what switch to update in HA, so do nothing
            if not door_sensor:
                logger.warning("Received unknown lockID: {}", door_id)
                return
   
            logger.info("Door {} unlocked by {}, updating sensor {}",
                        door_id+1,
                        control_source,
                        door_sensor._entity.name)
            attributes = {
                'control source': control_source,
            }
            door_sensor.on()
            door_sensor.set_attributes(attributes)
            # Wait some seconds, then turn off the switch entity (since the relay is momentary)
            await asyncio.sleep(2)
            door_sensor.off()
```

**Comment by kanemari** [comment]
> Hi, the 8102 is indeed a problematic device , its a quite old one... Is latest firmware active on it?
> 
> If I remember correct, the call sensor doesn't work either...
> 
> About 39687, is that lock id always the same in the log?

yeah it looks like the call sensor doesnt pick up any incoming calls either. The lockID seems to change every time the warning is generated.

**Comment by kanemari** [comment]
> If there is nothing to see in the log, whenopening door from hikvision/door, there is nothing i can do about it, that device doesnt support all functions
> 
> about the state not going to off again, seems the lockid is somekind of weird number, what we can do in below code, is just setting the state to off again, for lock 1 & 2
> 
> ```
>             entity_id = f'door_{door_id}'
>             # Extract the entity from the dict and cast to know type
>             door_sensor = cast(Switch, self._sensors[doorbell].get(entity_id))
>             # If the SDK returns a lock ID that is not starting from 0, 
>             # we don't know what switch to update in HA, so do nothing
>             if not door_sensor:
>                 logger.warning("Received unknown lockID: {}", door_id)
>                 return
>    
>             logger.info("Door {} unlocked by {}, updating sensor {}",
>                         door_id+1,
>                         control_source,
>                         door_sensor._entity.name)
>             attributes = {
>                 'control source': control_source,
>             }
>             door_sensor.on()
>             door_sensor.set_attributes(attributes)
>             # Wait some seconds, then turn off the switch entity (since the relay is momentary)
>             await asyncio.sleep(2)
>             door_sensor.off()
> ```

I would be ok with the state changing back to "off" after 30 seconds or to something I could change to align with the timeout on the door relay set through iVMS, but the problem with he state is that it never changes to 'ON' in the first place. the command topic shows the 'ON' command being sent through, but the state never changes from 'OFF' even though the relay triggers on the door.

**Comment by pergolafabio** [comment]
Ok, so just changing the switch to "off" is ok for you?

**Comment by kanemari** [comment]
> Ok, so just changing the switch to "off" is ok for you?

I guess I just want the MQTT state topic to update properly. so when the button gets pressed it indicates that its on, and after a period of time it indicates its off again. This one:-

hmd/switch/Front-Gate/Door-1-relay/state

The switch would automatically correct its behaviour if the state topic was accurate I think?

**Comment by kanemari** [comment]
yes thanks, that would work given the circumstances

**Comment by pergolafabio** [comment]
how many relays does your doorstation have?

**Comment by pergolafabio** [comment]
can you do a test for me? 

Uninstall the current beta
Download the "dev" branch of this doorbell https://github.com/pergolafabio/Hikvision-Addons/tree/dev
Then copy/paste   the "hikvision-doorbell"  folder inside your /addons share
Then edit this if function around  line 194 , make it like :  (file src/mqtt.py)

```
            if not door_sensor:
                logger.warning("Received unknown lockID: {}", door_id)
                logger.debug("Changing switches back to OFF position")
                num_doors = doorbell.get_num_outputs()
                await asyncio.sleep(2)
                for entity_id in range(num_doors):
                    door_sensor = cast(Switch, self._sensors[doorbell].get(entity_id))
                    door_sensor.off()
                return
```
Then install the local addon, it should be listed at the top of your addon store if you do a check for updates

**Comment by kanemari** [comment]
> how many relays does your doorstation have?

I only have 1 relay

**Comment by kanemari** [comment]
> can you do a test for me?
> 
> Uninstall the current beta, delete the mqtt devices Download the "dev" branch of this doorbell https://github.com/pergolafabio/Hikvision-Addons/tree/dev Then copy/paste the "hikvision-doorbell" folder inside your /addons share Then edit this if function around line 194 , make it like below : (file src/mqtt.py)
> 
> ```
>             if not door_sensor:
>                 logger.warning("Received unknown lockID: {}", door_id)
>                 logger.debug("Changing switches back to OFF position")
>                 num_doors = doorbell.get_num_outputs()
>                 await asyncio.sleep(2)
>                 for entity_id in range(num_doors):
>                     door_sensor = cast(Switch, self._sensors[doorbell].get(entity_id))
>                     door_sensor.off()
>                 return
> ```
> 
> Then install the local addon, it should be listed at the top of your addon store if you do a check for updates

ok will have a go, thanks!

**Comment by pergolafabio** [comment]
make sure to enable debug in the config, to see if you see this message , then you know you are using the modified code

`logger.debug("Changing switches back to OFF position")`

**Comment by kanemari** [comment]
> if not door_sensor:
>                 logger.warning("Received unknown lockID: {}", door_id)
>                 logger.debug("Changing switches back to OFF position")
>                 num_doors = doorbell.get_num_outputs()
>                 await asyncio.sleep(2)
>                 for entity_id in range(num_doors):
>                     door_sensor = cast(Switch, self._sensors[doorbell].get(entity_id))
>                     door_sensor.off()
>                 return

got some unexpected errors:-

2023-06-19 22:05:47.213 | DEBUG    | mqtt:door_switch_callback:149 - Received command: ON, door_id: 0, doorbell: 15 Intercom
[2023-06-19 22:05:47.213][DBG] Remote control dwCommToDVR[0x126009] dwDVRReturn[0]  dwoutBufSize[172]
[2023-06-19 22:05:47.215][INF] Private connect 192.168.1.200:8000 sock=157 this=0x423f8938 cmd=0x126009 port=53114
2023-06-19 22:05:47.250 | INFO     | doorbell:unlock_door:116 -  Door 1 unlocked by SDK
2023-06-19 22:05:49.705 | DEBUG    | event:_handle_callback:192 - Callback invoked from SDK
2023-06-19 22:05:49.707 | DEBUG    | event:_invoke_handlers:166 - Invoking 2 handlers
2023-06-19 22:05:49.708 | WARNING  | mqtt:video_intercom_event:196 - Received unknown lockID: 41223
2023-06-19 22:05:49.708 | DEBUG    | mqtt:video_intercom_event:197 - Changing switches back to OFF position
[2023-06-19 22:05:49.704][INF] Alarm[0] IP[192.168.1.200] data_len[159384] alarm_len[159384] status[431]
[2023-06-19 22:05:49.708][INF] [0][COM_CoreDevCfg_GetDeviceAbility] AbilityType 0x14, InbufLen=[0], OutbufLen[4096]
[2023-06-19 22:05:49.710][INF] Private connect 192.168.1.200:8000 sock=157 this=0x423f8938 cmd=0x11000 port=53118
2023-06-19 22:05:49.775 | INFO     | event:video_intercom_event:98 - Video intercom event from 15 Intercom
Task exception was never retrieved
future: <Task finished name='MQTT' coro=<MQTTHandler.video_intercom_event() done, defined at /app/mqtt.py:177> exception=AttributeError("'NoneType' object has no attribute 'off'")>
Traceback (most recent call last):
  File "/app/mqtt.py", line 202, in video_intercom_event
    door_sensor.off()
AttributeError: 'NoneType' object has no attribute 'off'

I wasnt outside to check if the door actually unlocked, but the MQTT state topic didnt change from 'off' same as before. The code change you have made looks like it will turn the MQTT state back to 'off' once it turns on and doesnt receive the correct lockID, but the problem is the MQTT state topic never updates to 'on' in the first place even though the relay gets triggered correctly.

**Comment by pergolafabio** [comment]
Yeah, I don't send the on command now, only the off...


Can you add door_sensor.on() line , right before the off command?

When changing code, afterwards, also change the version in the config yaml file, the addon needs an update  when code is changed

**Comment by kanemari** [comment]
I think I fixed it - reviewed how the entity_id was derived in the code and made some changes:-

                num_doors = doorbell.get_num_outputs()
                await asyncio.sleep(2)
                for door_id in range(num_doors):
                    entity_id = f'door_{door_id}'
                    door_sensor = cast(Switch, self._sensors[doorbell].get(entity_id))

this appears to work - the state seems to update now.

**Comment by pergolafabio** [comment]
Yeah, not home, otherwise I was able to upfate, I will make this change in next beta, thnx for testing!!

**Comment by pergolafabio** [comment]
ok, back home , your code indeed works, but if a user has 2 outputs, only 1 has will receive the payload on/off :-)

Thats why i have the for loop, can you try this?


```
            # If the SDK returns a lock ID that is not starting from 0, 
            # we don't know what switch to update in HA, so do nothing
            # Make sure the switch is back in "OFF" position in case it was trigger by the switch
            if not door_sensor:
                logger.warning("Received unknown lockID: {}", door_id)
                logger.debug("Changing switches back to OFF position")
                num_doors = doorbell.get_num_outputs()
                await asyncio.sleep(2)
                for door_id in range(num_doors):
                    entity_id = f'door_{door_id}'
                    door_sensor = cast(Switch, self._sensors[doorbell].get(entity_id))
                    door_sensor.on()
                    door_sensor.set_attributes(attributes)
                    # Wait some seconds, then turn off the switch entity (since the relay is momentary)
                    await asyncio.sleep(2)
                    door_sensor.off()
                return
   
            logger.info("Door {} unlocked by {}, updating sensor {}",
                        door_id+1,
                        control_source,
                        door_sensor._entity.name)
            attributes = {
                'control source': control_source,
            }
            door_sensor.on()
            door_sensor.set_attributes(attributes)
            # Wait some seconds, then turn off the switch entity (since the relay is momentary)
            await asyncio.sleep(2)
            door_sensor.off()
        else:
            logger.warning("Unhandled eventType: {}", alarm_info.byEventType)
```

**Comment by kanemari** [comment]
thanks for this - yes this works as well.

I guess its a choice as to whether you want every door sensor to change state, or only one door sensor to change state - in the event that the lockID is incorrect / unknown.

since the door wont change state to begin with if the lockID is unknown - this appears to only be useful in the case that you have a single doorbell with a single relay. Otherwise it may just become confusing.

But anyway, it works for what I wanted it to - so thanks again. I actually have another doorbell of the same model which I am not using with this integration. I might try adding it and see if there are any ways to potentially differentiate the garbage data they pump out! :)

**Comment by pergolafabio** [comment]
indeed :-)

yeah , there are maybe some 8102 owners that are using both relays, best to set them both to off anyway , not sure if your hardware supports it, otherwise i can drop the loop and use indeed your code change

**Comment by pergolafabio** [comment]
fixed in beta 21
