### ISSUE TITLE
Ghost call on KD8003

### ISSUE THREAD

**Issue by MaoZ1993** [pergolafabio/Hikvision-Addons#12]
Hi there, My intercom is Hik kd8003, I installed the add on today and instantly it start "receiving call", the call status change to "on" every 10-15 seconds, but no one has pressed the call button on KD8003. 

Logs attached

Hikvision SDK Add-on started! Listening for events...
loop[2] find 10 mac and 16 ip
Doorbell ringing, trying to update: sensor.hikvision_callstatus
Call dismissed
Doorbell ringing, trying to update: sensor.hikvision_callstatus
Call dismissed
Doorbell ringing, trying to update: sensor.hikvision_callstatus
Call dismissed
Doorbell ringing, trying to update: sensor.hikvision_callstatus
Call dismissed
Doorbell ringing, trying to update: sensor.hikvision_callstatus
Call dismissed
Doorbell ringing, trying to update: sensor.hikvision_callstatus
Call dismissed
Doorbell ringing, trying to update: sensor.hikvision_callstatus
Call dismissed
Doorbell ringing, trying to update: sensor.hikvision_callstatus
Call dismissed
Doorbell ringing, trying to update: sensor.hikvision_callstatus
Call dismissed
Doorbell ringing, trying to update: sensor.hikvision_callstatus
Call dismissed
Doorbell ringing, trying to update: sensor.hikvision_callstatus
Call dismissed
Doorbell ringing, trying to update: sensor.hikvision_callstatus
Call dismissed

**Comment by pergolafabio** [comment]
Strange, I have the same 8003 device... Maybe you need to reboot it?

**Comment by pergolafabio** [comment]
ok , i think i know whats going on, seems first time you launch the script, its downloading also the history... once its downloaded, it should be fine :-)

**Comment by MaoZ1993** [comment]
> ok , i think i know whats going on, seems first time you launch the script, its downloading also the history... once its downloaded, it should be fine :-)

You are correct, an hour later the ghost call stopped. Works great! Thanks for you amazing work
