### ISSUE TITLE
Modify device trigger `door_open` 

### ISSUE THREAD

**Issue by mion00** [pergolafabio/Hikvision-Addons#121]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

- Add `control_source` as part of the payload for the device trigger `door_open`.
- Check the use of `type` and `subtype` (should we use subtype=`<doorid>`?)

The data could be sent as a JSON map, so that we could send additional structured data in the future that can be parsed by the template filters of HA.

See comment in forum: https://community.home-assistant.io/t/hikvision-doorbell-videointercom-integration/532796/550?u=mion00

**Comment by pergolafabio** [comment]
gonna test the  change in setting attributes first before turning on switch

**Comment by pergolafabio** [comment]
seems setting attributes first does the trick:

me-assistant.io/t/hikvision-doorbell-videointercom-integration/532796/574?u=pergola.fabio


gonna close for now?

**Comment by mion00** [comment]
Given that state and attributes are sent in different moments in two separate topics, I think that there may be some corner cases where this trick of inverting the order might not work.

**Comment by pergolafabio** [comment]
added in dev
