### ISSUE TITLE
How to remove / reinstall this addon? I have duplicated entities and none of them work

### ISSUE THREAD

**Issue by uros76** [pergolafabio/Hikvision-Addons#133]
### What happened?

I entered the name on the configuration wrong, restarted the HA and began to use the addon. 
Then I renamed it in the configuration, restarted HA and now have duplicated entities (old ones remain unavailable) and the new ones don't work at all.  See below screenshot

Is there a way to remove them all and start from scratch? 

![image](https://github.com/pergolafabio/Hikvision-Addons/assets/25409772/39598ade-f337-407e-8507-88ce07af8c11)

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

3.0.0

### Installation type

Home Assistant add-on

### Relevant log output

```Text
2023-08-24 10:35:37.885 | DEBUG    | config:load_mqtt_config:130 - Loading MQTT configuration from supervisor
2023-08-24 10:35:37.886 | DEBUG    | config:mqtt_config_from_supervisor:36 - Requesting MQTT service configuration to supervisor
2023-08-24 10:35:37.908 | INFO     | sdk.utils:loadSDK:44 - Using OS: Linux with architecture: x86_64
loop[2] find 2 mac and 0 ip
2023-08-24 10:35:38.308 | INFO     | doorbell:authenticate:70 - Connected to doorbell: hikvision_doorbell
2023-08-24 10:35:38.309 | INFO     | event:__init__:76 - Setting up event handler: Console stdout
2023-08-24 10:35:38.309 | INFO     | mqtt:__init__:96 - Setting up event handler: MQTT
```

### Relevant configuration

```YAML
- name: hikvision_doorbell
  ip: 192.168.1.249
  username: admin
  password: xxx
```

**Comment by pergolafabio** [comment]
Yeah , sure, just stop the addon
Then in HA, goto the MQTT integrtation, select the device(s) and remove them... then start addon again

**Comment by uros76** [comment]
Ah man, so simple :D I actually had to remove the device under MQTT integration. I could not remove the entities itself, they were deeply attached to the device. 

Now the ring status and relay works. 
However, the hangup / reject call commands don't work. Anything else I should setup? Or is there a shell command I could try if it works? 
I would love to get the reject working for automation purpose if I manually open the door. Yes, I have door sensor installed :)

**Comment by pergolafabio** [comment]
the reject command works, but it only works, if the indoor station is actually ringing :-)
As for hangup, it also works, but you need to first answer the call on your indoor :-)


If you send it without a ringing status, you see indeed an error in the log ...

**Comment by uros76** [comment]
Yes yes, the indoor is ringing and the reject doesn't work for me. Also if I pick up ring with indoor, the hangup doesn't work. Dont know why. Maybe something with the latest firmware on outdoor/indoor units blocking it? 

I used this command now to reject a ring: 
`curl -i --digest -u admin:xxx -d '{"CallSignal":{"cmdType":"reject"}}' -H "Content-Type: application/json" -X PUT http://192.168.1.249/ISAPI/VideoIntercom/callSignal?format=json`
It did nothing, ring kept going.

**Comment by uros76** [comment]
More info from log. I established a ringing call, tried to hangup with this addon and it doesn't work. 
This is from addon log:
`2023-08-24 11:15:00.464 | INFO     | mqtt_input:_hangup_call_callback:288 - Received hangup command for doorbell: hikvision_doorbell
2023-08-24 11:15:00.479 | ERROR    | mqtt_input:_hangup_call_callback:300 - Error while hanging up call: ('Error while calling ISAPI /ISAPI/VideoIntercom/callSignal?format=json', 23, 'Device does not support this function.')`

**Comment by pergolafabio** [comment]
Noo, curl commands do not work, port 80 is closed on indoor stations
I have buttosn created on the addon/mqtt integration, you need to use those ...


![image](https://github.com/pergolafabio/Hikvision-Addons/assets/43251136/a415d283-0e66-4c85-a145-afc922d1f8e3)

**Comment by pergolafabio** [comment]
ahh; wait , i now see, you used indeed the addon , sorry

**Comment by pergolafabio** [comment]
have you tried reject  too, do you also see error 23 then ?

**Comment by uros76** [comment]
I also tried the shell command and get this output. Nothing happens while trying to reject a ringing call
`~$ curl -i --digest -u admin:xxx -d '{"CallSignal":{"cmdType":"reject"}}' -H "Content-Type: application/json" -X PUT http://192.168.1.249/ISAPI/VideoIntercom/callSignal?format=json
HTTP/1.1 401 Unauthorized
Date: Thu, 24 Aug 2023 10:10:05 GMT
Server: webs
Content-Length: 0
Connection: close
X-Frame-Options: SAMEORIGIN
Cache-Control: no-store
Pragma: no-cache
WWW-Authenticate: Digest qop="auth", realm="DS-5375596A", nonce="NjcwZWVmMmE4NGRiYjM0YjgyODU1ODY5ZjAwY2M3MmY=", stale="false", opaque="", domain="::"
Content-Type: application/json

HTTP/1.1 200 OK
Date: Thu, 24 Aug 2023 10:10:05 GMT
Server: webs
Content-Length: 67
Connection: close
X-Frame-Options: SAMEORIGIN
Cache-Control: no-store
Pragma: no-cache
Content-Type: application/json

{
        "statusCode":   1,
        "statusString": "OK",
        "subStatusCode":        "ok"`

**Comment by pergolafabio** [comment]
hmm, maybe you need to send the reject to outdoor station for you ?

**Comment by uros76** [comment]
I tried the reject button and it didnt work. This is from addon log while trying the reject: 

`2023-08-24 11:18:55.400 | INFO     | event:video_intercom_alarm:109 - Video intercom alarm from hikvision_doorbell
2023-08-24 11:19:05.420 | INFO     | mqtt_input:_reject_call_callback:273 - Received reject command for doorbell: hikvision_doorbell`

**Comment by pergolafabio** [comment]
no error?

For me , i need to send to indoor, when i send reject when no ringing, then i have error 29
But it works if its ringing

**Comment by uros76** [comment]
No error visible with reject press in the log no. 
Not sure why these reject or hangum are not working. Strange isn't it

**Comment by uros76** [comment]
Let me reboot my both outdoor / indoor units and try if that helps

**Comment by uros76** [comment]
Nope, same. I restarted both hik units and also restarted HA. 
Addon cannot reject a ring call for me. 
`2023-08-24 11:26:46.490 | INFO     | event:video_intercom_alarm:109 - Video intercom alarm from hikvision_doorbell
2023-08-24 11:26:49.996 | INFO     | mqtt_input:_reject_call_callback:273 - Received reject command for doorbell: hikvision_doorbell`

**Comment by uros76** [comment]
Is there a deeper logging available? Maybe we can get more info in the log if that helps to track down a problem

**Comment by pergolafabio** [comment]
yeah, set both to DEBUG:: in the addon config


```
log_level: INFO
sdk_log_level: NONE
```

Then try to send reject to both indoor and outdoor ?

**Comment by uros76** [comment]
Ok trying now... 

Hmmm, how to send reject command to Indoor unit with addon? In the addon configuration, there is only an IP specified for the outdoor unit. Or the addon knows how to connect to indoor unit over outdoor somehow?

**Comment by pergolafabio** [comment]
ahhhh, are you using the normal addon? You need to use the beta addon
it creates buttons for both indoor and outdoor

**Comment by pergolafabio** [comment]
this is my outdoor:

![image](https://github.com/pergolafabio/Hikvision-Addons/assets/43251136/21019ca5-3b25-4c37-9600-2b75aa780c19)

**Comment by uros76** [comment]
Wait no. I am using beta version, see screenshot. Maybe I should uninstall and reinstall completely the addon? 
![image](https://github.com/pergolafabio/Hikvision-Addons/assets/25409772/8213b78c-5375-46da-b0ac-63c340746d7f)

This is with DEBUG log. After I reject it got same output as I got with shell command.  

`[2023-08-24 11:33:18.015][INF] The COM:HCAlarm ver is 6.1.6.45, 2021_03_02.
[2023-08-24 11:33:18.019][INF] Private connect 192.168.1.249:8000 sock=135 this=0xa2bf1504 cmd=0x117000 port=57396
2023-08-24 11:33:18.048 | DEBUG    | sdk.utils:call_ISAPI:165 - Response output: <DeviceInfo version="2.0" xmlns="http://www.isapi.org/ver20/XMLSchema">
<deviceName>Outdoor</deviceName>
<deviceID>7d49925b-4fc7-406b-a0ec-e0ca3ce7a69a</deviceID>
<deviceDescription>	Vis</deviceDescription>
<deviceLocation>STD-CGI</deviceLocation>
<systemContact>STD-CGI</systemContact>
<model>DS-KV8113-WME1(C)</model>
<serialNumber>DS-KV8113-WME1(C)xxx</serialNumber>
<macAddress>xxx</macAddress>
<firmwareVersion>V2.2.65</firmwareVersion>
<firmwareReleasedDate>build 230703</firmwareReleasedDate>
<bootVersion>33685569</bootVersion>
<bootReleasedDate>1509123</bootReleasedDate>
<hardwareVersion>0x0</hardwareVersion>
<encoderVersion>V2.7</encoderVersion>
<encoderReleasedDate>build 230606</encoderReleasedDate>
<deviceType>	Vis</deviceType>
<telecontrolID>88</telecontrolID>
<supportBeep>true</supportBeep>
<supportVideoLoss>true</supportVideoLoss>
<alarmOutNum>2</alarmOutNum>
<alarmInNum>4</alarmInNum>
<RS485Num>1</RS485Num>
<customizedInfo></customizedInfo>
</DeviceInfo>

[2023-08-24 11:33:18.048][DBG] SimpleSTDCommandToDvr with out cmd[GET /ISAPI/System/deviceInfo], input size[0], max segment length[262144]
[2023-08-24 11:33:18.099][INF] [0][COM_CoreDevCfg_GetDeviceAbility] AbilityType 0x14, InbufLen=[0], OutbufLen[4096]
[2023-08-24 11:33:18.101][INF] Private connect 192.168.1.249:8000 sock=136 this=0xa2bf1504 cmd=0x11000 port=57398
2023-08-24 11:33:18.111 | DEBUG    | mqtt:__init__:139 - Configuring 2 door switches
2023-08-24 11:33:18.120 | DEBUG    | event:register_handler:206 - Adding event handler MQTT
2023-08-24 11:33:18.121 | DEBUG    | mqtt_input:__init__:21 - Setting up MQTTInput
2023-08-24 11:33:18.122 | DEBUG    | sdk.utils:call_ISAPI:125 - Request body: 
[2023-08-24 11:33:18.136][INF] Private connect 192.168.1.249:8000 sock=142 this=0xa2bf1504 cmd=0x117000 port=57408
2023-08-24 11:33:18.142 | DEBUG    | sdk.utils:call_ISAPI:165 - Response output: <DeviceInfo version="2.0" xmlns="http://www.isapi.org/ver20/XMLSchema">
<deviceName>Outdoor</deviceName>
<deviceID>7d49925b-4fc7-406b-a0ec-e0ca3ce7a69a</deviceID>
<deviceDescription>	Vis</deviceDescription>
<deviceLocation>STD-CGI</deviceLocation>
<systemContact>STD-CGI</systemContact>
<model>DS-KV8113-WME1(C)</model>
<serialNumber>DS-KV8113-WME1(C)xxx</serialNumber>
<macAddress>xxx</macAddress>
<firmwareVersion>V2.2.65</firmwareVersion>
<firmwareReleasedDate>build 230703</firmwareReleasedDate>
<bootVersion>33685569</bootVersion>
<bootReleasedDate>1509123</bootReleasedDate>
<hardwareVersion>0x0</hardwareVersion>
<encoderVersion>V2.7</encoderVersion>
<encoderReleasedDate>build 230606</encoderReleasedDate>
<deviceType>	Vis</deviceType>
<telecontrolID>88</telecontrolID>
<supportBeep>true</supportBeep>
<supportVideoLoss>true</supportVideoLoss>
<alarmOutNum>2</alarmOutNum>
<alarmInNum>4</alarmInNum>
<RS485Num>1</RS485Num>
<customizedInfo></customizedInfo>
</DeviceInfo>

[2023-08-24 11:33:18.142][DBG] SimpleSTDCommandToDvr with out cmd[GET /ISAPI/System/deviceInfo], input size[0], max segment length[262144]
2023-08-24 11:33:18.183 | DEBUG    | event:start:227 - Registering callback function using SDK
2023-08-24 11:33:18.185 | DEBUG    | doorbell:setup_alarm:81 - Arming the device via SDK
[2023-08-24 11:33:18.190][INF] Private connect 192.168.1.249:8000 sock=157 this=0xa2bf1504 cmd=0x111020 port=57420
2023-08-24 11:33:18.196 | DEBUG    | input:loop_forever:29 - Waiting for input command
2023-08-24 11:33:50.813 | DEBUG    | event:_handle_callback:192 - Callback invoked from SDK
2023-08-24 11:33:50.816 | DEBUG    | event:_invoke_handlers:166 - Invoking 2 handlers
2023-08-24 11:33:50.816 | INFO     | event:video_intercom_alarm:109 - Video intercom alarm from hikvision_doorbell
[2023-08-24 11:33:50.813][INF] Alarm[0] IP[192.168.1.249] data_len[568] alarm_len[568] status[430]
2023-08-24 11:33:50.817 | INFO     | mqtt:video_intercom_alarm:259 - Doorbell ringing, updating sensor 
settings: mqtt=MQTT(host='core-mosquitto', username='addons', password='jeeNg4Mee9Doh0aiw3ouyuc3fie9zeeF6Liexoh6YooM4pae5ceilu4lahth4OhK', client_name=None, tls_key=None, tls_certfile=None, tls_ca_cert=None, discovery_prefix='homeassistant', state_prefix='hmd') entity=SensorInfo(component='sensor', device=DeviceInfo(name='hikvision_doorbell', model='DS-KV8113-WME1(C)', manufacturer='Hikvision', sw_version='V2.2.65', hw_version='0x0', identifiers='6883457586564949514587776949406741484950485051485449538282656754525353574954', connections=None, configuration_url=None), device_class=None, enabled_by_default=None, entity_category=None, expire_after=None, force_update=None, icon='mdi:bell', name='Call state', object_id='hikvision_doorbell_call_state', qos=None, unique_id='6883457586564949514587776949406741484950485051485449538282656754525353574954-call_state', unit_of_measurement=None) debug=False manual_availability=True
topic_prefix: sensor/hikvision_doorbell/Call-state
config_topic: homeassistant/sensor/hikvision_doorbell/Call-state/config
state_topic: hmd/sensor/hikvision_doorbell/Call-state/state
wrote_configuration: True
        
2023-08-24 11:33:58.978 | INFO     | mqtt_input:_reject_call_callback:273 - Received reject command for doorbell: hikvision_doorbell
2023-08-24 11:33:58.979 | DEBUG    | sdk.utils:call_ISAPI:125 - Request body: {"CallSignal": {"cmdType": "reject"}}
[2023-08-24 11:33:58.986][INF] Private connect 192.168.1.249:8000 sock=160 this=0xa2bf1ae8 cmd=0x117001 port=58170
2023-08-24 11:33:58.994 | DEBUG    | sdk.utils:call_ISAPI:165 - Response output: {
	"requestURL":	"/ISAPI/VideoIntercom/callSignal",
	"statusCode":	1,
	"statusString":	"OK",
	"subStatusCode":	"ok"
}
[2023-08-24 11:33:58.994][DBG] SimpleSTDCommandToDvr with out cmd[PUT /ISAPI/VideoIntercom/callSignal?format=json], input size[37], max segment length[262144]
2023-08-24 11:34:06.618 | DEBUG    | event:_handle_callback:192 - Callback invoked from SDK
2023-08-24 11:34:06.621 | DEBUG    | event:_invoke_handlers:166 - Invoking 2 handlers
2023-08-24 11:34:06.622 | INFO     | event:video_intercom_alarm:109 - Video intercom alarm from hikvision_doorbell
2023-08-24 11:34:06.623 | INFO     | mqtt:video_intercom_alarm:262 - Call dismissed, updating sensor 
settings: mqtt=MQTT(host='core-mosquitto', username='addons', password='jeeNg4Mee9Doh0aiw3ouyuc3fie9zeeF6Liexoh6YooM4pae5ceilu4lahth4OhK', client_name=None, tls_key=None, tls_certfile=None, tls_ca_cert=None, discovery_prefix='homeassistant', state_prefix='hmd') entity=SensorInfo(component='sensor', device=DeviceInfo(name='hikvision_doorbell', model='DS-KV8113-WME1(C)', manufacturer='Hikvision', sw_version='V2.2.65', hw_version='0x0', identifiers='6883457586564949514587776949406741484950485051485449538282656754525353574954', connections=None, configuration_url=None), device_class=None, enabled_by_default=None, entity_category=None, expire_after=None, force_update=None, icon='mdi:bell', name='Call state', object_id='hikvision_doorbell_call_state', qos=None, unique_id='6883457586564949514587776949406741484950485051485449538282656754525353574954-call_state', unit_of_measurement=None) debug=False manual_availability=True
topic_prefix: sensor/hikvision_doorbell/Call-state
config_topic: homeassistant/sensor/hikvision_doorbell/Call-state/config
state_topic: hmd/sensor/hikvision_doorbell/Call-state/state
wrote_configuration: True
        
[2023-08-24 11:34:06.617][INF] Alarm[0] IP[192.168.1.249] data_len[568] alarm_len[568] status[430]
[2023-08-24 11:34:23.291][DBG] Alarm chan [0] recv timeout[2]!
`

**Comment by uros76** [comment]
Allright, let me uninstall completely and reinstall. Will report back what happens.

**Comment by pergolafabio** [comment]
ah, i see, it was ringing
indeed some outdoors dont react to it, when there is an indoor attached, (same for me)

can you show same log, withting and sending it to indoor?

**Comment by uros76** [comment]
Yes of course. I sent the reject command when there was a ringing call. I have an DS-KV8113-WME1(C) outdoor unit

**Comment by uros76** [comment]
After reinstalling of addon, the reject button still doesn't work. This is how it's set up under mqtt now:
![image](https://github.com/pergolafabio/Hikvision-Addons/assets/25409772/2b5cfdfa-af38-4877-bdd9-9828cae39dab)


I tried the reject command on indoor unit IP and it doesn't work. Ok port 80 we know it's closed, but I even tried on port 8000 and it doesn't work:
`~$ curl -i --digest -u admin:xxx -d '{"CallSignal":{"cmdType":"reject"}}' -H "Content-Type: application/json" -X PUT http://192.168.1.187/ISAPI/VideoIntercom/callSignal?format=json
curl: (7) Failed to connect to 192.168.1.187 port 80 after 7 ms: Connection refused`

`~$ curl -i --digest -u admin:xxx -d '{"CallSignal":{"cmdType":"reject"}}' -H "Content-Type: application/json" -X PUT http://192.168.1.187:8000/ISAPI/VideoIntercom/callSignal?format=json
curl: (1) Received HTTP/0.9 when not allowed`

**Comment by pergolafabio** [comment]
Curl commands to port 8000 dont work, that port 8000 is specific for the SDK
The only way sending the reject is with the addon

You still see then error 23 ? device not supported? when sending to indoor?

**Comment by uros76** [comment]
Ok, didn't know about 8000 port being demanding. 

With addon sending reject I see just this, not even an error. THe reject button command gives no additional info on the log. After failed reject I then manually rejected the ring call on the indoor unit screen. This is full log: 

`2023-08-24 11:48:23.514 | INFO     | event:video_intercom_alarm:109 - Video intercom alarm from hikvision_doorbell
2023-08-24 11:48:27.276 | INFO     | mqtt_input:_reject_call_callback:273 - Received reject command for doorbell: hikvision_doorbell
2023-08-24 11:48:32.445 | INFO     | mqtt:video_intercom_alarm:262 - Call dismissed, updating sensor 
settings: mqtt=MQTT(host='core-mosquitto', username='addons', password='jeeNg4Mee9Doh0aiw3ouyuc3fie9zeeF6Liexoh6YooM4pae5ceilu4lahth4OhK', client_name=None, tls_key=None, tls_certfile=None, tls_ca_cert=None, discovery_prefix='homeassistant', state_prefix='hmd') entity=SensorInfo(component='sensor', device=DeviceInfo(name='hikvision_doorbell', model='DS-KV8113-WME1(C)', manufacturer='Hikvision', sw_version='V2.2.65', hw_version='0x0', identifiers='6883457586564949514587776949406741484950485051485449538282656754525353574954', connections=None, configuration_url=None), device_class=None, enabled_by_default=None, entity_category=None, expire_after=None, force_update=None, icon='mdi:bell', name='Call state', object_id='hikvision_doorbell_call_state', qos=None, unique_id='6883457586564949514587776949406741484950485051485449538282656754525353574954-call_state', unit_of_measurement=None) debug=False manual_availability=True
topic_prefix: sensor/hikvision_doorbell/Call-state
config_topic: homeassistant/sensor/hikvision_doorbell/Call-state/config
state_topic: hmd/sensor/hikvision_doorbell/Call-state/state
wrote_configuration: True`

**Comment by uros76** [comment]
Honestly, I am still happy to see call status and lock commands work locally. This way I can stop using the cloud hik doorbell addon. 

But of course, it would be great to get the other button commands working at some point 😊

**Comment by pergolafabio** [comment]
But have you added also your indoor station to your config too?
can you show me your config?

**Comment by uros76** [comment]
Ah no I did not. How do I do that? 
Here is my current config file:
`- name: hikvision_doorbell
  ip: 192.168.1.249
  username: admin
  password: xxx
`

**Comment by pergolafabio** [comment]
ahh, thats why!! you need to also add yur indoor device too :-)

like:

```
- name: DS-KD8003
  ip: 192.168.0.70
  username: admin
  password: xxx
  output_relays: 1
- name: DS-KH9510
  ip: 192.168.0.71
  username: admin
  password: xxx
```

that will create a second MQTT devicen use those reject button then :-)

**Comment by uros76** [comment]
Ahhhhh it works now 😂. This should be explained more on the main github page LOL
Thanks for the patience and help provided. Virtual beer donation on the way to your paypal 👍

**Comment by pergolafabio** [comment]
hehe, thnx!!

well, its explained, but still all in beta, alltough it should be released as final soon
Just hoping to get the com ports to work, but it will take some time, maybe i can debug later the hikconnect app, to see how commands are being sended

in docs there are examples :-)
https://github.com/pergolafabio/Hikvision-Addons/blob/main/doorbell_beta/DOCS.md

**Comment by uros76** [comment]
> hehe, thnx!!
> 
> well, its explained, but still all in beta, alltough it should be released as final soon Just hoping to get the com ports to work, but it will take some time, maybe i can debug later the hikconnect app, to see how commands are being sended
> 
> in docs there are examples :-) https://github.com/pergolafabio/Hikvision-Addons/blob/main/doorbell_beta/DOCS.md

He he yes I noticed later there are config examples in the doc. Silly me I looked just at the basic githib landing page.

Keeping fingers crossed if you manage to get the indoor unit COM relays to work 👌
