### ISSUE TITLE
Door not closed binary sensor

### ISSUE THREAD

**Issue by madspeed** [pergolafabio/Hikvision-Addons#137]
### What happened?

Cant find binary sensor for "door not closed"

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

3.0.0

### Installation type

Home Assistant add-on

### Anything else?

How to find "door not closed" binary sensor?
I want to make automation - door not closed for XX minutes - send notification.

**Comment by pergolafabio** [comment]
Hi, all events like motion, zone, door open are now device triggers, you can build automations on those triggers
We decided to NOT create a binary sensor for eacht type of event, cause it will be to much then

Alltoough, the "door open open" event is triggered by the device/SDK, you should see it in the log. but seems the "door not closed" dosnt get triggered by the device itself, it doesnt work for anyone

Someoone created a workaround for this:, look here:

https://community.home-assistant.io/t/hikvision-doorbell-videointercom-integration/532796/537

**Comment by madspeed** [comment]
I have added the following, but status is UNKNOWN, what I did wrong?
template:
  - trigger:
    - platform: mqtt
      topic: hmd/device_automation/Doorbell/door_not_closed_0/state        
    binary_sensor:
    - name: 'kalitka_status'
      unique_id: kalitka_status
      icon: mdi:door
      device_class: door      
      state: >
        true
      attributes:
        last_event: "{{ now().isoformat()}}"

**Comment by pergolafabio** [comment]
i dont think there is a "door not closed" event , its not supported
Can you check with MQTT explorer to see what event is created? i think you will only see "door not open"

**Comment by madspeed** [comment]
![image](https://github.com/pergolafabio/Hikvision-Addons/assets/61581394/dc2a73dc-4c71-4605-813e-625f8be68faf)

**Comment by pergolafabio** [comment]
hmm, not sure why its unknown, i dont use those triggers... maybe you can ask the guy on the forum? reply to that message?
