### ISSUE TITLE
hikvision sensors won't work. 

### ISSUE THREAD

**Issue by fabianbonte** [pergolafabio/Hikvision-Addons#14]
Hi, i've installed the plugin as told, added the sensors in conf; 
Logbook from Hikvision-SDK says:

"Hikvision SDK Add-on started! Listening for events...
loop[2] find 8 mac and 16 ip"

but i cannot see any change to the sensors when calling doorphone. 

Running hass on vm on vm-ware macmini

**Comment by pergolafabio** [comment]
Do you see anything in the log of th addon when you open door / call ? it should be there too

**Comment by fabianbonte** [comment]
192.168.0.21 = touchscreen

192.168.0.20 = outdoor unit

 

 

 

mvg,

 

Fabian Bonte

 

 <http://trifase.be/> trifase.be ////

------------------------------

TriFase BVBA

 <x-apple-data-detectors://7/1> Rumbeeksesteenweg 187

 <x-apple-data-detectors://7/1> 8800 Roeselare-Rumbeke

 <x-apple-data-detectors://7/1> Belgium

------------------------------

BTW: BE  <tel:0832%20787%20857> 0832 787 857

BE02  <tel:3630%208130%205440> 3630 8130 5440

BIC: BBRUBEBB 

------------------------------

Tel:  <tel:+32%2051%2043%2040%2049> +32 51 43 40 49

 ***@***.***> ***@***.***

 <http://www.trifase.be/> www.trifase.be

 <http://www.trifase.be/disclaimer> disclaimer

 

Van: pergolafabio ***@***.***> 
Verzonden: woensdag 11 mei 2022 15:36
Aan: pergolafabio/Hikvision-Addons ***@***.***>
CC: fabianbonte ***@***.***>; Author ***@***.***>
Onderwerp: Re: [pergolafabio/Hikvision-Addons] hikvision sensors won't work. (Issue #14)

 

what device do you have?

**Comment by pergolafabio** [comment]
the type of outdoor i mean? what device is it ? maybe not supported with SDK

**Comment by fabianbonte** [comment]
DS-KD8003-IME1-F-EU

 

mvg,

 

Fabian Bonte

 

 <http://trifase.be/> trifase.be ////

------------------------------

TriFase BVBA

 <x-apple-data-detectors://7/1> Rumbeeksesteenweg 187

 <x-apple-data-detectors://7/1> 8800 Roeselare-Rumbeke

 <x-apple-data-detectors://7/1> Belgium

------------------------------

BTW: BE  <tel:0832%20787%20857> 0832 787 857

BE02  <tel:3630%208130%205440> 3630 8130 5440

BIC: BBRUBEBB 

------------------------------

Tel:  <tel:+32%2051%2043%2040%2049> +32 51 43 40 49

 ***@***.***> ***@***.***

 <http://www.trifase.be/> www.trifase.be

 <http://www.trifase.be/disclaimer> disclaimer

 

Van: pergolafabio ***@***.***> 
Verzonden: woensdag 11 mei 2022 16:32
Aan: pergolafabio/Hikvision-Addons ***@***.***>
CC: fabianbonte ***@***.***>; Author ***@***.***>
Onderwerp: Re: [pergolafabio/Hikvision-Addons] hikvision sensors won't work. (Issue #14)

 

the type of outdoor i mean? what device is it ? maybe not supported with SDK

**Comment by fabianbonte** [comment]
Still started.. (see snapshots)

 





 

mvg,

 

Fabian Bonte

 

 <http://trifase.be/> trifase.be ////

 

------------------------------

TriFase BVBA

 <x-apple-data-detectors://7/1> Rumbeeksesteenweg 187

 <x-apple-data-detectors://7/1> 8800 Roeselare-Rumbeke

 <x-apple-data-detectors://7/1> Belgium

------------------------------

BTW: BE  <tel:0832%20787%20857> 0832 787 857

BE02  <tel:3630%208130%205440> 3630 8130 5440

BIC: BBRUBEBB 

------------------------------

Tel:  <tel:+32%2051%2043%2040%2049> +32 51 43 40 49

 ***@***.***> ***@***.***

 <http://www.trifase.be/> www.trifase.be

 <http://www.trifase.be/disclaimer> disclaimer

 

Van: pergolafabio ***@***.***> 
Verzonden: woensdag 11 mei 2022 16:34
Aan: pergolafabio/Hikvision-Addons ***@***.***>
CC: fabianbonte ***@***.***>; Author ***@***.***>
Onderwerp: Re: [pergolafabio/Hikvision-Addons] hikvision sensors won't work. (Issue #14)

 

that should work, i have the same 8003
is the addon still in started state? or does it stops?

**Comment by pergolafabio** [comment]
Hmm, not sure, should work... Maybe firmware? Try the manual script, where this addon is based on...

**Comment by fabianbonte** [comment]
just tried to use external dns name instaid of http://localipadres, doesn't make any difference

**Comment by fabianbonte** [comment]
rebooted homeassistant, and got a little more in the logbook, but sensors still won't change..

Hikvision SDK Add-on started! Listening for events...
loop[2] find 8 mac and 16 ip
Door unlocked, trying to update: sensor.hikvision_door
Unlocked door LockID : 0
Sensor updating failed
Unlocked by: [49, 48, 48, 49, 48, 49, 49, 48, 48, 48, 49, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Door unlocked, trying to update: sensor.hikvision_door
Unlocked door LockID : 0
Sensor updating failed
Unlocked by: [49, 48, 48, 49, 48, 49, 49, 48, 48, 48, 49, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Door unlocked, trying to update: sensor.hikvision_door
Unlocked door LockID : 0
Sensor updating failed
Unlocked by: [49, 48, 48, 49, 48, 49, 49, 48, 48, 48, 49, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Door unlocked, trying to update: sensor.hikvision_door
Unlocked door LockID : 0
Sensor updating failed
Unlocked by: [49, 48, 48, 49, 48, 49, 49, 48, 48, 48, 49, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

**Comment by pergolafabio** [comment]
Perfect , the IP is indeed local, since it connects to port 8000 on device... The states, that can be external indeed

**Comment by pergolafabio** [comment]
maybe you can put your external address to update the sensors, based on https

**Comment by fabianbonte** [comment]
Hey Fabio, status update werkt al hoor, heb recent een DS-K1T341AM gekocht om eens wat mee te testen, zou dit een andere api zijn dan van de deurpost? 

Met bestaande add-on lukt het niet om de status van het deurcontact van de gezichtsherkenning in te lezen. 

 

Van: pergolafabio ***@***.***> 
Verzonden: dinsdag 11 oktober 2022 10:04
Aan: pergolafabio/Hikvision-Addons ***@***.***>
CC: fabianbonte ***@***.***>; Author ***@***.***>
Onderwerp: Re: [pergolafabio/Hikvision-Addons] hikvision sensors won't work. (Issue #14)

 

maybe you can put your external address to update the sensors, based on https

**Comment by pergolafabio** [comment]
hey, geen flauw idee :-)

Ik heb alleen maar de DS-KD8003, normaal zou de SDK toch hetzelfde moeten zijn

mss idd een andere commando, je kan dit hier vinden;

https://open.hikvision.com/hardware/structures/NET_VCA_FACESNAP_RESULT.html

**Comment by pergolafabio** [comment]
of hier:

http://ftp.hikvision.ru/02.%20Software/05.%20SDK/Device%20Network%20SDK%20Programming%20Manual%28DVR%29.pdf
