### ISSUE TITLE
KV6113 Hangup doesn't work

### ISSUE THREAD

**Issue by fishenebelny** [pergolafabio/Hikvision-Addons#141]
### What happened?

Dear Fabio,

Integration seems works  well.
Though one function from KV6113 doesn't work as expected. 
I cannot hangup call. So what I do:
1. Call from KV6113
2. Answer call (microphone LED lights up)
3. Hang up (Nothing happens)

At the same time it is not a good idea to reject call and then start conversation via Frigate card as when you reject call there is sound message on KV6113.

Can it be fixed somehow as integration seems very interesting.

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

3.0.2

### Installation type

Home Assistant add-on

### Relevant log output

```Text
2023-09-07 15:33:22.818 | INFO     | mqtt_input:_hangup_call_callback:288 - Received hangup command for doorbell: kv6113_doorbell
2023-09-07 15:33:22.818 | DEBUG    | sdk.utils:call_ISAPI:125 - Request body: {"CallSignal": {"cmdType": "hangup"}}
[2023-09-07 15:33:22.823][INF] Private connect 192.168.12.31:8000 sock=158 this=0x5a37a898 cmd=0x117001 port=48888
2023-09-07 15:33:22.825 | DEBUG    | sdk.utils:call_ISAPI:162 - Response status: {
	"requestURL":	"/ISAPI/VideoIntercom/callSignal",
	"statusCode":	4,
	"statusString":	"Invalid Operation",
	"subStatusCode":	"invalidOperation",
	"errorCode":	1073741830,
	"errorMsg":	"invalid operation"
}
2023-09-07 15:33:22.826 | ERROR    | mqtt_input:_hangup_call_callback:300 - Error while hanging up call: ('Error while calling ISAPI /ISAPI/VideoIntercom/callSignal?format=json', 23, 'Device does not support this function.')
```

**Comment by pergolafabio** [comment]
I know, its a pain

Reject , makes indeed a annoying sound, g-you can disable the output sounds on the device, so you dotn hear the beep beep beep
Hangup indeed doesnt, work, since it should only work, if the "answer" works, after
Do you have an indoor device too ?

**Comment by fishenebelny** [comment]
I do not have indoor device. I use it with mobile app Hik-Connect.

**Comment by fishenebelny** [comment]
> ah ok,
> what happens if you send the 'answer" command do the outdoor? (when its in ringing state)
> 
> my outdoor doesnt support answer, since i have "indoor stations"
> 
> If answer should work, then you can send the "hangup" immediately after, and then start two way audio with frigate
> 
> 

I can answer. KV6113 turn on microphone LED in this case. But then I try to hang up. And nothing happens.

**Comment by pergolafabio** [comment]
hmm, thats also for me trial and error :-(
i never got those answer/reject/hangup to work

when i use Frigate, i need to send the reject to indoor, and i disable the sounds on "outdoor" so the visitor doesnt have the beepbeep tone

i"m also quite limited in testing, i only have 1 device, and my outdoor doesnt allow sending "callsignals"

I only added those buttons there for testing

**Comment by fishenebelny** [comment]
> hmm, thats also for me trial and error :-(
> i never got those answer/reject/hangup to work
> 
> when i use Frigate, i need to send the reject to indoor, and i disable the sounds on "outdoor" so the visitor doesnt have the beepbeep tone
> 
> i"m also quite limited in testing, i only have 1 device, and my outdoor doesnt allow sending "callsignals"
> 
> I only added those buttons there for testing

I can help in tests. Tell me what to check and I will try.

**Comment by pergolafabio** [comment]
Since you have outdoor only, it supports all Isapi commands, on the forum thread I have posted all Isapi PDF docs, but the commands are already implemented, I have no idea why it doesn't work

**Comment by pergolafabio** [comment]
Hey, I found this doc, maybe you need to configure the doorbell to call to the "center" and use that template... maybe it's needed for the commands to work like hangup...

In my addon I use the Isapi commands, but they are the same...

https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.hikvisioneurope.com/eu/portal/portal/Technology%2520Partner%2520Program/03-How%2520to/How%2520to%2520Integrate%2520Video%2520Intercom%2520Function.pdf&ved=2ahUKEwiHm6bdupmBAxVHM-wKHT2hDk8QFnoECBIQAQ&usg=AOvVaw3wEbYc8VMC_MQWObe0tLXP

**Comment by fishenebelny** [comment]
I will try ISAPI methods. I have already used some of them before. Maybe during this or next week. 
Thank you!

**Comment by pergolafabio** [comment]
be aware, ISAPI on indoor (port 80) is closed, you cant use it
Only trough the SDK

**Comment by pergolafabio** [comment]
Hey,

dont think it will work with ISAPI, but this looks interesting:

https://www.hikvisioneurope.com/eu/portal/portal/Technology%20Partner%20Program/03-How%20to/How%20to%20Integrate%20Video%20Intercom%20Function.pdf

But its a tolally different concept, you need to configure the doorbell to call to the "center" and then indeed, i tested with the client demo that you can download, you can indeed intercept a call

**Comment by fishenebelny** [comment]
So when I configured button to call to Center all time I got an error message speaking from kv6113. I think as I use with Hik-Connect wihout indoor station I need to do something different.

**Comment by pergolafabio** [comment]
yeah, seems not possible to call center AND indoor together

**Comment by pergolafabio** [comment]
indeed, thats incorrect!!! i fix it soon

But are you sending it now to indoor or outdoor?
Cause for me sending to outdoor, none of the callsignal works for me, my outdoor station doesnt allow "callsignal" commands, only indoor

**Comment by pergolafabio** [comment]
OMG, that was it!!
Now i can send an answer+hangup to my indoor station, and then the outdoor speaker isnt in use anymore to start Frigate!!

wow , fantastic :-)

**Comment by fishenebelny** [comment]
I sent it to outdoor KV6113. 
I think KV6113 allows it in my case as I use it only wiht hik-connect app. I do not have indoor station.
I wanted to buy KH9510 and use it in conjunction with Home Assistant. But your messages on the internet about this station forced me not to but it :)

**Comment by fishenebelny** [comment]
> OMG, that was it!! Now i can send an answer+hangup to my indoor station, and then the outdoor speaker isnt in use anymore to start Frigate!!
> 
> wow , fantastic :-)

Can I do it in the same way using addon? :)

**Comment by pergolafabio** [comment]
yes, just released beta37 , not in final yet, need todo some other stuff first
STOp addon 3.0.2 , copy/paste config in beta37

**Comment by fishenebelny** [comment]
Do I need to add this line
version: '3.0.0-beta.37'

to addon config?

**Comment by pergolafabio** [comment]
Are you using the addon store from HA? Then no need to add anything, it's the same config

**Comment by fishenebelny** [comment]
Yes I use addon store from HA. 
Reboted addon. Still same error with hangup.

**Comment by pergolafabio** [comment]
Huh, have you installed the beta addon? It's a different onew next to 3.0.2

**Comment by fishenebelny** [comment]
I installed Beta version of addon.
There is same issue with hangup (

**Comment by pergolafabio** [comment]
Hmm, that's strange, maybe something wrong with my upload to github

**Comment by fishenebelny** [comment]
Got an update. Now it works in Beta. 
Thank you very much!

**Comment by pergolafabio** [comment]
ahh ok, you were still on beta 36 , perfect, thx for feedback, i think we can close ticket now :-)

Much appreciated!!

**Comment by pergolafabio** [comment]
As for 9510, HA doesn't run indeed on it, very slow, but the Openhab clients works quite good

**Comment by pergolafabio** [comment]
Out of interest , can you send an hangup ? Without sending an answer first?

**Comment by fishenebelny** [comment]
> Out of interest , can you send an hangup ? Without sending an answer first?

I will try later Today. Already left my workspace.

**Comment by fishenebelny** [comment]
> As for 9510, HA doesn't run indeed on it, very slow, but the Openhab clients works quite good

OpenHab is a kind of another Home Assistant? I need to read about it.

**Comment by pergolafabio** [comment]
Its indeed quite the same as HA,..

There is a custom component available to send all entities to Mqtt, so they can be used in Openhab..

My idea was to have the most important entities in Openhab, so i can trigger and use them from the indoor panels .. they have also nice panels

**Comment by fishenebelny** [comment]
> Out of interest , can you send an hangup ? Without sending an answer first?

In this case there is no message on doorbell and callState changes to idle.
