### ISSUE TITLE
MQTT call state and Relay control stopped working

### ISSUE THREAD

**Issue by fishenebelny** [pergolafabio/Hikvision-Addons#142]
### What happened?

Dear Fabio,

I see that Call state and Relay control stopped working in MQTT integrattion.
It dissappeared at night when nothing was happening.
At the same time buttons to reject and answer call work fine.

Such thing also happened when I update MQTT Broker yesterday. I re installed Hikvision Addon and everythin started working fine. But dissapeared again.

Any help will be highly appreciated.

Thank you in advance!

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

3.0.2

### Installation type

Home Assistant add-on

**Comment by pergolafabio** [comment]
hmm , not sure had to tell without any logs :-(

**Comment by pergolafabio** [comment]
when a mqtt entity is being created, the addon cannot delete it, since topics are still present in mqtt broker, so the problem lies elsewhere, non in this addon i believe

**Comment by fishenebelny** [comment]
I have no clue which logs can be helpful. I see that motion events, call events are in Addon logs.
E.g. following what I see in addon logs.
```
2023-09-08 16:16:39.106 | INFO     | event:video_intercom_alarm:109 - Video intercom alarm from kv6113_doorbell
[2023-09-08 16:16:39.101][INF] Alarm[0] IP[192.168.12.31] data_len[568] alarm_len[568] status[430]
2023-09-08 16:16:39.957 | INFO     | mqtt_input:_reject_call_callback:273 - Received reject command for doorbell: kv6113_doorbell
```
Following is what I see in MQTT integration
![image](https://github.com/pergolafabio/Hikvision-Addons/assets/67923540/19381ae8-c2d4-4f08-96e2-49709c570ebf)

**Comment by pergolafabio** [comment]
hmm, not sure, maybe somethign was messed up with the mqtt 
next time, if you see it, dont trestart the addon, maybe something is there in the log

**Comment by fishenebelny** [comment]
I have already restarted it. An the situation is same. I mean that Call state and Relay control are not available even after addons restart.
I restarted:
1. Hikvision addon
2. MQTT Broker addon
Nothing helped.

**Comment by pergolafabio** [comment]
can you try to:
Siop the addon
Delete the device from the MQTT integration, so all entities are gone
Restart the addon
