### ISSUE TITLE
Add Devices from Metzler

### ISSUE THREAD

**Issue by carter300** [pergolafabio/Hikvision-Addons#146]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

Hy, 

could you please also add devices from the manufacturer Metzler?
These are also devices from HikVision, but with slightly adapted firmware. So far only the call status seems to work.

See also: https://edelstahl-tuerklingel.de/vdm10/faq
Good would be Support for VDM 1.0 and 2.0

You're doing great work here and it's certainly not your priority to somehow add German variants, but I thought I'd ask.

**Comment by pergolafabio** [comment]
Hey, well this addon is build based on the SDK that can be downloaded from Hikvision site itself.... 

Is the sdk the same for your device? Then it maybe can work... if not, it will be a totally different addon

Have you tested it?

**Comment by OldShatterhand77** [comment]
Hey, I'm also trying to get a VDM10 from Metzler working with your AddOn. However, the ringstate sensor seems to be quite odd. It changes back from idle and ringing randomly without anyone pushing the doorbell :D 

I attached you the logs of the addon, maybe you can  have a look?

[HikVision VDM10 Log.txt](https://github.com/pergolafabio/Hikvision-Addons/files/14365040/HikVision.VDM10.Log.txt)
