### ISSUE TITLE
KH8520 Answer call doesn't work 

### ISSUE THREAD

**Issue by bavariancoder** [pergolafabio/Hikvision-Addons#149]
### What happened?

Hi,

when i use the "Answer call" function on my indoor station (KH8520) it responds with an error (see log output). The "Reject call" function, however, works.

Any idea, how to get the "Anwer call" to work, so i can end the call and start a conversation via the the Frigate card.

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

3.0.7

### Installation type

Home Assistant add-on

### Relevant log output

```Text
2023-09-21 22:57:41.402 | INFO     | mqtt_input:_answer_call_callback:304 - Received answer command for doorbell: Indoor
2023-09-21 22:57:41.402 | DEBUG    | sdk.utils:call_ISAPI:125 - Request body: {"CallSignal": {"cmdType": "answer"}}
[2023-09-21 22:57:41.407][INF] Private connect 192.168.10.202:8000 sock=189 this=0xa1966eec cmd=0x117001 port=46434
2023-09-21 22:57:41.413 | DEBUG    | sdk.utils:call_ISAPI:162 - Response status: {
	"statusCode":	"4",
	"statusString":	"Invalid Operation",
	"subStatusCode":	"Unknow",
	"errorMsg":	"noRequest",
	"errorCode":	1073770506
}
2023-09-21 22:57:41.414 | ERROR    | mqtt_input:_answer_call_callback:319 - Error while answering call: ('Error while calling ISAPI /ISAPI/VideoIntercom/callSignal?format=json', 29, 'Device operation failed.')
[2023-09-21 22:57:41.413][DBG] SimpleSTDCommandToDvr with out cmd[PUT /ISAPI/VideoIntercom/callSignal?format=json], input size[37], max segment length[262144]
```

**Comment by pergolafabio** [comment]
Hi, in my case the answer commands only works if there is a real call coming in, then I send answer + hangup to my indoor... it works for me on my 9310 indoor device...
Maybe indeed the 8520 is not supported? Then you need to use the reject instead ...

**Comment by bavariancoder** [comment]
Hi, 
with a "real call comming in" you mean that the KD8003 outdoor station calls the indoor station?

Do you know if there is another way to find out if the "anwer" command is supported or not? The CallSingal capabilities contain the "answer" command:

`{
        "CallSignal":   {
                "cmdType":      {
                        "@opt": ["answer", "reject", "bellTimeout", "hangUp", "deviceOnCall"]
                },
                "periodNumber": {
                        "@min": 1,
                        "@max": 9
                },
                "buildingNumber":       {
                        "@min": 1,
                        "@max": 999
                },
                "unitNumber":   {
                        "@min": 1,
                        "@max": 99
                },
                "floorNumber":  {
                        "@min": 0,
                        "@max": 999
                },
                "roomNumber":   {
                        "@min": 1,
                        "@max": 9999
                },
                "unitType":     {
                        "@opt": ["villa", "confirm", "outdoor", "fence", "doorbell", "manage"]
                }
        }
}`

As alternative solution would it be possible to mute the outdoor speaker, reject the call and then unmute the outdoor speaker via the addon? Its only the "beep beep beep" after rejecting the call which bothers me.

**Comment by pergolafabio** [comment]
I also have the 8003, for me it works, by sending the answer command to my indoor station ( real call indeed, that the outdoor speaker stops ringing, I then send the hangup, and they the outdoor speaker is free) then I can start two way audio...

Maybe your indoor station doesn't support answer commands, alltough it should work...

No, I couldnt find any other commands to mute or something like that

**Comment by pergolafabio** [comment]
Let me know if you still need help

**Comment by tevaadarelsol** [comment]
@bavariancoder did you manage to get it working? i am facing the same issue

**Comment by bavariancoder** [comment]
You mean the "Answer call" function on the indoor station? Sadly no, I stopped investigating why the indoor station responds with an error. If you have any idea, let me know.

Currently I use the above mentioned alternative solution (mute outdoor speaker of the KD8003 , reject call via the indoor station and unmute the outdoor speaker) to stop the call / ringing when somebody opens the door. You have to wait a few seconds before unmuting the outdoor speaker or otherwise you will hear the last (two) reject-call-beep.

To speak to the person in front of the door I use the [Asterisk HASS Addon](https://github.com/TECH7Fox/asterisk-hass-addons) registered as indoor extension together with the Linphone Android App or [SIP HASS Card](https://github.com/TECH7Fox/sip-hass-card), because the Frigate approach did not really work (reliably) from me. The two-way-audio did not always work. I am not sure if it is / was a general issue or if it was because of the mute-reject-unmute workaround to stop the initial call. I might be that rejecting the call blocks the two-way-audio for a few seconds.

I am not happy with the current workaround, but due to lack of time I could not try anything else.

**Comment by pergolafabio** [comment]
Yeah, it can be frustrating indeed, I hate the project for this, cause every device acts different:-(

But indeed, the guide I created to register as indoor extension is indeed most stable...

Btw, seems pyvoip is back on track , that one can be used as an alternative... They are working on it and I'm keeping an eye on it... with pyvoip, we can register again as extension, no fancy script needed... And the hopefully transfer the call to ....

I already requested to add the regxml part on the header, needed for registering, and today they released a beta version, including the transfer option...

Gonna try it asap... If that works, no need for asterisk anymore (if video gets through)

**Comment by pergolafabio** [comment]
A while a go , some users were reporting error 23 while sending callsignal commands, in the project I'm sending Isapi commands , as a test, on error 23, I do an SDK command instead...

https://github.com/pergolafabio/Hikvision-Addons/blob/874d58b1a6ef0b1d0fd67f09a8e182ca8b8a1987/hikvision-doorbell/src/mqtt_input.py#L359

Maybe you can try that command instead? You can maybe download the project, change that code error from 23 to 29 , so it uses the SDK method:

https://github.com/pergolafabio/Hikvision-Addons/blob/874d58b1a6ef0b1d0fd67f09a8e182ca8b8a1987/hikvision-doorbell/src/doorbell.py#L150

Maybe , it will work??

**Comment by bavariancoder** [comment]
I already tried it with the following python script in the src folder of the project:
```python
from ctypes import byref, c_byte, sizeof

from sdk.hcnetsdk import NET_DVR_DEVICEINFO_V30, NET_DVR_VIDEO_CALL_PARAM
from sdk.utils import loadSDK

# NET_DVR_GET_CALL_STATUS                  16034
# NET_DVR_SET_CALL_SIGNAL                  16036
HCNetSDK = loadSDK()
HCNetSDK.NET_DVR_Init()
HCNetSDK.NET_DVR_SetValidIP(0, True)

device_info = NET_DVR_DEVICEINFO_V30()

user_id = HCNetSDK.NET_DVR_Login_V30( "<ip>".encode('utf-8'), 8000, "admin".encode('utf-8'), "<password>".encode('utf-8'), device_info)

if (user_id < 0):
    print(
        f"NET_DVR_Login_V30 failed, error code = {HCNetSDK.NET_DVR_GetLastError()}")
    HCNetSDK.NET_DVR_Cleanup()
    exit(1)

gw = NET_DVR_VIDEO_CALL_PARAM()
gw.dwSize = sizeof(NET_DVR_VIDEO_CALL_PARAM)
gw.dwCmdType = 2
gw.wUnitNumber = 1
gw.byRes = (c_byte * 115)()
result = HCNetSDK.NET_DVR_SetDVRConfig(user_id, 16036, 1, byref(gw),255)

print(gw.dwSize)

print("reusult", result)
if result == 0:
    print(HCNetSDK.NET_DVR_GetLastError())

HCNetSDK.NET_DVR_Logout_V30(user_id)
HCNetSDK.NET_DVR_Cleanup()
```

But it did not work and I received the following result:

```
loop[2] find 5 mac and 10 ip
136
reusult 0
23
```

**Comment by pergolafabio** [comment]
Ok :-( 23 = not supported...

**Comment by pergolafabio** [comment]
Hey @bavariancoder @tevaadarelsol , i remember some other project, that guy told me , you first need to drop the RING signal, and the inititate hangup up
i see in this code:

https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/blob/807e9a0f471eb9461ae798e8de57fabf8e679d91/nodes/hikvisionUltimateDoorbell.js#L121

However, i dont have the DELETE ring command included in my fucntion, but you can do this manually for now
first go to your indoor mqtt device and enable this diagnostic entitty

![image](https://github.com/pergolafabio/Hikvision-Addons/assets/43251136/085a899e-4308-42e9-85ff-57614afd6400)


afterwards you can use this service to send ISAPI, you can check the result in the addon log, or in the entitiy attributes
Make sure to enable DEBUG in the addon to see results in the logs

```
service: text.set_value
data:
  value: DELETE /ISAPI/VideoIntercom/ring
target:
  entity_id:
    - text.ds_kd8003_isapi_request
    - text.ds_kh9510_isapi_request
```


SO can you do a real ring event? then send the delete ring, then immedatly try playing with the hangup button? or reject? or answer? maybe it will work then ? if it does, i can easyly add the delete ring in my addon too
Maybe with a combination tests with indoor vs outdoor ?

On my devices, the ring signal never worked, it worked without it, maybe with yours its needed?

**Comment by tevaadarelsol** [comment]
> Hey @bavariancoder @tevaadarelsol , i remember some other project, that guy told me , you first need to drop the RING signal, and the inititate hangup up i see in this code:
> 
> https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/blob/807e9a0f471eb9461ae798e8de57fabf8e679d91/nodes/hikvisionUltimateDoorbell.js#L121
> 
> However, i dont have the DELETE ring command included in my fucntion, but you can do this manually for now first go to your indoor mqtt device and enable this diagnostic entitty
> 
> ![image](https://private-user-images.githubusercontent.com/43251136/295127568-085a899e-4308-42e9-85ff-57614afd6400.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTg4MTksIm5iZiI6MTcwNDc5ODUxOSwicGF0aCI6Ii80MzI1MTEzNi8yOTUxMjc1NjgtMDg1YTg5OWUtNDMwOC00MmU5LTg1ZmYtNTc2MTRhZmQ2NDAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDExMDgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiOTA4MmE3ZWNhMWE0MGE0MzU2OTA3NzcwZDgzMjRmYWNiMmFlMDA3MWNhZDY3N2FkOTc3ZjAxODBjOWI5YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iFS8c30oHWP0IOPNcmz0H2ORzQQAvABJVuytRkCDqZM)
> 
> afterwards you can use this service to send ISAPI, you can check the result in the addon log, or in the entitiy attributes Make sure to enable DEBUG in the addon to see results in the logs
> 
> ```
> service: text.set_value
> data:
>   value: DELETE /ISAPI/VideoIntercom/ring
> target:
>   entity_id:
>     - text.ds_kd8003_isapi_request
>     - text.ds_kh9510_isapi_request
> ```
> 
> SO can you do a real ring event? then send the delete ring, then immedatly try playing with the hangup button? or reject? or answer? maybe it will work then ? if it does, i can easyly add the delete ring in my addon too Maybe with a combination tests with indoor vs outdoor ?
> 
> On my devices, the ring signal never worked, it worked without it, maybe with yours its needed?

Tried this:

2024-01-09 12:46:46.843 | INFO     | event:video_intercom_alarm:120 - Video intercom alarm from DS-HD8003
2024-01-09 12:46:54.649 | DEBUG    | mqtt_input:_isapi_input_callback:474 - Received input text for doorbell: DS-HD8003
2024-01-09 12:46:54.650 | DEBUG    | sdk.utils:call_ISAPI:125 - Call ISAPI request method url body: DELETE /ISAPI/VideoIntercom/ring  
2024-01-09 12:46:54.655 | DEBUG    | sdk.utils:call_ISAPI:165 - Response output: 
2024-01-09 12:46:54.657 | DEBUG    | mqtt_input:_isapi_input_callback:474 - Received input text for doorbell: DS-KH6320
2024-01-09 12:46:54.658 | DEBUG    | sdk.utils:call_ISAPI:125 - Call ISAPI request method url body: DELETE /ISAPI/VideoIntercom/ring  
2024-01-09 12:46:54.679 | DEBUG    | sdk.utils:call_ISAPI:165 - Response output: 
2024-01-09 12:46:58.706 | INFO     | mqtt_input:_answer_call_callback:341 - Received answer command for doorbell: DS-HD8003
2024-01-09 12:46:58.706 | DEBUG    | sdk.utils:call_ISAPI:125 - Call ISAPI request method url body: PUT /ISAPI/VideoIntercom/callSignal?format=json {"CallSignal": {"cmdType": "answer"}} 
2024-01-09 12:46:58.711 | DEBUG    | sdk.utils:call_ISAPI:162 - Response status: {
	"requestURL":	"/ISAPI/VideoIntercom/callSignal",
	"statusCode":	6,
	"statusString":	"Invalid Content",
	"subStatusCode":	"badXmlContent",
	"errorCode":	1610612739,
	"errorMsg":	"Wrong XMLcontent"
}
2024-01-09 12:46:58.711 | ERROR    | mqtt_input:_answer_call_callback:354 - Error while answering call with ISAPI: ('Error while calling ISAPI /ISAPI/VideoIntercom/callSignal?format=json', 11, 'The data sent to the device is illegal, or the data received from the device error.  E.g. The input data is not supported by the device for remote configuration.')
2024-01-09 12:47:03.198 | INFO     | mqtt_input:_hangup_call_callback:318 - Received hangup command for doorbell: DS-HD8003
2024-01-09 12:47:03.198 | DEBUG    | sdk.utils:call_ISAPI:125 - Call ISAPI request method url body: PUT /ISAPI/VideoIntercom/callSignal?format=json {"CallSignal": {"cmdType": "hangUp"}} 
2024-01-09 12:47:03.208 | DEBUG    | sdk.utils:call_ISAPI:162 - Response status: {
	"requestURL":	"/ISAPI/VideoIntercom/callSignal",
	"statusCode":	6,
	"statusString":	"Invalid Content",
	"subStatusCode":	"badXmlContent",
	"errorCode":	1610612739,
	"errorMsg":	"Wrong XMLcontent"
}
2024-01-09 12:47:03.208 | ERROR    | mqtt_input:_hangup_call_callback:331 - Error while Hanging up the call with ISAPI: ('Error while calling ISAPI /ISAPI/VideoIntercom/callSignal?format=json', 11, 'The data sent to the device is illegal, or the data received from the device error.  E.g. The input data is not supported by the device for remote configuration.')
2024-01-09 12:47:05.062 | INFO     | mqtt_input:_answer_call_callback:341 - Received answer command for doorbell: DS-KH6320
2024-01-09 12:47:05.062 | DEBUG    | sdk.utils:call_ISAPI:125 - Call ISAPI request method url body: PUT /ISAPI/VideoIntercom/callSignal?format=json {"CallSignal": {"cmdType": "answer"}} 
2024-01-09 12:47:05.068 | DEBUG    | sdk.utils:call_ISAPI:162 - Response status: {
	"statusCode":	"4",
	"statusString":	"Invalid Operation",
	"subStatusCode":	"Unknow",
	"errorMsg":	"noRequest",
	"errorCode":	1073770506
}
2024-01-09 12:47:05.069 | ERROR    | mqtt_input:_answer_call_callback:354 - Error while answering call with ISAPI: ('Error while calling ISAPI /ISAPI/VideoIntercom/callSignal?format=json', 29, 'Device operation failed.')
2024-01-09 12:47:06.059 | INFO     | mqtt_input:_hangup_call_callback:318 - Received hangup command for doorbell: DS-KH6320
2024-01-09 12:47:06.059 | DEBUG    | sdk.utils:call_ISAPI:125 - Call ISAPI request method url body: PUT /ISAPI/VideoIntercom/callSignal?format=json {"CallSignal": {"cmdType": "hangUp"}} 
2024-01-09 12:47:06.065 | DEBUG    | sdk.utils:call_ISAPI:162 - Response status: {
	"statusCode":	"4",
	"statusString":	"Invalid Operation",
	"subStatusCode":	"Unknow",
	"errorMsg":	"noRequest",
	"errorCode":	1073770506
}
2024-01-09 12:47:06.066 | ERROR    | mqtt_input:_hangup_call_callback:331 - Error while Hanging up the call with ISAPI: ('Error while calling ISAPI /ISAPI/VideoIntercom/callSignal?format=json', 29, 'Device operation failed.')

**Comment by pergolafabio** [comment]
hmm, seems the DELETE ring command doesnt do anything on your device :-(

**Comment by tevaadarelsol** [comment]
@bavariancoder @pergolafabio I am pleased to bring some great news: I managed to get the answer and hang up buttons working!

Background:
At home I have several VLANs set up that, depending on their purpose, have or do not have access to the Internet. The doorbell is connected to the CCTV VLAN, which has no Internet connection. This is for privacy. Therefore, the doorbell had never been registered with Hikvision's servers, since it had never been connected to the internet.

To do a final test, I connected the doorbell to a WiFi with Internet access, and I registered the device in the Hik-Connect APP. After this, I made a test call and I was able to verify that the answer and hang up buttons now work. Even if I reconnect the doorbell to a VLAN with no internet connection.

It seems that something must be activated at the configuration level in the doorbell when it connects to the Hikvision servers, so that even if you leave it without internet again, it continues to work.

So well, I think it's great news for all of us who didn't have this work for us.

Nice!

**Comment by pergolafabio** [comment]
Wow , that's indeed great news!!! I would never thought that!! Great finding... Now it's indeed more clear that it works for some and for some not!!! Gonna update docs soon! Thnx for sharing this

**Comment by bavariancoder** [comment]
Thanks that is really good news. This really explains it because wether my
doorbell (KD8003) nor my indoor station were allowed to connect to the
internet so far.

Pergola Fabio ***@***.***> schrieb am Do., 11. Jan. 2024,
10:10:

**Comment by pergolafabio** [comment]
can you verify the behaviour @bavariancoder  , when you connect indoor to hikconnect or at least enable it in ivms?

**Comment by tevaadarelsol** [comment]
Update: it seems to work while not connected to internet but only unitl a reboot. Then, it needs to be connected to internet again to work. This is not a problem for those who has the doorbell connected to internet, but something to take into the account for those who don´t.

**Comment by pergolafabio** [comment]
yeah, probably the callsignal is used bu hikconnect, i sniffed that before with the hikconnect app, thats why it maybe indeed doesnrt work, alltough its strange that reject does indeed work

**Comment by pergolafabio** [comment]
gonna close now!! :-)

**Comment by pergolafabio** [comment]
Btw , in ivms, you can also define a custom IP for hikconnect cloud, maybe it's enough to enter just somekind of internal IP? So it thinks it's connected?

**Comment by pergolafabio** [comment]
Gonna reopen , there must be a way without hikconnect!! The payload i'm sending is quite basic, its enough for the reject, but maybe not enough without hikconnect

current payload: ` {"CallSignal": {"cmdType": "answer"}}`

But from the docs, it can be below, maybe we need to send to outdoor? maybe we send to indoor but that the indoor "thinks" it comes from the hikconnect app! So the source can be different
In the addon, i also added a "caller info" button, that gives you attributes about the building nr etc ... But maybe we need the caller info from hikconnect! so we can define hikconnect as a 'src'

@dragonspy00 tried this too, but we always tested before the "indoor" as a source and not hikconnect

I'm gonna wireshark hikconnect again, and send the "caller info" command to it to see what the "src" attributes are...


		"cmdType":	{
			"@opt":	["answer", "reject", "bellTimeout", "hangUp", "deviceOnCall"]
		},
		"periodNumber":	{
			"@min":	1,
			"@max":	9
		},
		"buildingNumber":	{
			"@min":	1,
			"@max":	999
		},
		"unitNumber":	{
			"@min":	1,
			"@max":	99
		},
		"floorNumber":	{
			"@min":	0,
			"@max":	999
		},
		"roomNumber":	{
			"@min":	1,
			"@max":	9999
		},
		"unitType":	{
			"@opt":	["villa", "confirm", "outdoor", "fence", "doorbell", "manage"]
		},
		"coderType":	{
			"@opt":	["ezviz", "dsp"]
		},
		"model":	{
			"@min":	1,
			"@max":	64
		}
	}
}
```

example payload (not working)


```
{
      "CallSignal": {  
            "cmdType":  "answer",  
            "sessionId":  "test",  
            "src": {    
                  "periodNumber":  1,    
                  "buildingNumber":  1,
                  "unitNumber":  1,      
                  "floorNumber":  1,     
                  "roomNumber":  1,      
                  "devIndex":  1,  
                  "communityNumber":  "test", 
                  "callNumber":  "12312312311",     
                  "unitType":  "villa"
 
            },
            "target": { 
                  "periodNumber":  1,    
                  "buildingNumber":  1,  
                  "unitNumber":  1,      
                  "floorNumber":  1,     
                  "roomNumber":  1,      
                  "devIndex":  1,  
                  "communityNumber":  "test", 
                  "callNumber":  "12312312311",     
                  "unitType":  "indoor"
            }
      }
}
```

**Comment by pergolafabio** [comment]
and here is callerinfo from the hikconnect app, sended the curl to hikconnect cloud, when hikconnect was actually ringing
maybe wit all that info, we can figure out how to make a fake hikconnect answer command to the indoor

`{"data":"{"CallerInfo":{"buildingNo":1,"floorNo":0,"zoneNo":1,"unitNo":1,"devNo":0,"devType":1,"lockNum":1,"status":"ring"}}","meta":{"code":200,"message":"操作成功","moreInfo":null}}                       `

**Comment by pergolafabio** [comment]
anyone an update here? :-)

**Comment by bavariancoder** [comment]
So I did some tests today and I can confirm that answering and hanging up the call via the addon works when the indoor station has an internet connection via WiFi and is registered as device in Hik-Connect:

```
2024-02-04 21:45:45.187 | INFO     | mqtt_input:_answer_call_callback:341 - Received answer command for doorbell: Indoor Station
2024-02-04 21:45:45.191 | DEBUG    | sdk.utils:call_ISAPI:125 - Call ISAPI request method url body: PUT /ISAPI/VideoIntercom/callSignal?format=json {"CallSignal": {"cmdType": "answer"}} 
[2024-02-04 21:45:45.199][INF] Private connect 192.168.xxx.xxx:8000 sock=201 this=0x6bf87e1c cmd=0x117001 port=38942

2024-02-04 21:45:45.317 | DEBUG    | sdk.utils:call_ISAPI:165 - Response output: {
	"statusCode":	"1",
	"statusString":	"OK",
	"errorMsg":	"ok",
	"errorCode":	1
}
[2024-02-04 21:45:45.317][DBG] SimpleSTDCommandToDvr with out cmd[PUT /ISAPI/VideoIntercom/callSignal?format=json], input size[37], max segment length[262144]

2024-02-04 21:45:47.322 | INFO     | mqtt_input:_hangup_call_callback:318 - Received hangup command for doorbell: Indoor Station
2024-02-04 21:45:47.323 | DEBUG    | sdk.utils:call_ISAPI:125 - Call ISAPI request method url body: PUT /ISAPI/VideoIntercom/callSignal?format=json {"CallSignal": {"cmdType": "hangUp"}} 
[2024-02-04 21:45:47.335][INF] Private connect 192.168.xxx.xxx:8000 sock=201 this=0x6bf87e1c cmd=0x117001 port=38964

[2024-02-04 21:45:47.867][INF] Alarm[0] IP[192.168.xxx.xxx] data_len[568] alarm_len[568] status[430]

2024-02-04 21:45:47.867 | DEBUG    | event:_handle_callback:220 - Callback invoked from SDK
2024-02-04 21:45:47.868 | DEBUG    | event:_invoke_handlers:192 - Invoking 2 handlers
2024-02-04 21:45:47.869 | INFO     | mqtt:video_intercom_alarm:334 - Call dismissed, updating sensor 
topic_prefix: sensor/Doorbell-Frontdoor/Call-state
config_topic: homeassistant/sensor/Doorbell-Frontdoor/Call-state/config
state_topic: hmd/sensor/Doorbell-Frontdoor/Call-state/state
wrote_configuration: True
        
2024-02-04 21:45:47.882 | INFO     | event:video_intercom_alarm:120 - Video intercom alarm from Doorbell Frontdoor
2024-02-04 21:45:50.462 | DEBUG    | sdk.utils:call_ISAPI:165 - Response output: {
	"statusCode":	"1",
	"statusString":	"OK",
	"errorMsg":	"ok",
	"errorCode":	1
```

But as soon as I disconnect the indoor station from the internet (disable WiFi connection) it does no longer work:
```
2024-02-04 21:47:02.519 | INFO     | mqtt_input:_answer_call_callback:341 - Received answer command for doorbell: Indoor Station
2024-02-04 21:47:02.523 | DEBUG    | sdk.utils:call_ISAPI:125 - Call ISAPI request method url body: PUT /ISAPI/VideoIntercom/callSignal?format=json {"CallSignal": {"cmdType": "answer"}} 
[2024-02-04 21:47:02.531][INF] Private connect 192.168.xxx.xxx:8000 sock=201 this=0x6bf87e1c cmd=0x117001 port=48510

2024-02-04 21:47:02.541 | DEBUG    | sdk.utils:call_ISAPI:162 - Response status: {
	"statusCode":	"4",
	"statusString":	"Invalid Operation",
	"subStatusCode":	"Unknow",
	"errorMsg":	"noRequest",
	"errorCode":	1073770506
}
2024-02-04 21:47:02.545 | ERROR    | mqtt_input:_answer_call_callback:354 - Error while answering call with ISAPI: ('Error while calling ISAPI /ISAPI/VideoIntercom/callSignal?format=json', 29, 'Device operation failed.')
[2024-02-04 21:47:02.541][DBG] SimpleSTDCommandToDvr with out cmd[PUT /ISAPI/VideoIntercom/callSignal?format=json], input size[37], max segment length[262144]

2024-02-04 21:47:04.465 | INFO     | mqtt_input:_hangup_call_callback:318 - Received hangup command for doorbell: Indoor Station
2024-02-04 21:47:04.466 | DEBUG    | sdk.utils:call_ISAPI:125 - Call ISAPI request method url body: PUT /ISAPI/VideoIntercom/callSignal?format=json {"CallSignal": {"cmdType": "hangUp"}} 
[2024-02-04 21:47:04.476][INF] Private connect 192.168.xxx.xxx:8000 sock=201 this=0x6bf87e1c cmd=0x117001 port=48524

2024-02-04 21:47:04.487 | DEBUG    | sdk.utils:call_ISAPI:162 - Response status: {
	"statusCode":	"4",
	"statusString":	"Invalid Operation",
	"subStatusCode":	"Unknow",
	"errorMsg":	"noRequest",
	"errorCode":	1073770506
}
2024-02-04 21:47:04.490 | ERROR    | mqtt_input:_hangup_call_callback:331 - Error while Hanging up the call with ISAPI: ('Error while calling ISAPI /ISAPI/VideoIntercom/callSignal?format=json', 29, 'Device operation failed.')
[2024-02-04 21:47:04.487][DBG] SimpleSTDCommandToDvr with out cmd[PUT /ISAPI/VideoIntercom/callSignal?format=json], input size[37], max segment length[262144]
```

It seems that the indoor stations needs to be connected to the Hik Connect server or at least needs to think that it is still connected. 

@tevaadarelsol how do you disconnect the indoor station from the internet? 

Next step is to capture the traffic from / to the indoor station, maybe i can find something.

**Comment by tevaadarelsol** [comment]
> So I did some tests today and I can confirm that answering and hanging up the call via the addon works when the indoor station has an internet connection via WiFi and is registered as device in Hik-Connect:
> 
> ```
> 2024-02-04 21:45:45.187 | INFO     | mqtt_input:_answer_call_callback:341 - Received answer command for doorbell: Indoor Station
> 2024-02-04 21:45:45.191 | DEBUG    | sdk.utils:call_ISAPI:125 - Call ISAPI request method url body: PUT /ISAPI/VideoIntercom/callSignal?format=json {"CallSignal": {"cmdType": "answer"}} 
> [2024-02-04 21:45:45.199][INF] Private connect 192.168.xxx.xxx:8000 sock=201 this=0x6bf87e1c cmd=0x117001 port=38942
> 
> 2024-02-04 21:45:45.317 | DEBUG    | sdk.utils:call_ISAPI:165 - Response output: {
> 	"statusCode":	"1",
> 	"statusString":	"OK",
> 	"errorMsg":	"ok",
> 	"errorCode":	1
> }
> [2024-02-04 21:45:45.317][DBG] SimpleSTDCommandToDvr with out cmd[PUT /ISAPI/VideoIntercom/callSignal?format=json], input size[37], max segment length[262144]
> 
> 2024-02-04 21:45:47.322 | INFO     | mqtt_input:_hangup_call_callback:318 - Received hangup command for doorbell: Indoor Station
> 2024-02-04 21:45:47.323 | DEBUG    | sdk.utils:call_ISAPI:125 - Call ISAPI request method url body: PUT /ISAPI/VideoIntercom/callSignal?format=json {"CallSignal": {"cmdType": "hangUp"}} 
> [2024-02-04 21:45:47.335][INF] Private connect 192.168.xxx.xxx:8000 sock=201 this=0x6bf87e1c cmd=0x117001 port=38964
> 
> [2024-02-04 21:45:47.867][INF] Alarm[0] IP[192.168.xxx.xxx] data_len[568] alarm_len[568] status[430]
> 
> 2024-02-04 21:45:47.867 | DEBUG    | event:_handle_callback:220 - Callback invoked from SDK
> 2024-02-04 21:45:47.868 | DEBUG    | event:_invoke_handlers:192 - Invoking 2 handlers
> 2024-02-04 21:45:47.869 | INFO     | mqtt:video_intercom_alarm:334 - Call dismissed, updating sensor 
> topic_prefix: sensor/Doorbell-Frontdoor/Call-state
> config_topic: homeassistant/sensor/Doorbell-Frontdoor/Call-state/config
> state_topic: hmd/sensor/Doorbell-Frontdoor/Call-state/state
> wrote_configuration: True
>         
> 2024-02-04 21:45:47.882 | INFO     | event:video_intercom_alarm:120 - Video intercom alarm from Doorbell Frontdoor
> 2024-02-04 21:45:50.462 | DEBUG    | sdk.utils:call_ISAPI:165 - Response output: {
> 	"statusCode":	"1",
> 	"statusString":	"OK",
> 	"errorMsg":	"ok",
> 	"errorCode":	1
> ```
> 
> But as soon as I disconnect the indoor station from the internet (disable WiFi connection) it does no longer work:
> 
> ```
> 2024-02-04 21:47:02.519 | INFO     | mqtt_input:_answer_call_callback:341 - Received answer command for doorbell: Indoor Station
> 2024-02-04 21:47:02.523 | DEBUG    | sdk.utils:call_ISAPI:125 - Call ISAPI request method url body: PUT /ISAPI/VideoIntercom/callSignal?format=json {"CallSignal": {"cmdType": "answer"}} 
> [2024-02-04 21:47:02.531][INF] Private connect 192.168.xxx.xxx:8000 sock=201 this=0x6bf87e1c cmd=0x117001 port=48510
> 
> 2024-02-04 21:47:02.541 | DEBUG    | sdk.utils:call_ISAPI:162 - Response status: {
> 	"statusCode":	"4",
> 	"statusString":	"Invalid Operation",
> 	"subStatusCode":	"Unknow",
> 	"errorMsg":	"noRequest",
> 	"errorCode":	1073770506
> }
> 2024-02-04 21:47:02.545 | ERROR    | mqtt_input:_answer_call_callback:354 - Error while answering call with ISAPI: ('Error while calling ISAPI /ISAPI/VideoIntercom/callSignal?format=json', 29, 'Device operation failed.')
> [2024-02-04 21:47:02.541][DBG] SimpleSTDCommandToDvr with out cmd[PUT /ISAPI/VideoIntercom/callSignal?format=json], input size[37], max segment length[262144]
> 
> 2024-02-04 21:47:04.465 | INFO     | mqtt_input:_hangup_call_callback:318 - Received hangup command for doorbell: Indoor Station
> 2024-02-04 21:47:04.466 | DEBUG    | sdk.utils:call_ISAPI:125 - Call ISAPI request method url body: PUT /ISAPI/VideoIntercom/callSignal?format=json {"CallSignal": {"cmdType": "hangUp"}} 
> [2024-02-04 21:47:04.476][INF] Private connect 192.168.xxx.xxx:8000 sock=201 this=0x6bf87e1c cmd=0x117001 port=48524
> 
> 2024-02-04 21:47:04.487 | DEBUG    | sdk.utils:call_ISAPI:162 - Response status: {
> 	"statusCode":	"4",
> 	"statusString":	"Invalid Operation",
> 	"subStatusCode":	"Unknow",
> 	"errorMsg":	"noRequest",
> 	"errorCode":	1073770506
> }
> 2024-02-04 21:47:04.490 | ERROR    | mqtt_input:_hangup_call_callback:331 - Error while Hanging up the call with ISAPI: ('Error while calling ISAPI /ISAPI/VideoIntercom/callSignal?format=json', 29, 'Device operation failed.')
> [2024-02-04 21:47:04.487][DBG] SimpleSTDCommandToDvr with out cmd[PUT /ISAPI/VideoIntercom/callSignal?format=json], input size[37], max segment length[262144]
> ```
> 
> It seems that the indoor stations needs to be connected to the Hik Connect server or at least needs to think that it is still connected.
> 
> @tevaadarelsol how do you disconnect the indoor station from the internet?
> 
> Next step is to capture the traffic from / to the indoor station, maybe i can find something.

I disconnect It by turning wifi off in the indoor unit settings

**Comment by pergolafabio** [comment]
maybe setting an invalid DNS entry ?

**Comment by bavariancoder** [comment]
invalid DNS entry doesn't work. No matter how I block the internet access / access to litedev.eu.hik-connect.com it doesn't work. 

I captured the traffic between the indoor station and the hik connect server and what I can see is that the indoor stations sends the following request multiple times via UDP:

```
<?xml version="1.0" encoding="utf-8"?>
<Request>
<DevSerial><serial no of the indoor station></DevSerial>
</Request>
```
And the hik connect or something external answers with:
```
<?xml version='1.0' encoding='utf-8' ?>
<Response>
	<Result>0</Result>
	<Client Address="<my public ip>" Port="32946"/>
</Response>
```

I think the indoor stations uses this request-response-ping-pong to detect that the connection to hik-connect is established and then accepts the ISAPI answer call and hang up request.

**Comment by pergolafabio** [comment]
It's still strange that answer doesn't work, while reject works... My guess it's still an issue with the correct Json payload

**Comment by bavariancoder** [comment]
But the Json payload from the addon to indoor station should not change no matter if the Indoor station is connected to hik-connect or not, right? 

And at least in my test the outdoor station still had no access to the internet so hik connect can't influence the call from the outdoor station to the indoor station.

**Comment by pergolafabio** [comment]
the problem is, i dont know! the payload used by the addon is very basic, maybe it needs to be extended
Its not documented anywere, its a bit of guessing
