### ISSUE TITLE
No callstatus, just motion

### ISSUE THREAD

**Issue by pickonedev** [pergolafabio/Hikvision-Addons#15]
Hi!

I am using a hikvision DS-KB6003-WIP. I have installed the repostiory, then the HikVision SDK Addon, I made all the configurations, motion it is working, but not the call status. And... this is the only reason for which I tried the addon, I need the callstatus status :-).

This is the log:

```
Hikvision SDK Add-on started! Listening for events...
loop[2] find 8 mac and 16 ip
Motion detected, trying to update: sensor.hikvision_motion
Motion detected, trying to update: sensor.hikvision_motion
Motion detected, trying to update: sensor.hikvision_motion
Motion detected, trying to update: sensor.hikvision_motion
Motion detected, trying to update: sensor.hikvision_motion
Motion detected, trying to update: sensor.hikvision_motion
Motion detected, trying to update: sensor.hikvision_motion
Motion detected, trying to update: sensor.hikvision_motion
```

Any idea how to make it work?
Thank you in advance!

Edit:

I have tried this:
```
curl -i --digest -u admin:xxxx http://192.168.0.70/ISAPI/VideoIntercom/callStatus?format=json&channelType=tripartitePlatform
for other models:
curl -i --digest -u admin:xxx http://192.168.x.x/ISAPI/VideoIntercom/callStatus?format=json
Should give as output : “idle” , “ring” , “onCall”
```
But I get "Can't locate the url#" every time....

**Comment by pergolafabio** [comment]
I think you have an old device , it's not supported with ISAPi or SDK, you can try the hikconnect cloud integration...

**Comment by pickonedev** [comment]
Wow, too fast answer :-D

Well, yes, I am using that integration, but as a cloud, it is not always responding... Sometimes I push the button and it is not doing anything... Sometimes means 5-10% of cases

**Comment by pergolafabio** [comment]
Do you have indoor stations?

**Comment by pickonedev** [comment]
I don't understand the question, sorry. I only have this doorbell, which is connected to wifi and a power adapter (no batteries)

**Comment by pergolafabio** [comment]
Ah, no display inside? Well, you can connect your doorstation to a PBX , and then capture the PBX signakl

**Comment by pickonedev** [comment]
No, no "original" display. I have a tablet on which I see the camera, but nothing else... :-(
