### ISSUE TITLE
Support for K1T605 model

### ISSUE THREAD

**Issue by Jimmyboy83** [pergolafabio/Hikvision-Addons#16]
Hi! Thanks for your addon.
Can You add support for K1T605 model?

**Comment by Jimmyboy83** [comment]
What is PR?

**Comment by pergolafabio** [comment]
a pull requests to my addon with your new code

**Comment by pergolafabio** [comment]
Sorry, want to help, but I don't have such a device :-(

**Comment by Jimmyboy83** [comment]
Can I collect any logs or any information to help?

пт, 24 июн. 2022 г., 19:47 pergolafabio ***@***.***>:

**Comment by pergolafabio** [comment]
what kind of device is it? is it an intercom ? what feature do you want?
