### ISSUE TITLE
Motion as sensor not just trigger

### ISSUE THREAD

**Issue by mihaimdinca** [pergolafabio/Hikvision-Addons#160]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

It would be nice to have the motion detection available as a sensor and not just a trigger. I know this should be possible to do as a template sensor but honestly I got stuck in writing one. Any help would be appreciated. I believe this would be useful in Home Assistant with cards that are condition based on sensor state.

**Comment by pergolafabio** [comment]
Hi, 
If you go to the page: integrations/mqtt/device ..
There is an automation section, just click on the motion trigger and create the automation you need...

**Comment by pergolafabio** [comment]
You can then turn for example an Boolean to "on" wait 2 sec and turn it off again

**Comment by mihaimdinca** [comment]
Ok. Thank you. I was trying to build a template sensor using home assistant helper so I wouldn't have to use an automation. I failed so far. I am not even totally sure that this is possible. Anyway, thank you for your help and quick response. Have a wonderful day!

**Comment by pergolafabio** [comment]
No, it's indeed easier to build an automation from the trigger itself

You can use the delay function to turn the Boolean back to off after x seconds
