### ISSUE TITLE
Frigate custom card for doorbel

### ISSUE THREAD

**Issue by Sonusss** [pergolafabio/Hikvision-Addons#169]
### What happened?

I tried your example for the frigate custom card but when trying answer or hangup call I get an error in HA:
<< Failed to call service button/press. must contain at least one of entity_id, device_id, area_id. >>

I tried to modify the card yaml as follow to comply with new button_press service but still:
  - type: custom:frigate-card-menu-icon
    icon: mdi:phone
    tap_action:
      - action: custom:frigate-card-action
        frigate_card_action: microphone_mute
      - action: call-service
        service: button.press
        service_data: {}
        target:
          entity_id: button.gate_answer_call
      - action: custom:frigate-card-action
        frigate_card_action: unmute
      - action: custom:frigate-card-action
        frigate_card_action: microphone_unmute

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

latest from 2 weeks ago

### Installation type

Docker container (standalone)

### Relevant configuration

```YAML
HA core 2023.10.5
```

**Comment by pergolafabio** [comment]
Hi, otherwise, have a look at the frigate GitHub page, there are lots of examples there...
