### ISSUE TITLE
DS-KH6320-WTE1

### ISSUE THREAD

**Issue by TokarevSergey** [pergolafabio/Hikvision-Addons#17]
Good afternoon. Please tell me if this integration supports DS-KH6320-WTE1 monitor? Will the eight alarm sensors built into it and the two switches be displayed? Will it be possible to switch the alarm scenes and is it possible to supply the alarm? Thank you.

Добрый день. Скажите пожалуйста поддерживает ли эта интеграция монитор DS-KH6320-WTE1? Будут ли отображаться восемь тревожных датчиков встроенных в нее и два переключателя? Появится ли возможность переключать сцены сигнализации и возможна ли поставка на сигнализацию? Спасибо.

**Comment by pergolafabio** [comment]
Hi, no it only supports the outdoor , not indoor
it will gve you sensor for door/motion/ring events

alltough i have in the code, some tampering alarm events, it should be visible in the log...
https://github.com/pergolafabio/Hikvision-Addons/blob/main/hikvison-sdk/hik.py#L45

try it , if it works, i can make a sensor for it

i dont have any alarms, so cant test
