### ISSUE TITLE
Hikvision Doorbell and Asterisk 

### ISSUE THREAD

**Issue by frank81** [pergolafabio/Hikvision-Addons#170]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

Ciao Fabio,
una informazione, la tua integrazione con asterisk prevede per forza l'uso di home assistant? a casa ho un centralino asterisk e volevo integrarlo con il citofono hikvision facendo in modo che funzioni sia la chiamata tramite il loro cloud che sul mio centralino. è possibile? Grazie

**Comment by frank81** [comment]
Hello Fabio,
I have a question. Does your integration with Asterisk necessarily require the use of Home Assistant? At home, I have an Asterisk PBX, and I wanted to integrate it with the Hikvision intercom, making sure that both the call through their cloud and on my PBX work. Is it possible? Thank you.

**Comment by frank81** [comment]
Can you explain to me how I should proceed? Do I only need to use the Python script?

**Comment by pergolafabio** [comment]
Depends how you want to proceed, my script is not needed , you can also use plain sip on the devices

**Comment by pergolafabio** [comment]
Do you have an indoor? You can do this maybe...

https://github.com/pergolafabio/Hikvision-Addons/blob/main/asterisk/asterisk.as.indoor.md
