### ISSUE TITLE
Upgrade to the Frigate 0.13-beta to have current go2rtc

### ISSUE THREAD

**Issue by iBobik** [pergolafabio/Hikvision-Addons#173]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

None

### Your feature request

Current beta already have go2rtc upgraded, so how about to upgrade to this Frigate version?

**Comment by pergolafabio** [comment]
Hi x there is no go2rtc used in my addon, so not sure what you mean?

**Comment by iBobik** [comment]
Hi, i mean Frigate beta version which has go2rtc updated

**Comment by pergolafabio** [comment]
ah, you want me to update my guide? yeah, i will do that once its out of beta :-)
But i wait for the new frigate hass card, with the new card coming out, there is no need for frigate NVR anymore, much easier
