### ISSUE TITLE
Call State unavailable 

### ISSUE THREAD

**Issue by jimfranssen** [pergolafabio/Hikvision-Addons#174]
### What happened?

The call state sensor is unavailable. In the Addon log I do see that the call state is updated whenever the doorbell rings or when the call is dismissed (see below).

![CallStateLog](https://github.com/pergolafabio/Hikvision-Addons/assets/51799662/8045eccd-fba9-4f2d-85bd-d06d9591f76e)

Why is the Call State sensor unavailable in the MQTT device section ? 
Below you also find MQTT info for the Call State sensor 

![Scherm­afbeelding 2023-12-14 om 14 56 18](https://github.com/pergolafabio/Hikvision-Addons/assets/51799662/989f7e38-6478-40dc-813c-ab60fa233ee5)
 
I am using the add-on in combination with Hikvisio DS-KV6113-WPE1(C) with Firmware V2.2.65

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

3.0.12

### Installation type

Home Assistant add-on

**Comment by pergolafabio** [comment]
i would try to stop the addon; delete the mqtt intergartion (devices) , then restart addon, so everything gets recreated
that should fix it

**Comment by jimfranssen** [comment]
I did as you suggested. Everything works fine now. Sorry for doubting your add-on. Perhaps it is good to add this to the documentation.

**Comment by fatmacheto** [comment]
@pergolafabio 

Hi, 

I am trying to setup an automation on incoming call but I dont see the states anywhere:

![image](https://github.com/pergolafabio/Hikvision-Addons/assets/25221505/6018871a-6393-43e0-9351-f099ecc848d4)

**Comment by pergolafabio** [comment]
hey, the call state is a sensor, you can build your autmations based on that sensor:
example:
![image](https://github.com/pergolafabio/Hikvision-Addons/assets/43251136/c4b307ca-bfd2-4caf-ad67-28b33a9fe07c)

**Comment by pergolafabio** [comment]
also make sure to make call first , and see if the sensor changes, then you have the options avaible

**Comment by fatmacheto** [comment]
Hi, i am using exactly this sensor but as you can see from the screenshots the states available are  any state, unavailable and unknown.

**Comment by pergolafabio** [comment]
ok, is the addon still running? do you see any error in the addon log?
if still running... try to stop adddon, delete the whole mqtt device (integration) , then start addon again

**Comment by fatmacheto** [comment]
Yes,I followed your recommendation on several similar issues that you replied before posting in this thread but it doesn’t help. I tested the entity shows the actual call status.All I see is thisOn 11 Jan 2024, at 17:45, Pergola Fabio ***@***.***> wrote:﻿
ok, is the addon still running? do you see any error in the addon log?
if still running... try to stop adddon, delete the whole mqtt device (integration) , then start addon again

**Comment by pergolafabio** [comment]
Are all entities unavailable?

**Comment by fatmacheto** [comment]
Just noticed that after the tests the call state is in ringing stateOn 11 Jan 2024, at 17:45, Pergola Fabio ***@***.***> wrote:﻿
ok, is the addon still running? do you see any error in the addon log?
if still running... try to stop adddon, delete the whole mqtt device (integration) , then start addon again

**Comment by pergolafabio** [comment]
Perfect, so working then?

**Comment by pergolafabio** [comment]
I don't see screenshots :+)

**Comment by fatmacheto** [comment]
Поздрави,КрасимирOn 11 Jan 2024, at 19:15, Pergola Fabio ***@***.***> wrote:﻿
I don't see screenshots :+)

**Comment by fatmacheto** [comment]
Do you see them now?Поздрави,КрасимирOn 11 Jan 2024, at 19:15, Pergola Fabio ***@***.***> wrote:﻿
I don't see screenshots :+)

**Comment by pergolafabio** [comment]
Nope

**Comment by pergolafabio** [comment]
Best to use GitHub page and not reply by email

**Comment by pergolafabio** [comment]
yeah, i dont see the "ringing" state there either, just type in manually

from idle to ringing for example ...
just look at the state history to see correct namings

**Comment by fatmacheto** [comment]
Okay;I also tought it might be the case. Will try. How about the ringing state that is always like that? Should I reboot?Поздрави,КрасимирOn 12 Jan 2024, at 10:43, Pergola Fabio ***@***.***> wrote:﻿
yeah, i dont see the "ringing" state there either, just type in manually
from idle to ringing for example ...
just look at the state history to see correct namings

**Comment by pergolafabio** [comment]
yeah, maybe, or make again a real call , that should change it

**Comment by fatmacheto** [comment]
Okay I will try. The thing I wanted to achieve is send the image on my samsung tizen tv whenever there is a call but it doesn’t seem very reliable.Поздрави,КрасимирOn 12 Jan 2024, at 10:58, Pergola Fabio ***@***.***> wrote:﻿
yeah, maybe, or make again a real call , that should change it

**Comment by pergolafabio** [comment]
samsung tizen? how you gonna do that? with  a chromecast ?

**Comment by fatmacheto** [comment]
I can see I can send some media to it like cameras etc. but haven’t really tested it yet because I hit the rock with the ring event.Поздрави,КрасимирOn 12 Jan 2024, at 11:10, Pergola Fabio ***@***.***> wrote:﻿
samsung tizen? how you gonna do that? with  a chromecast ?

**Comment by pergolafabio** [comment]
Ah ok, I had a Tizen also before, but was difficult to send YouTube and stuff. I switched now to Google tv, Tizen was too old and slow
