### ISSUE TITLE
DS-KV6113-WPE1(C) ISAPI request

### ISSUE THREAD

**Issue by kamazzz21** [pergolafabio/Hikvision-Addons#176]
### What happened?

Hi all. Sorry for my English.

I installed this addon according to instructions, including integration with Frigate. Video from the intercom, open button, everything works.

I use an intercom without a monitor and without hik-connect.

At the same time, in mqtt devices, the ISAPI request status is: unknown.

When you press the call button on the intercom, at first there is silence and after that the intercom makes a “busy” sound, while Call state: ringing.

As I understand it, the integration connects to the intercom, receives all events and video from it, but does not replace a full-fledged service for managing it? Or do I have an error in the settings that the ISAPI request status is: unknown?

I really ask you to help with this

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

3.0.13

### Installation type

Home Assistant add-on

### Relevant log output

```Text
2024-01-04 22:09:32.516 | INFO     | event:motion_detection:98 - Motion detected from Домофон
2024-01-04 22:09:33.396 | INFO     | event:video_intercom_alarm:120 - Video intercom alarm from Домофон
2024-01-04 22:09:33.397 | INFO     | mqtt:video_intercom_alarm:331 - Doorbell ringing, updating sensor 
settings: mqtt=MQTT(host='core-mosquitto', port=1883, username='addons', password='ete0wu3quoeth7eiqu1ooyie6Je1AigeeVepheitaeTh0Ahweex4aeRei0eig4ph', client_name=None, tls_key=None, tls_certfile=None, tls_ca_cert=None, discovery_prefix='homeassistant', state_prefix='hmd') entity=SensorInfo(component='sensor', device=DeviceInfo(name='Домофон', model='DS-KV6113-WPE1(C)', manufacturer='Hikvision', sw_version='V2.2.65', hw_version='0x0', identifiers='6883457586544949514587806949406741484950485051494948508282657556504854554852', connections=None, configuration_url=None), device_class=None, enabled_by_default=None, entity_category=None, expire_after=None, force_update=None, icon='mdi:bell', name='Call state', object_id='домофон_call_state', qos=None, unique_id='6883457586544949514587806949406741484950485051494948508282657556504854554852-call_state', unit_of_measurement=None, state_class=None) debug=False manual_availability=True
topic_prefix: sensor/-------/Call-state
config_topic: homeassistant/sensor/-------/Call-state/config
state_topic: hmd/sensor/-------/Call-state/state
wrote_configuration: True
```

**Comment by pergolafabio** [comment]
No, the addon is just for events, you still need to setup a device like an indoor or hikconnect so you can make a call... This addon doesn't replace answering a call

**Comment by kamazzz21** [comment]
Thanks for the very quick response.

Alas, it’s a pity that this is so. Now I installed IVMS and indeed, the intercom started ringing, and as you said, I cannot answer the call using the HA, only through IVMS.

Or maybe you can immediately tell me which intercom can be used in standalone mode in order to completely control it through the HA?

thanks in advance

**Comment by pergolafabio** [comment]
I think in standalone mode, you need hikconnect or sip..

**Comment by pergolafabio** [comment]
I only have the ds-kd8003, doesn't work official standalone


 I dont know other models, maybe best to ask on forums
