### ISSUE TITLE
DS-K1T502DBFWX-C - Not supported

### ISSUE THREAD

**Issue by seederp2p** [pergolafabio/Hikvision-Addons#177]
### What happened?

I'm trying to add my DS-K1T502DBFWX-C without success.

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

3.0.12

### Installation type

Home Assistant add-on

### Relevant log output

```Text
2024-01-05 18:59:28.255 | DEBUG    | config:load_mqtt_config:129 - Loading MQTT configuration from supervisor
2024-01-05 18:59:28.255 | DEBUG    | config:mqtt_config_from_supervisor:36 - Requesting MQTT service configuration to supervisor
2024-01-05 18:59:28.273 | INFO     | sdk.utils:loadSDK:44 - Using OS: Linux with architecture: x86_64
loop[2] find 2 mac and 0 ip
Traceback (most recent call last):
  File "/app/main.py", line 96, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/main.py", line 47, in main
    doorbell.authenticate()
  File "/app/doorbell.py", line 71, in authenticate
    self._type = DeviceType(self._device_info.wDevType)
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 884 is not a valid DeviceType
```

**Comment by pergolafabio** [comment]
Ok , np , will add it on next release

**Comment by seederp2p** [comment]
> Ok , np , will add it on next release

When do you think it will be released?

Is there something I can do to test it while you don't officialy release the new version?

Thank you so much!

**Comment by pergolafabio** [comment]
No, I need to add that identifier first

**Comment by seederp2p** [comment]
> No, I need to add that identifier first

Got it.

If you need any info from my side I'm here to help.

When do you think you can add support to this device ID?

**Comment by pergolafabio** [comment]
This weekend probably

**Comment by seederp2p** [comment]
> This weekend probably

Wow, nice :)

Thank you!

**Comment by pergolafabio** [comment]
i just updated the beta addon, with version 52 , can you try it?
make sure to refresh/update addons, so 52 is visible

**Comment by seederp2p** [comment]
> i just updated the beta addon, with version 52 , can you try it? make sure to refresh/update addons, so 52 is visible

I'm getting this:

2024-01-06 17:14:12.749 | DEBUG    | config:load_mqtt_config:129 - Loading MQTT configuration from supervisor
2024-01-06 17:14:12.749 | DEBUG    | config:mqtt_config_from_supervisor:36 - Requesting MQTT service configuration to supervisor
2024-01-06 17:14:12.779 | INFO     | sdk.utils:loadSDK:44 - Using OS: Linux with architecture: x86_64
loop[2] find 2 mac and 0 ip
2024-01-06 17:14:13.166 | INFO     | doorbell:authenticate:79 - Connected to doorbell: Porta_Armazem
2024-01-06 17:14:13.166 | INFO     | event:__init__:87 - Setting up event handler: Console stdout
2024-01-06 17:14:13.168 | INFO     | mqtt:__init__:95 - Setting up event handler: MQTT
2024-01-06 17:14:13.343 | ERROR    | __main__:<module>:101 - Error while listening to events in Porta_Armazem: Device does not support this function. Error code:23

**Comment by seederp2p** [comment]
Debug enabled:

[2024-01-06 17:32:50.696][INF] Private connect 172.16.127.211:8000 sock=139 this=0x861775f4 cmd=0x117000 port=51662
[2024-01-06 17:32:50.698][DBG] SimpleSTDCommandToDvr with out cmd[GET /ISAPI/System/deviceInfo], input size[0], max segment length[262144]
2024-01-06 17:32:50.758 | DEBUG    | event:start:255 - Registering callback function using SDK
2024-01-06 17:32:50.763 | DEBUG    | doorbell:setup_alarm:90 - Arming the device via SDK
[2024-01-06 17:32:50.766][INF] Private connect 172.16.127.211:8000 sock=163 this=0x861775f4 cmd=0x111021 port=51674
2024-01-06 17:32:50.768 | ERROR    | __main__:<module>:101 - Error while listening to events in Porta_Armazem: Device does not support this function. Error code:23
[2024-01-06 17:32:50.768][ERR] Index[0] cmd[111021] SendCommandWithRecv failed[23] 
[2024-01-06 17:32:50.768][ERR] CMemberMgrBase::AllocIndex2, MemberStart Failed, iIndex[0]

**Comment by pergolafabio** [comment]
Hmm that's not good, I don't think your device supports the SDK... Are you using an NVR?

**Comment by seederp2p** [comment]
> Owner

Hi!

No. I just use this as a standalone doorbell with videocom ;)

**Comment by pergolafabio** [comment]
Hmm, not sure if I can do anything about it, seems your device doesnt support SDK for listening on events :-(

Maybe you can use some Isapi commands instead?

Is it a new device?

**Comment by seederp2p** [comment]
> Hmm, not sure if I can do anything about it, seems your device doesnt support SDK for listening on events :-(
> 
> Maybe you can use some Isapi commands instead?
> 
> Is it a new device?

Yes. This was released 1 year ago and it's supposed to be a high end terminal.

Is there anything I can do on my side so you can make sure that it doesn't support SDK?

**Comment by pergolafabio** [comment]
Hm on hikvision site, you can download the SDK files, there are also some client test tools inside, can you try them? Especially the one for events

**Comment by seederp2p** [comment]
> Hm on hikvision site, you can download the SDK files, there are also some client test tools inside, can you try them? Especially the one for events

Can you please give me some basic guidance about the steps I have to follow?

Thank you

**Comment by pergolafabio** [comment]
Hi, here are the SDK test tools, you can download it for windows and linux

https://www.hikvision.com/europe/support/tools/hitools/?type=IP

extract the zip, and there are some tools / client demo included

**Comment by seederp2p** [comment]
> Hi, here are the SDK test tools, you can download it for windows and linux
> 
> https://www.hikvision.com/europe/support/tools/hitools/?type=IP
> 
> extract the zip, and there are some tools / client demo included

Ok so I tried to run the C# demo\5-GettingDeviceCapabilities\CapabilityCSharpDemo\bin\ClientDemoEn.exe and it gathers some data. I don't find any specific binary for events...

**Comment by seederp2p** [comment]
> I believe its this one, but never tried myself
> 
> C# demo\4-Alarm(Arm&Listen)\4-Alarm(Arm&Listen)\AlarmCSharpDemo
> 
> but if you add your device, can you see the video stream for example?

I confirm that I can see the video stream.

I found the path you were refering to:

![image](https://github.com/pergolafabio/Hikvision-Addons/assets/3126847/5926193f-c8c8-4f29-bf63-5678db70b5ab)


![image](https://github.com/pergolafabio/Hikvision-Addons/assets/3126847/34600e17-40cc-42f3-b6f3-292410440ce6)

![image](https://github.com/pergolafabio/Hikvision-Addons/assets/3126847/91e4c855-65dd-4f16-b501-9bb0dda0d148)

![image](https://github.com/pergolafabio/Hikvision-Addons/assets/3126847/152cf9e1-cbc4-4b81-afca-fcca0c11d162)

**Comment by pergolafabio** [comment]
what you can do, download the dev branch:

https://github.com/pergolafabio/Hikvision-Addons/tree/dev

copy paste the hikvision-doorbell folder in your "addons" share on your HA
download the SDK zip package, but the linux64 edition,  extract it there should be a "lib" folder
Remove all content from the lib-amd64 folder, and replace it with the new lib, make sure folder structure is the same
Then  goto HA, do a  refresh for your addons, then a local addon should popup in your store , then install it...
Then you have the addon, with the new SDK version, not sure if it works, but worth a try

**Comment by pergolafabio** [comment]
you have also ivms right? Do you see this? the arming/disarming function? this is used for getting events:

![image](https://github.com/pergolafabio/Hikvision-Addons/assets/43251136/3b51eef4-0f03-49ff-8d42-1fca2e038b39)

**Comment by pergolafabio** [comment]
But i think you are out of luck, i see you also have error 23 in the client demo tool for the alarm functions

**Comment by seederp2p** [comment]
> But i think you are out of luck, i see you also have error 23 in the client demo tool for the alarm functions

I get it. I can try to contact hikvision to get this in future firmware versions. Can you help me formulating a proper request? :)

**Comment by pergolafabio** [comment]
hmm, i already know the answer, it will get cancelled anwyay, i was told that they are going to stop using SDK, they want all devices with more ISAPI support instead...

**Comment by seederp2p** [comment]
> hmm, i already know the answer, it will get cancelled anwyay, i was told that they are going to stop using SDK, they want all devices with more ISAPI support instead...

Ok. :(

Do you know if is it possible via IS API to get a status o someone fingerprint authentication? Even if I have to pool this very often. My goal was to take an action whenever someone correctly authenticates on the doorbell... In this case via fingerprint...

**Comment by pergolafabio** [comment]
Hmm, never looked for those, but i shared all isapi docs on community thread, you can have a look at the person based access control document maybe

https://www.dropbox.com/s/obppstvpvxja9l7/isapi.zip?dl=0

also try this command in putty, maybe your devices supports the alertstream?

`curl -i --digest -u admin:XXXXXXXhttp://192.168.0.70/ISAPI/Event/notification/alertStream`

**Comment by pergolafabio** [comment]
Yeah, that should be possible, that are command line or rest sensors for that, and with automation you should be able to check the dates.....

Good find! Did you saw those commands in the Isapi zip ?

**Comment by pergolafabio** [comment]
Doesnt the alarm stream command work for you? That should give some live data... On mine device it doesn't work, but it works mostly for hikvision cameras for motions etc...

**Comment by seederp2p** [comment]
> Yeah, that should be possible, that are command line or rest sensors for that, and with automation you should be able to check the dates.....
> 
> Good find! Did you saw those commands in the Isapi zip ?

I found it searching the wiki: https://tpp.hikvision.com/Wiki/ISAPI

**Comment by pergolafabio** [comment]
Ahh you have an account there?

**Comment by seederp2p** [comment]
> Ahh you have an account there?

Nop. I think it's public...

**Comment by seederp2p** [comment]
> > Hmm, never looked for those, but i shared all isapi docs on community thread, you can have a look at the person based access control document maybe
> > https://www.dropbox.com/s/obppstvpvxja9l7/isapi.zip?dl=0
> > also try this command in putty, maybe your devices supports the alertstream?
> > `curl -i --digest -u admin:XXXXXXX http://192.168.0.70/ISAPI/Event/notification/alertStream`
> 
> I found that I can get the latest fingerprint and door close (that happens 5 seconds after each success finger print via):
> 
> `curl --location --globoff --digest -u 'admin:mypass' 'http://x.x.x.x/ISAPI/AccessControl/AcsEvent?format=json' --data '{ "AcsEventCond": { "searchID": "1", "searchResultPosition": 0, "maxResults": 1, "timeReverseOrder": true, "major": 5, "minor": 38 } }'`
> 
> and:
> 
> `curl --location --globoff --digest -u 'admin:mypass!!' 'http://x.x.x.x/ISAPI/AccessControl/AcsEvent?format=json' \ --data '{ "AcsEventCond": { "searchID": "1", "searchResultPosition": 0, "maxResults": 1, "timeReverseOrder": true, "major": 5, "minor": 22 } }'`
> 
> The output for fingerprint success is something like:
> 
> `{ "AcsEvent": { "searchID": "1", "responseStatusStrg": "MORE", "numOfMatches": 1, "totalMatches": 114, "InfoList": [{ "major": 5, "minor": 38, "time": "2024-01-09T16:51:51-00:00", "netUser": "", "cardType": 1, "name": "whatever", "cardReaderNo": 1, "doorNo": 1, "employeeNoString": "20", "type": 0, "serialNo": 1455, "userType": "normal", "currentVerifyMode": "fp" }] }`
> 
> and for door close:
> 
> `{ "AcsEvent": { "searchID": "1", "responseStatusStrg": "MORE", "numOfMatches": 1, "totalMatches": 284, "InfoList": [{ "major": 5, "minor": 22, "time": "2024-01-09T16:51:56-00:00", "netUser": "", "doorNo": 1, "type": 0, "serialNo": 1457, "currentVerifyMode": "faceOrFpOrCardOrPw" }] } }`
> 
> My idea was to create 2 sensors in HA that could store the "time" value of each event (Success FingerPrint and Door Close).
> 
> After that I would create another sensor like "Auth Status" that would store the LATEST event based on the other 2 sensors. That way I could fire actions based on this last sensor change of status.
> 
> But I'm not sure if this is possible...

about "alertstream" I got this after the curl:

`{
  "AcsEvent": {
    "searchID": "1",
    "responseStatusStrg": "MORE",
    "numOfMatches": 1,
    "totalMatches": 111,
    "InfoList": [
      {
        "major": 5,
        "minor": 38,
        "time": "2024-01-09T14:13:32-00:00",
        "netUser": "",
        "cardType": 1,
        "name": "Person Name",
        "cardReaderNo": 1,
        "doorNo": 1,
        "employeeNoString": "20",
        "type": 0,
        "serialNo": 1443,
        "userType": "normal",
        "currentVerifyMode": "fp"
      }
    ]
  }
}
`

**Comment by pergolafabio** [comment]
I think the Alertstream is a continuous command, the curl command is still active and providing data right?

**Comment by seederp2p** [comment]
> I think the Alertstream is a continuous command, the curl command is still active and providing data right?

No it's not... it doesn't remain active :(

**Comment by seederp2p** [comment]
about my first idea I tried this sensor:

`- platform: rest
  name: whatever
  resource: http://x.x.x.x/ISAPI/AccessControl/AcsEvent?format=json
  method: POST
  payload: '{"AcsEventCond": {"searchID": "1", "searchResultPosition": 0, "maxResults": 1, "timeReverseOrder": true, "major": 5, "minor": 38}}'
  username: admin
  password: mypass
  authentication: digest
  value_template: "{{ value_json.AcsEvent.InfoList[0].time if value_json.AcsEvent is defined else None }}"
  scan_interval: 1
  json_attributes:
    - AcsEvent`

and got this: 

![image](https://github.com/pergolafabio/Hikvision-Addons/assets/3126847/2598796d-8c86-43b4-9e5a-b98e412108cc)

But after some time I've "none"... maybe HA gets blacklisted due to requests all the seconds... I dont know

**Comment by pergolafabio** [comment]
yeah, i think the payload of 1 sec is way to fast, maybe make it more like 4-5 sec

**Comment by pergolafabio** [comment]
scan interval i mean

**Comment by seederp2p** [comment]
> scan interval i mean

change to 5 and after some time I get "none"

**Comment by pergolafabio** [comment]
and if you do the curl?

**Comment by seederp2p** [comment]
> and if you do the curl?

I can spam the curl command and I always get the output...

**Comment by pergolafabio** [comment]
hmm, strange
try the command line sensor instear of the rest sensor?
then you can use the curl too

**Comment by pergolafabio** [comment]
Yeah, I know that there were issues in the ha core with the digest authentication, there are issues created for it..

**Comment by seederp2p** [comment]
> or no response at all, strange that the curl always works?

I'm side testing on a ubuntu server machine via command line and it always work...

**Comment by seederp2p** [comment]
Well I just went all the way arround.

Since I've an internal webserver always on, I created a PHP script to generate a json output after comparing both FP auth and Door close Dates.

`<?php
// Função para obter os eventos com base nos parâmetros fornecidos usando cURL com autenticação Digest
function getEvent($minor) {
    $url = 'http://yo.ur.i.p/ISAPI/AccessControl/AcsEvent?format=json';
    $data = array(
        "AcsEventCond" => array(
            "searchID" => "1",
            "searchResultPosition" => 0,
            "maxResults" => 1,
            "timeReverseOrder" => true,
            "major" => 5,
            "minor" => $minor
        )
    );

    $ch = curl_init($url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_DIGEST);
    curl_setopt($ch, CURLOPT_USERPWD, 'admin:YOURPASSWORD');
    curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json'));
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));

    $response = curl_exec($ch);
    if ($response === false) {
        echo json_encode(array("error" => 'Erro ao fazer a requisição: ' . curl_error($ch)));
        return null;
    }

    curl_close($ch);
    return json_decode($response, true);
}

// Obter eventos para minor 38 (Autenticação Digital) e minor 22 (Fecho de Porta)
$event_38 = getEvent(38);
$event_22 = getEvent(22);

if (!$event_38 || !$event_22) {
    echo json_encode(array("error" => "Não foi possível obter os eventos."));
    exit();
}

// Extrair os tempos dos eventos
$time_38 = $event_38['AcsEvent']['InfoList'][0]['time'];
$time_22 = $event_22['AcsEvent']['InfoList'][0]['time'];

// Comparar os tempos para determinar o evento mais recente
if ($time_38 > $time_22) {
    echo json_encode(array("ultimo_evento" => "Autenticacao Digital"));
} elseif ($time_38 < $time_22) {
    echo json_encode(array("ultimo_evento" => "Fecho de Porta"));
} else {
    echo json_encode(array("ultimo_evento" => "Outro"));
}
?>
`

after that I created a sensor in HA that pools every second:

- platform: rest
  name: Estado_Porta
  resource: http://your.web.server.ip/HA/whatever.php
  value_template: '{{ value_json.ultimo_evento }}'
  scan_interval: 1 

And now I've a working sensor that has the last event between Fingerprint Auth and Door close :)

**Comment by pergolafabio** [comment]
gonna close for now, too bad you couldnt use the addon , would be much better

**Comment by seederp2p** [comment]
> nice :-) i hope the script doesnt hammer your device with that 1 sec, i hope it keeps stable

Yep. I'll monitor that :)

**Comment by seederp2p** [comment]
Hi!

For your information, there's a different approach possible! :)

You can go to Configuration -> Network Service -> HTTP -> HTTP Listening and configure an endpoint to receive the event payloads such as:

```
{
    "ipAddress": "whatever",
    "portNo": 80,
    "protocol": "HTTP",
    "dateTime": "2024-08-26T12:32:28+01:00",
    "activePostCount": 1,
    "eventType": "AccessControllerEvent",
    "eventState": "active",
    "eventDescription": "Access Controller Event",
    "AccessControllerEvent": {
        "deviceName": "DS-K1T502DBFWX-C",
        "majorEventType": 5,
        "subEventType": 21,
        "reportChannel": 5,
        "cardReaderKind": 1,
        "doorNo": 1,
        "serialNo": 257,
        "currentEvent": true,
        "frontSerialNo": 256,
        "hasRecord": false
    }
}
```

However I found out that this is not going to support calls to HTTPS service as it looks like the device won't support nothing higher than TLS 1.0. However you can create a "proxy service" inside your network with simple HTTP port 80 that can forward that to your HA Webhook. Example:

```
<?php
// Define the path to the file where the payload will be saved for debugging
$file = 'payload.txt';

// URL of the Home Assistant webhook (hidden for security)
$webhook_url = 'YOUR_WEBHOOK_URL_HERE';

// Check if the request method is POST
if ($_SERVER['REQUEST_METHOD'] === 'POST') {

    // Capture the payload from the event_log field
    $event_log = isset($_POST['event_log']) ? $_POST['event_log'] : null;

    // If the event_log field exists, process it
    if ($event_log) {

        // Convert the event_log to an array if it's in JSON format
        if (is_string($event_log)) {
            $event_log = json_decode($event_log, true);
        }

        // Initialize a variable for the event name
        $event_name = "Irrelevant Event";

        // Check if the major and minor fields exist and process the event
        if (isset($event_log['AccessControllerEvent']['majorEventType']) && $event_log['AccessControllerEvent']['majorEventType'] === 5) {
            $minor = $event_log['AccessControllerEvent']['subEventType'];
            if ($minor === 22) {
                $event_name = "Door Closed";
            } elseif ($minor === 38) {
                $event_name = "Digital Authentication";
            }
        }

        // Rebuild the payload with the event name
        $new_payload = array("last_event" => $event_name);

        // Optional: Save the received payload and the (relevant) payload to be sent locally for debugging
        $debug_info = "Received Payload:\n" . json_encode($event_log, JSON_PRETTY_PRINT) . "\n\n";

        // Check if the event is relevant before sending it to Home Assistant
        if ($event_name !== "Irrelevant Event") {
            // Add the payload sent to the log
            $debug_info .= "Payload Sent:\n" . json_encode($new_payload, JSON_PRETTY_PRINT) . "\n\n";

            // Send the new payload to the Home Assistant webhook using cURL
            $ch = curl_init($webhook_url);
            curl_setopt($ch, CURLOPT_POST, 1);
            curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($new_payload));
            curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

            // Execute the request and capture the response
            $response = curl_exec($ch);
            $http_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);

            curl_close($ch);

            // Check if the request was successful
            if ($http_code == 200) {
                echo "Payload successfully sent to Home Assistant.";
            } else {
                echo "Failed to send payload to Home Assistant. HTTP Code: $http_code";
            }
        } else {
            // If the event is not relevant, only log the information
            $debug_info .= "No payload sent (Irrelevant Event).\n\n";
            echo "Irrelevant event. No payload sent.";
        }

        // Write all debugging information to the file
        file_put_contents($file, $debug_info . str_repeat("-", 20) . "\n", FILE_APPEND);

    } else {
        echo "event_log field not found in the request.";
    }
} else {
    echo "Unsupported request method.";
}
?>

```

In this little script I'm just using the events for finger print and door closing.

then create something like this in your HA:

```
template:
  - trigger:
      - platform: webhook
        webhook_id: hikvision
        local_only: true
    sensor:
      - name: "your-door"
        state: "{{ trigger.json.last_event }}"

```

**Comment by pergolafabio** [comment]
ah, thats cool indeed,

=>  Configuration -> Network Service -> HTTP -> HTTP Listening

is that something you can configure on the Hikvison device? seems i dont have that on my DS-KD8003 ...
Where can you find it? can you make a screenshot?

This is maybe an idea to implement in the addon, to support thos devices

**Comment by seederp2p** [comment]
> ah, thats cool indeed,
> 
> => Configuration -> Network Service -> HTTP -> HTTP Listening
> 
> is that something you can configure on the Hikvison device? seems i dont have that on my DS-KD8003 ... Where can you find it? can you make a screenshot?
> 
> This is maybe an idea to implement in the addon, to support thos devices

Yep!

Take a look:

![image](https://github.com/user-attachments/assets/9714ca84-cf11-40c8-ac6d-f56a77729006)

However, as I said, it looks like it doesn't support nothing higher than TLS 1.0, so we should send this to a "proxy" listener in HTTP that maybe can then forward to the HA webhook (or to a listener in your integration).

Also, If you want to open the door on this device you can do that by:
`
curl -i --digest -u 'admin:whatever' -X PUT -d '<RemoteControlDoor><cmd>open</cmd></RemoteControlDoor>' http://you.r.i.p/ISAPI/AccessControl/RemoteControl/door/1`

**Comment by pergolafabio** [comment]
yeah, that door open command is indeed also part of the addon
i dont have that http listener setting :-( , not easy to develop if i cant test :-(

**Comment by seederp2p** [comment]
> yeah, that door open command is indeed also part of the addon i dont have that http listener setting :-( , not easy to develop if i cant test :-(

Basically the Device start sending payloads whenever ANY event occurs.

Something like:

```
{
    "ipAddress": "whatever",
    "portNo": 80,
    "protocol": "HTTP",
    "dateTime": "2024-08-26T12:32:28+01:00",
    "activePostCount": 1,
    "eventType": "AccessControllerEvent",
    "eventState": "active",
    "eventDescription": "Access Controller Event",
    "AccessControllerEvent": {
        "deviceName": "DS-K1T502DBFWX-C",
        "majorEventType": 5,
        "subEventType": 21,
        "reportChannel": 5,
        "cardReaderKind": 1,
        "doorNo": 1,
        "serialNo": 257,
        "currentEvent": true,
        "frontSerialNo": 256,
        "hasRecord": false
    }
}
```

The code numbers are the same as in the ISAPI documentation...

So for instance, a Fingerprint read is major event 5 and minor (or subevent) 38.

Door locked is major 5 and minor (or subevent) 22

**Comment by pergolafabio** [comment]
should be easy, i have the issue open again , gonna make a feature reques from it ...
maybe in future when i have some time :-)

**Comment by seederp2p** [comment]
> should be easy, i have the issue open again , gonna make a feature reques from it ... maybe in future when i have some time :-)

sure!

Please let me know if you need any data from the device or a beta tester ;)

**Comment by seederp2p** [comment]
FYI, when you restart the hikvision device it won't start using the HTTP Listener automatically (!!!!).

In fact after you reboot, when you access your /ISAPI/Event/notification/httpHosts/1 you'll see:


```
<HttpHostNotification xmlns="http://www.isapi.org/ver20/XMLSchema" version="2.0">
<id>1</id>
<url>/HA/proxy.php</url>
<protocolType>HTTP</protocolType>
<parameterFormatType/>
<addressingFormatType>ipaddress</addressingFormatType>
<ipAddress>whatever</ipAddress>
<portNo>80</portNo>
<httpAuthenticationMethod/>
<SubscribeEvent>
<heartbeat>30</heartbeat>
<eventMode>all</eventMode>
</SubscribeEvent>
</HttpHostNotification>
```

Unlease you save again your configuration OR you send the proper payload to the ISAPI it won't send any alerts!

After you save again you'll see this:


```
<HttpHostNotification xmlns="http://www.isapi.org/ver20/XMLSchema" version="2.0">
<id>1</id>
<url>/HA/proxy.php</url>
<protocolType>HTTP</protocolType>
<parameterFormatType/>
<addressingFormatType>ipaddress</addressingFormatType>
<ipAddress>whatever</ipAddress>
<portNo>80</portNo>
<httpAuthenticationMethod/>
<SubscribeEvent>
<heartbeat>30</heartbeat>
<eventMode>all</eventMode>
<EventList>
<Event>
<type>AccessControllerEvent</type>
<minorAlarm/>
<minorException/>
<minorOperation/>
<minorEvent/>
<pictureURLType>binary</pictureURLType>
</Event>
</EventList>
</SubscribeEvent>
</HttpHostNotification>
```

Notice the <EventList> that is now present!

You can also achieve the same result by running something like:

```
curl -i --digest -u 'admin:whatever' -X PUT -d '<HttpHostNotification xmlns="http://www.isapi.org/ver20/XMLSchema" version="2.0">
<id>1</id>
<url>/HA/proxy.php</url>
<protocolType>HTTP</protocolType>
<parameterFormatType/>
<addressingFormatType>ipaddress</addressingFormatType>
<ipAddress>whatever</ipAddress>
<portNo>80</portNo>
<httpAuthenticationMethod/>
<SubscribeEvent>
<heartbeat>30</heartbeat>
<eventMode>all</eventMode>
<EventList>
<Event>
<type>AccessControllerEvent</type>
<minorAlarm/>
<minorException/>
<minorOperation/>
<minorEvent/>
<pictureURLType>binary</pictureURLType>
</Event>
</EventList>
</SubscribeEvent>
</HttpHostNotification>' \
http://whatever/ISAPI/Event/notification/httpHosts/1
```

Please remind that it will spit all the missed events, so you should be careful. Maybe handlind event dates so you won't trigger any action based on a past event...

**Comment by pergolafabio** [comment]
hmm, maybe thats a firmware bug ?

**Comment by seederp2p** [comment]
> hmm, maybe thats a firmware bug ?

Very likely... :) but we can't rely on hikvision to fix this ... ahaha

I don't even have a proper contact to escalate this... so we can overcome by creating a mechanism that PUT de needed XML payload so the listener is active again (for instance after a reboot).

Then you just need to handle the dates between the payloads that hikvision send vs the current time of the system.

My example:

```
<?php
// Define the path to the file where the payload will be saved for debugging
$file = 'payload.txt';

// Home Assistant webhook URL
$webhook_url = 'YOUR_HIDDEN_URL_HERE';

// Check if the request method is POST
if ($_SERVER['REQUEST_METHOD'] === 'POST') {

    // Capture the payload from the event_log field
    $event_log = isset($_POST['event_log']) ? $_POST['event_log'] : null;

    // If the event_log field exists, process it
    if ($event_log) {

        // Convert event_log to an array if it's in JSON format
        if (is_string($event_log)) {
            $event_log = json_decode($event_log, true);
        }

        // Check if the dateTime field exists in the payload
        if (isset($event_log['dateTime'])) {

            // Convert the payload dateTime and the current system time to timestamps
            $payload_time = strtotime($event_log['dateTime']);
            $current_time = time();

            // Calculate the difference in seconds between the payload time and the current time
            $time_difference = abs($current_time - $payload_time);

            // If the difference is greater than 10 seconds, consider the event as irrelevant
            if ($time_difference > 10) {
                // Capture the current system date and time
                $system_time = date('Y-m-d H:i:s');

                // Message indicating that the event is outside the time tolerance, including the system date and time
                $message = "Payload is outside the time tolerance (system date: $system_time).";
                
                echo $message;

                // Log the debug information in the file
                $debug_info = "$message\nPayload Received:\n" . json_encode($event_log, JSON_PRETTY_PRINT) . "\n\n";
                file_put_contents($file, $debug_info . str_repeat("-", 20) . "\n", FILE_APPEND);
                exit;
            }
        } else {
            echo "dateTime field not found in the payload.";
            exit;
        }

        // Initialize the variable for the event name
        $event_name = "Irrelevant Event";

        // Check if the major and minor fields exist and process the event
        if ($event_log['AccessControllerEvent']['majorEventType'] === 5) {
            $minor = $event_log['AccessControllerEvent']['subEventType'];
            if ($minor === 22) {
                $event_name = "Door Closure";
            } elseif ($minor === 38) {
                $event_name = "Digital Authentication";
            }
        }

        // Reconstruct the payload with the event name
        $new_payload = array("last_event" => $event_name);

        // Optionally: Save the received payload and the (if relevant) payload to be sent locally for debugging
        $debug_info = "Payload Received:\n" . json_encode($event_log, JSON_PRETTY_PRINT) . "\n\n";

        // Check if the event is relevant before sending it to Home Assistant
        if ($event_name !== "Irrelevant Event") {
            // Add the sent payload to the log
            $debug_info .= "Payload Sent:\n" . json_encode($new_payload, JSON_PRETTY_PRINT) . "\n\n";

            // Send the new payload to the Home Assistant webhook using cURL
            $ch = curl_init($webhook_url);
            curl_setopt($ch, CURLOPT_POST, 1);
            curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($new_payload));
            curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

            // Execute the request and capture the response
            $response = curl_exec($ch);
            $http_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);

            curl_close($ch);

            // Check if the request was successful
            if ($http_code == 200) {
                echo "Payload successfully sent to Home Assistant.";
            } else {
                echo "Failed to send payload to Home Assistant. HTTP Code: $http_code";
            }
        } else {
            // If the event is not relevant, just log the information
            $debug_info .= "No payload sent (Irrelevant Event).\n\n";
            echo "Irrelevant event. No payload sent.";
        }

        // Log all the debug information in the file
        file_put_contents($file, $debug_info . str_repeat("-", 20) . "\n", FILE_APPEND);

    } else {
        echo "event_log field not found in the request.";
    }
} else {
    echo "Request method not supported.";
}
?>

```

**Comment by Alexandreao** [comment]
Would you consider using node-red with  hikvision-ultimate ? (youtube : https://www.youtube.com/watch?v=d9MOMtDw7Zs&t=273s)
This guy uses node-red with ISAPI to listen the hikvision events and then integrate on homeassistant

**Comment by pergolafabio** [comment]
I am indeed familiar with that project, but not interested in Isapi, it doesnt provide events for intercoms, it's way too limiter... The Isapi eventstream only works on cameras

**Comment by pergolafabio** [comment]
Btw, is there an Isapi command for polling the events for K1T devices? I can add a polling sensor....

For other intercom models it doesn't work...

**Comment by Alexandreao** [comment]
I'm kinda new to Hikvision protocols.
For now, I pretend to integrate a Hikvision access control (K1T805) with HomeAssistant and I found that implementation in Node-Red.
For my understanding, Hikvision is trying to migrate everything with ISAPI events including NVR, cameras, doorbells, access panels
This Node-red implementation is compatible with multi devices (specially the new ones), and I thought that could help you with the integration.

**Comment by pergolafabio** [comment]
Yeah, I know , but it doesn't work well for intercoms, it's just too limited...
