### ISSUE TITLE
Error 28 Not enough resources 

### ISSUE THREAD

**Issue by InsularOne** [pergolafabio/Hikvision-Addons#178]
### What happened?

Had been working fine for a while, updated HA recently and shortly after started getting error code 28. Restarted the Doorbell (KB8112), restarted HA, uninstalled and reinstalled the add on, still getting the same issue.

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

3.0.13

### Installation type

Home Assistant add-on

### Relevant log output

```Text
2024-01-06 20:50:10.122 | ERROR    | __main__:<module>:101 - Error while listening to events in Road Gate: Not enough resource on the device. Error code:28
```

**Comment by pergolafabio** [comment]
Hi, have you tried rebooting the device? Or maybe a firmware upgrade?

**Comment by InsularOne** [comment]
Thanks for the response. I am on the latest firmware and have tried rebooting it a few times without any success unfortunately. Have also tried downgrading HA to the version it was last working on and this doesn't work either.

**Comment by pergolafabio** [comment]
Hmm, there is no relation ship between HA and this addon, it's a complete separate instance...

Error 28 really comes from your device, not HA, must be some issue on your device side...

**Comment by InsularOne** [comment]
Ah, good to know. I will try a full reset of the device back to factory settings and see how it goes. Thanks for the quick replies.

**Comment by pergolafabio** [comment]
No problem

**Comment by InsularOne** [comment]
Just to follow up on this in case anyone else is having the same issue, the factory reset of the device worked. Thanks again for the help.

**Comment by pergolafabio** [comment]
Perfect:-)
