### ISSUE TITLE
Add device DS-KH6320-WTE1

### ISSUE THREAD

**Issue by DastyDiesel** [pergolafabio/Hikvision-Addons#182]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

Is there any possibility to add device DS-KH6320-WTE1 to AddOn? I need to use it in HA mainly for Relay 1 and 2.
Thank you.

**Comment by pergolafabio** [comment]
Yeah, that device should work, just try it out

**Comment by DastyDiesel** [comment]
> Yeah, that device should work, just try it out

Unfortunately I don't see the Relay 1 and Relay 2 entities
![image](https://github.com/pergolafabio/Hikvision-Addons/assets/72550500/7975567f-f7a3-497b-94a3-ac27a54fb0d6)

**Comment by pergolafabio** [comment]
Can you show me the add-on log?

**Comment by pepsonEL** [comment]
I have this LCD and works with relay 1 and 2 but i have newer FW in my 2.2.20
![image](https://github.com/pergolafabio/Hikvision-Addons/assets/71824185/6e5c3dbb-7264-4adc-8102-bcc49560ced1)

**Comment by DastyDiesel** [comment]
> HikVision Doorbell

you are right, I!m using Hik-Connect added by HACS. But I tried to use HikVision Doorbell. Can you, please, provide me the setting screen of HikVision Doorbell addon? It looks that something is wrong in my setting.

**Comment by pergolafabio** [comment]
Hi, its better to configure your outdoor station, or do you not have access to it?
If no access try to add this to the config:

`  output_relays: 2`

remember, indoor station dont provide the RING event! You need to poll it, in latest addon version 3.0.14, i added an "call status" button, you can make an automation to trigger it every x seconds for example

**Comment by pepsonEL** [comment]
- name: DS-KD8003-IME1(B)
  ip: 192.168.xxx.xxx
  username: admin
  password: xxxxxxxxxxxxxxxx
- name: DS-KH6320-WTE
  ip: 192.168.xxx.xxx
  username: admin
  password: xxxxxxxxxxxxxxxxxxxxx

**Comment by pergolafabio** [comment]
there is indeed a firmware difference, 2.1.32 vs 2.2.20
best to align it, or maybe newer if out?

**Comment by pergolafabio** [comment]
also make sure to refresh the MQTT page where you see the sensors, sometimes its still creating the entities and you need to refresh

**Comment by pepsonEL** [comment]
> there is indeed a firmware difference, 2.1.32 vs 2.2.20 best to align it, or maybe newer if out?

I dont find newer,

**Comment by DastyDiesel** [comment]
So I updated my indoor station to 2.2.20... I set correctly add on HikVision Doorbell. Now I see via MQTT both devices.also with relays.... but.... 
My scenario: When someone is ringing, I want to push button in Home assistant and open gate (it is easy). But when I click on relay button 1 or 2 on indoor device, the event is nto visible in Home Assistant... and it is my issue. Is it possible to do it somehow?

**Comment by pergolafabio** [comment]
Hi, not following here, so you have added bot the devices to HA? your indoor AND outdoor? Ca you show me the config?
Your OUTDOOR device gives you the ring event, opening the door , its best to use the OUTDOOR device, 

Pressing this switch below should open the door..., (Also use the OUTDOOR device) if not show me the addon log when you press it, i dont know if the INDOOR device relay buttons do work, i think its only for newer models...

@pepsonEL , does it work for your indoor device? does the door open then?

![image](https://github.com/pergolafabio/Hikvision-Addons/assets/43251136/2677785b-d4d3-474c-8c19-80f5e23a6f6d)
