### ISSUE TITLE
Add translation

### ISSUE THREAD

**Issue by psike01** [pergolafabio/Hikvision-Addons#185]
### Is there an existing feature request for this?

- [x] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

It would be nice to add the ability to use translations for the phrases "idle", "calling" and others. On my own, I can then add a translation to "RU"

**Comment by pergolafabio** [comment]
Hmm, don't know if that's possible, the output is coming from the device itself.. if you send an ISAPI command for example, do you see output in RU language?

**Comment by psike01** [comment]
No, i didn't recive output in Ru language.
My suggestion is to make an additional function for data conversion in device responses. By default, "EN" is set. And additionally, by adding locale languages, translate these entities into other languages.
For example, how is it done here: https://github.com/AlexxIT/XiaomiGateway3/blob/master/custom_components/xiaomi_gateway3/translations/en.json

**Comment by pergolafabio** [comment]
Hi, thats a lot of work, there are a lot of events hardcoded in the addon, if i start with 1 language, tehn ...
Also dont have time for this atm, but feel free to submit a PR !

Gonna close for now, maybe in a  future time, we need to rebase the code anyway first
