### ISSUE TITLE
Add "attribute" to "illegal_card_swiping_event" topic

### ISSUE THREAD

**Issue by rabdalov** [pergolafabio/Hikvision-Addons#187]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

There is an event "### illegal_card_swiping_event" which is sends state topic:
### hmd/device_automation/Main_Door_Intercom/illegal_card_swiping_event
Please can you add attributes containing the number of used illegal card

**Comment by pergolafabio** [comment]
Do you have people trying to access your house?

**Comment by pergolafabio** [comment]
Hey , i created an beta addon , can you install version 59 ? I added the same control_source that you see when opening a door with key/number, now also on the illegal card swipe event

https://github.com/pergolafabio/Hikvision-Addons/commit/05fd078543ae7f0a4d2967710a3185f9a92f3efe

**Comment by rabdalov** [comment]
Nope ))
I'd like to use non registered cards in HA automation beside opening door.
Thanks a lot !

**Comment by pergolafabio** [comment]
Ok, try the beta add-on, I have added it there as attribute

**Comment by rabdalov** [comment]
Thanks a lot!
It works!

**Comment by pergolafabio** [comment]
perfect, i will add it to next final release later
