### ISSUE TITLE
Doorbell opening records

### ISSUE THREAD

**Issue by ulysses-sheng** [pergolafabio/Hikvision-Addons#188]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

Is it possible to obtain the doorbell opening records? such as fingerprints, IC cards, face recognition.thanks!

**Comment by pergolafabio** [comment]
Hi,, if you at the switch , there is an attribute called "control_source", that will give you the record who openened it

**Comment by ulysses-sheng** [comment]
> Hi,, if you at the switch , there is an attribute called "control_source", that will give you the record who openened it

I'm sorry,can you show me how to configure "control_source" .I tried configuration.yaml several times without success.Thank you!

**Comment by pergolafabio** [comment]
there is nothing to configure, its a  attribute of the switch entity, there you see the record, see example:

![image](https://github.com/pergolafabio/Hikvision-Addons/assets/43251136/e6f077d3-ffd3-4435-9094-e80ef41f542c)

**Comment by ulysses-sheng** [comment]
en,thanks,but my door bell can not see the record,is that need to configure the Access Controller?
![微信截图_20240514164529](https://github.com/pergolafabio/Hikvision-Addons/assets/162559068/e90fe73e-5c06-438c-8193-a68d0e2aaa7e)

**Comment by ulysses-sheng** [comment]
hmm.I can see door record on Home assistant Add-ons,How can I tranfer it to Home assistant sensor

![Image](https://github.com/user-attachments/assets/9fdd8fde-f5cd-40bf-b2a0-738611868a94)

**Comment by pergolafabio** [comment]
They are device triggers, you can build automations on those triggers , or make a template sensor if you really need a sensor
