### ISSUE TITLE
error 7

### ISSUE THREAD

**Issue by kuradi** [pergolafabio/Hikvision-Addons#19]
hello,

addon worked good but after latest ha update i have this error:

07/14/2022, 19:42:10 Hikvision SDK Add-on started! Listening for events...
loop[2] find 10 mac and 16 ip
NET_DVR_Login_V30 failed, error code = 7 

ho to fix it?

**Comment by pergolafabio** [comment]
Maybe a login error? Normally nothing changed on addon, runs for me...
Maybe IP changed? Maybe try rebooting the doorstation?
