### ISSUE TITLE
Add support for DS-K1T341M

### ISSUE THREAD

**Issue by cclucky1** [pergolafabio/Hikvision-Addons#193]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

Hey, thanks for your dedication to this project, I was able to properly add the hik device I'm using, he works but not all functions, relay and reboot, mute all work fine but Call state keeps showing idle, my device model is DS-K1T341M, firmware version V3.2.30, I'll be more than happy to provide the device information if it's needed! I will be happy to provide information about the device if needed, and finally wish you a good day!

**Comment by pergolafabio** [comment]
Hi , it was requested before, but for some reason, those k1t devices don't provide the event for  call..

Do you also have an indoor device?
Maybe try also pressing the caller/call status button when the device is ringing, maybe that works, check the addon log when you press that button, there is a Json , hopefully it gives the correct call state

**Comment by cclucky1** [comment]
Yes, I have an indoor unit model DS-KH6350-C1, by that do you mean pressing the caller/call status button on the indoor unit when it rings and checking the plugin log?

**Comment by pergolafabio** [comment]
Yes indeed , you can add the indoor device too, to the config...
But also try pressing those mqtt buttons on the outdoor , maybe one of the 2 devices gives the correct info...
If that works, you can create a polling for it

**Comment by cclucky1** [comment]
Just now, I tried to press the Call status button in the ringing state, and in the Addon's logs, I get this, 
`2024-03-28 13:28:36.541 | INFO     | mqtt_input:_call_status_callback:401 - Received call status: {
	"CallStatus":	{
		"status":	"ring"
	}
} and show it as an attribute`
what information do I need to provide to better adapt your Addon, such as displaying it properly in the Call state sensor?

**Comment by pergolafabio** [comment]
Ah, that's good, is that from your indoor or outdoor?

**Comment by cclucky1** [comment]
It's a button press on my outdoor unit, would you be interested in doing an adaptation on this model, if you are I'd be happy to provide any info I have!

**Comment by pergolafabio** [comment]
The problem is that those type of devices are not giving the SDK events, you nee to poll them


For now there is no relationship between the call sensor and the callerinfo/callstatus button...

For the moment, you can make an automation that presses the button like every xx seconds, the JSON is also visible as attribute on that button, so you can build your next automation based on the JSON...

Maybe I can include later an poll sensor....

**Comment by cclucky1** [comment]
Thanks for your dedication to this project, I will try to create polling

**Comment by pergolafabio** [comment]
I keep this one open, will make a new option to create a polling option, to update the call sensor...
But will be something for next weeks

**Comment by pergolafabio** [comment]
For now , you can use a time pattern automation, that polls for like every 4 sec..  

Not sure if it's ok to poll every sec.. :-)

**Comment by cclucky1** [comment]
I have implemented polling once per second and triggering my rtsp to work, it shows up as doorbell in the homekit, tested and they work fine, thanks again for your work on this project!

**Comment by mozzie1121** [comment]
> I have implemented polling once per second and triggering my rtsp to work, it shows up as doorbell in the homekit, tested and they work fine, thanks again for your work on this project!

这个逻辑怎么实现的能分享一下吗？我的设备时K1T670M，也是同样的问题，通过按钮可以获取到设备的状态，我想着把这个门铃添加到homekit里面，是需要结合scrypted来做吗？
