### ISSUE TITLE
DS-KB8112-IM support

### ISSUE THREAD

**Issue by attilhacks** [pergolafabio/Hikvision-Addons#196]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

Hello, I have 3 x DS-KB8112-IM doorbells and I would like to connect to your addon, unfortunately I get this message:

ERROR    | __main__:<module>:101 - Error while listening to events in Citofono Sbarra: Not enough resource on the device. Error code:28

this is the complete log

<encoderVersion>V1.0</encoderVersion>
<encoderReleasedDate>build 180516</encoderReleasedDate>
<deviceType>EmbeddedNetVIS</deviceType>
<telecontrolID>99</telecontrolID>
</DeviceInfo>

2024-04-23 20:44:17.811 | DEBUG    | doorbell:sdk_device_ability:275 - Response url for sdk_device_ability: <?xml version="1.0" encoding="UTF-8"?>
<IpViewDevAbility version="2.0">
<LocalAbility>
<inputVolume min="0" max="10"/>
<outputVolume min="0" max="10"/>
</LocalAbility>
<VideoIntercom>
<DeviceID>
<enabled>true</enabled>
<supportUnitType opt="VillaOutDoorDevice,AgainDevice"/>
<VillaOutDoorDevice>
<period min="1" max="9"/>
<buildingNum min="1" max="999"/>
<unitNum min="1" max="99"/>
<floorNum min="-10" max="10"/>
<devIndex min="0" max="99"/>
</VillaOutDoorDevice>
<AgainDevice>
</AgainDevice>
</DeviceID>
<OperationTime>
<messageTime min="30" max="60"/>
<talkTime min="90" max="120"/>
</OperationTime>
<RelateDevice>
<sipServerIP opt="ipv4"/>
<centerIP opt="ipv4"/>
<centerPort min="0" max="65535"/>
</RelateDevice>
<ControlGateway>
<gatewayIndex min="1"/>
<command opt="open"/>
<controlSrc>true</controlSrc>
<controlType opt="monitor,calling"/>
<lockType opt="normal"/>
</ControlGateway>
<IOIn>
<IOInNo attri="readonly" min="1" max="1"/>
<useType opt="disabled,openDoorBtn,magneticStatus,custom"/>
<NodeList>
<Node>
<id>1</id>
<name>AI</name>
<useType opt="disabled,openDoorBtn,magneticStatus,custom"/>
</Node>
</NodeList>
</IOIn>
<IOOut>
<IOOutNo attri="readonly" min="1" max="1"/>
<useType opt="disabled,electricLock,custom"/>
<NodeList>
<Node>
<id>1</id>
<name>COM</name>
<useType opt="disabled,electricLock,custom"/>
</Node>
</NodeList>
</IOOut>
<supportVisRegisterInfo opt="true"/>
<supportVideoFormat opt="P,N"/>
<CallRoomConfig>
<callManageCenter opt="true,false"/>
</CallRoomConfig>
</VideoIntercom>
<UploadAlarmCfg>
<UploadDoorNotCloseAlarm opt="true,false"/>
</UploadAlarmCfg>
<NoNeedReboot>
<videoResolutionChange opt="true"/>
<videoFrameRateChange opt="true"/>
</NoNeedReboot>
</IpViewDevAbility>

2024-04-23 20:44:17.813 | DEBUG    | mqtt:__init__:166 - Configuring 1 door switches
2024-04-23 20:44:17.818 | DEBUG    | event:register_handler:234 - Adding event handler MQTT
2024-04-23 20:44:17.819 | DEBUG    | mqtt_input:__init__:21 - Setting up MQTTInput
2024-04-23 20:44:17.819 | DEBUG    | sdk.utils:call_ISAPI:125 - Call ISAPI request method url body: GET /ISAPI/System/deviceInfo  
2024-04-23 20:44:17.862 | DEBUG    | sdk.utils:call_ISAPI:165 - Response output: <DeviceInfo version="2.0" xmlns="http://www.isapi.org/ver20/XMLSchema">
<deviceName>Citofono Cancelli</deviceName>
<deviceID>48323133-3133-3235-3238-1868cbf9fc8d</deviceID>
<model>DS-KB8112-IM</model>
<serialNumber>DS-KB8112-IM0120180502WR213132528CL</serialNumber>
<macAddress>18:68:cb:f9:fc:8d</macAddress>
<firmwareVersion>V1.4.5</firmwareVersion>
<firmwareReleasedDate>build 190219</firmwareReleasedDate>
<encoderVersion>V1.0</encoderVersion>
<encoderReleasedDate>build 180516</encoderReleasedDate>
<deviceType>EmbeddedNetVIS</deviceType>
<telecontrolID>99</telecontrolID>
</DeviceInfo>

2024-04-23 20:44:17.912 | DEBUG    | event:start:255 - Registering callback function using SDK
2024-04-23 20:44:17.916 | DEBUG    | doorbell:setup_alarm:90 - Arming the device via SDK
2024-04-23 20:44:17.938 | ERROR    | __main__:<module>:101 - Error while listening to events in Citofono Sbarra: Not enough resource on the device. Error code:28

thanks for your help

**Comment by pergolafabio** [comment]
Do you see the error on all 3 devices? Have you tried maybe upgrading the firmware?
The add-on the first time is downloading a huge backlog, maybe after a few reboots and or restarts , the error will be gone...

**Comment by pergolafabio** [comment]
Sew also this one, he was able to resolve with a reset...

https://github.com/pergolafabio/Hikvision-Addons/issues/178

I think it's firmware related maybe

**Comment by attilhacks** [comment]
Ciao Fabio, yes it's a common thing on all of the 3 devices, I tried resetting one but no luck.  Firmware is the latest available for that model which is kind of old...

it works great on DS-KV6113-WPE1(C) 

Many thanks

**Comment by pergolafabio** [comment]
Hmm , then I'm out of ideas :-(
Maybe you can ask on the community forums to see if other People succeeded with this device?

**Comment by pergolafabio** [comment]
Did you manage to get it to work?

**Comment by attilhacks** [comment]
Hello, thanks for the follow up
no, looks like an issue with the device and not with your code

**Comment by pergolafabio** [comment]
Ah ok, what was the issue? Maybe interesting for other  people?

**Comment by attilhacks** [comment]
no idea, the device jus throws Error code:28 but wasn't able to find the problem :-(  
I will get back to it when I have more time anyways.

thanks
