### ISSUE TITLE
Indoor Station Relays Behavior Improvement

### ISSUE THREAD

**Issue by Sonusss** [pergolafabio/Hikvision-Addons#197]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

The two relay switches exposed to MQTT are just "firing commands" for the two relays of the indoor station.

Issue 1: If someone activate relay on the indoor station this is not reported to MQTT

Issue 2: If the relay is settled with permanent state & toggle (indoor station config menu)  it's state is not reported to MQTT and it is not possible to toggle it to off state. (on is working)

Indoor station DS-KH6320-WTE1  Firmware: V2.2.8
I'm testing with the latest docker image from 3 Month ago.

**Comment by pergolafabio** [comment]
You are correct, but for some reason, the state events on indoor stations are not reported in the SDK, no idea why... Even isapi commands don't provide the feedback :-(

**Comment by Sonusss** [comment]
I'm not familiar with ISAPI etc... but I found this in the SDK documentation on "Display and control"

![image](https://github.com/pergolafabio/Hikvision-Addons/assets/51654027/e36030d9-084d-4d11-9ef6-00d2901085c8)

**Comment by pergolafabio** [comment]
Yeah, I'm familiar with those, but they don't work for indoor stations, I already have an issue open, maybe I can look again in future

**Comment by Sonusss** [comment]
What a pitty,
I will then add an interface GPI to MQTT :-( 

Thx for your time
