### ISSUE TITLE
Can the add-on support DS-KH6320-WTE1 ?

### ISSUE THREAD

**Issue by corcaioch** [pergolafabio/Hikvision-Addons#198]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

Just wondering if this hikvision device is supported by the doorbell add-on?
DS-KH6320-WTE1

**Comment by pergolafabio** [comment]
You can try, I think it was confirmed working by others

**Comment by pergolafabio** [comment]
Let me know if you have issues

**Comment by corcaioch** [comment]
I can see the Com 1 relay switch as a device in home assistant but when I switch it on/off the gate doesn't open. Just wondering if anyone had reported similar issues?

**Comment by pergolafabio** [comment]
Com ports are not used for the door, you need to use the relay switch
