### ISSUE TITLE
Login failed when using spec. symbol in password.

### ISSUE THREAD

**Issue by ArtChm** [pergolafabio/Hikvision-Addons#205]
### What happened?

Docker container failed to start with the error "invalid user name or password" when the password contains a special symbol e.g. $
Everything went well when I changed the password to contain only characters and digits.

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

pergolafabio/hikvision-doorbell:latest

### Installation type

Docker container (standalone)

**Comment by pergolafabio** [comment]
Best to change password indeed, thnx for reporting

**Comment by ArtChm** [comment]
Thanks.
Is it impossible to make a fix instead of a workaround or is this a limitation of the Hikvision library?

**Comment by pergolafabio** [comment]
It's probably indeed a limitation:-(
