### ISSUE TITLE
Please add DS-KV8102-IP support

### ISSUE THREAD

**Issue by alexdan-77** [pergolafabio/Hikvision-Addons#206]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

Hi there!
Outdoor panel DS-KV8102-IP.
this topic is always same (never "ringing")
"hmd/sensor/domophone_panel_01/Call-state/state idle"

instead of other model (DS-KV6103-PE1):
"hmd/sensor/domophone_panel_05/Call-state/state ringing"

I'v got several DS-KV8102-IP and beg you to help to work it out!
Thanks.

**Comment by pergolafabio** [comment]
That device is indeed too old, it doesn't support isapi and SDK, nothing I can do :-(

The only solution is to use hikconnect cloud integration, it's available in Hacs
