### ISSUE TITLE
Entities become 'unavailable' within a few hours of restarting the add-on.

### ISSUE THREAD

**Issue by Whytey** [pergolafabio/Hikvision-Addons#211]
### What happened?

When first started, the add-on seems to work OK.  After a number of hours, all entities become 'unavailable'.  A restart of the add-on fixes things...for a few hours.  No errors appear in the logs.  Raising the log level doesn't seem to provide any insight either.

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

3.0.15

### Installation type

Home Assistant add-on

### Relevant log output

```Text
[2024-06-17 21:23:01.665][DBG] Alarm chan [0] recv timeout[2]!
[2024-06-17 21:23:31.701][DBG] Alarm chan [0] recv timeout[2]!
[2024-06-17 21:24:01.740][DBG] Alarm chan [0] recv timeout[2]!
[2024-06-17 21:24:31.773][DBG] Alarm chan [0] recv timeout[2]!
[2024-06-17 21:25:01.815][DBG] Alarm chan [0] recv timeout[2]!
[2024-06-17 21:25:31.857][DBG] Alarm chan [0] recv timeout[2]!
[2024-06-17 21:26:01.882][DBG] Alarm chan [0] recv timeout[2]!
[2024-06-17 21:26:31.917][DBG] Alarm chan [0] recv timeout[2]!
[2024-06-17 21:27:01.945][DBG] Alarm chan [0] recv timeout[2]!
```

### Anything else?

![image](https://github.com/pergolafabio/Hikvision-Addons/assets/876620/b6f032ac-71a7-43a9-9c8d-df6ca4a94d27)

**Comment by pergolafabio** [comment]
is the addon maybe stopped? that makes the entities unavaibale

**Comment by Whytey** [comment]
No, the add-on still reports as running and continues to log that message
regularly.

**Comment by pergolafabio** [comment]
thats very strange, maybe an mqtt issue ?

**Comment by Whytey** [comment]
I assume the suggestion is delete the mqtt entities and restart the add-on?

**Comment by pergolafabio** [comment]
after how many hours di you see the addon stopping? can you enable debug mode on it? there must be a reason why it stops
of is it still runnning? maybe worth checking the mqtt logs? i dont see the behaviour on my side

**Comment by paddawan2002** [comment]
I will flush the mqtt entities and put on debug. I had been using the beta as it seemed to be up longer. I just haven't spent the time drilling into the specific behaviour. Normally after half a day or a day it becomes unavailable.

**Comment by pergolafabio** [comment]
Hmm, the beta is the same as the main, no difference between those...
Are you maybe running both? Maybe that's causing the issue?

**Comment by Whytey** [comment]
I seem to be stuck on "ringing" now. 🤣

**Comment by pergolafabio** [comment]
Probably a backlog , is it flipping the whole time? Do you see it changing in log? Once complete it should be stable again

**Comment by Whytey** [comment]
No, I don't think it was backlog.  The addon had been up for ~18hrs.  It
was showing idle for most of the time but correctly changed to ringing when
the doorbell rang - but never returned to idle...for more than 11 hrs.  I
was able to click the hangup and reject call buttons.  The logs reflected
the button being pressed and commands being issued but didn't affect the
state.  A quick restart of the addon this morning and the state has
returned to idle.

**Comment by pergolafabio** [comment]
That's possible indeed, the reject/hangup buttons doesn't always work on every type of device, sometimes you need an indoor panel, and you need to send the commands there to stop the ringing 

As long as the entity is idle, and the addon is running, its working

**Comment by paddawan2002** [comment]
I have cleaned up MQTT topics, removed both versions (I was only running one at a time), and reinstalled 3.0.15. Been stable for a 3 days. Thanks

**Comment by arathunku** [comment]
Hi, Anyone else is runnig into this issue?

I got indoor station and doorbell connected and recognized. The button are available but they don't do anything. I can see in logs it's correctly receiving information about card swipe / call, but I cannot trigger door open by any of the controls.

In debug logs I can see:

```log
024-11-13 21:08:46.038 | DEBUG    | event:start:255 - Registering callback function using SDK
2024-11-13 21:08:46.039 | DEBUG    | doorbell:setup_alarm:91 - Arming the device via SDK
[2024-11-13 21:08:46.041][INF] Private connect 192.0.0.65:8000 sock=205 this=0x718d2504 cmd=0x111020 port=48862
2024-11-13 21:08:46.046 | DEBUG    | doorbell:setup_alarm:91 - Arming the device via SDK
[2024-11-13 21:08:46.049][INF] Private connect 192.0.0.63:8000 sock=208 this=0x718d2ae8 cmd=0x111020 port=37412
2024-11-13 21:08:46.052 | DEBUG    | input:loop_forever:29 - Waiting for input command
[2024-11-13 21:09:16.093][DBG] Alarm chan [0] recv timeout[2]!
[2024-11-13 21:09:46.141][DBG] Alarm chan [0] recv timeout[2]!
[2024-11-13 21:10:16.187][DBG] Alarm chan [0] recv timeout[2]!
[2024-11-13 21:10:46.240][DBG] Alarm chan [0] recv timeout[2]!
[2024-11-13 21:11:16.280][DBG] Alarm chan [0] recv timeout[2]!
```

 version 3.0.18.

I already reinstalled the addon (with MQTT topic clean) but this didn't help.

![image](https://github.com/user-attachments/assets/18b90245-53ae-4eef-abf2-54bf77974024)
![image](https://github.com/user-attachments/assets/3d90e654-3386-494a-9fdc-b269d1e17b38)

**Comment by pergolafabio** [comment]
Can you also try to delete the whole matt device, then start the addon again?

**Comment by pergolafabio** [comment]
And "sensor" too probably? :-)

**Comment by arathunku** [comment]
@pergolafabio yes... sensor too :smile: Anything else? I can submit a PR to docs if you point me where I can find some code related to topics :D

**Comment by pergolafabio** [comment]
Hey , probably all these :

https://github.com/pergolafabio/Hikvision-Addons/blob/4ee35a4e07cd27eee60573e886c57b7316c27f6a/hikvision-doorbell/src/mqtt.py#L10

And

https://github.com/pergolafabio/Hikvision-Addons/blob/4ee35a4e07cd27eee60573e886c57b7316c27f6a/hikvision-doorbell/src/mqtt_input.py#L7

**Comment by arathunku** [comment]
Ohh.... so there isn't a single topic at all, just every type of sensor as a topic. Ok
