### ISSUE TITLE
Door status not displaying when gate is opened via gate remote control

### ISSUE THREAD

**Issue by MarcoCITA** [pergolafabio/Hikvision-Addons#213]
### What happened?

I wired the doorbell so that when i open the gate home assistant sees that the gate is open. When i open the gate via Home Assistant switch entity or via the indoor unit works fine, but when i open the gate with the gate remote the entity doesn't work.
![Entity door is open](https://github.com/pergolafabio/Hikvision-Addons/assets/53432302/6ac9a74e-fba9-44fb-9f0d-bacca944ae28)
![Gate remote](https://github.com/pergolafabio/Hikvision-Addons/assets/53432302/754bb6ba-b2f8-4706-b8ee-feb1a4660393)

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

3.0.15

### Installation type

Home Assistant add-on

### Anything else?

The automation that turns ON or OFF the switch "door open"
![Portone aperto](https://github.com/pergolafabio/Hikvision-Addons/assets/53432302/0779d292-4710-49e0-a8d8-ffed6a44da74)
![Portone chiuso](https://github.com/pergolafabio/Hikvision-Addons/assets/53432302/871b2744-8951-4eb5-a315-75819e2697bd)

**Comment by pergolafabio** [comment]
Can you show the log of the addon when you open the gate with the remote? Do you see any event there? What type of doorbell do you have? Not all SDK events are always triggered...

**Comment by MarcoCITA** [comment]
No events in the addon log. Doorbell DS-KD8003-IME1

**Comment by pergolafabio** [comment]
Indeed, that's a known issue, seems that event is not logged on the doorbells, nothing I can do :-(

You can invert the logic, someone else posted it on the forum as a workaround
