### ISSUE TITLE
Support for DS-K1T502DBFWX(-C) and/or DS-K2604T

### ISSUE THREAD

**Issue by IOTMOTG** [pergolafabio/Hikvision-Addons#214]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

Hi, I see that the DS-K1T502DBFWX is not supported at all at the moment.
Is this due to hardware?

I use 2 of these devices (DS-K1T502DBFWX and DS-K1T502DBFWX-C) in a Airbnb and they work perfect.
They are connect to a Hikvision DS-K2604T Acces controller together with other keypads and fingerprint readers.

Recently I started upgrading the place to Home Assistant (previously worked with Sonoff/Ewelink and other platforms together)

I managed to add/migrate almost all of the smart devices, sensors, camera's, etc. the only struggle I have is with the Doorbell and Access controller.

Is there any way to add them or is there a plan in the future to add support for these devices?

Kind regards,

Martijn

**Comment by pergolafabio** [comment]
We tried adding it, but seems the device doesnt support SDK, you can use Isapi to grab ecengsy... See here

https://github.com/pergolafabio/Hikvision-Addons/issues/177
