### ISSUE TITLE
Error when installing addon

### ISSUE THREAD

**Issue by karelrychtar** [pergolafabio/Hikvision-Addons#22]
Hi, I have a Hikvision DS-KV8202 intercom with KH8301 indoor stations. Now I am interested in connecting this intercom to HA, but I can't manage to run the installation with an error in printscreen. Can you please advise me what is wrong? Thank you

![hik_error_msg](https://user-images.githubusercontent.com/59023537/184234186-e15fe76f-f7bc-4be0-acd4-f1e0d030f81b.png)

**Comment by pergolafabio** [comment]
Raspberry? Doesn't work on it...

But actually, you don't need to run this opensips at all.... You can just add the extensions with a random sn, and just register asterisk as a trunk, no need anymore for this addon

**Comment by karelrychtar** [comment]
Hi, I have just read the same problem in closed issues. Yes Rpi4 x64. Thank you

**Comment by pergolafabio** [comment]
Indeed , but you don't need this addon to forward the call ...I gonna remove it soon, just use asterisk and register a trunk, important is to first add the extension manually on the indoor

**Comment by pergolafabio** [comment]
It's compatible now, I was able to retrieve the SDK for RPI
