### ISSUE TITLE
Event too slow

### ISSUE THREAD

**Issue by vk496** [pergolafabio/Hikvision-Addons#220]
### What happened?

Hello and thank you for this great work.

I notice that the automation I'm building are not very smooth because the status change (from idle to ringing) are not instantaneous.

I don't have much experience with ISAPI, but maybe the add-on is pulling status instead of subscribing to events? I think it's weird (since I can see in the logs events for motion), but that's my unique explanation for a delay of 3s

I'm happy to contribute if it feasible to improve that part

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

3.0.15

### Installation type

Home Assistant add-on

**Comment by pergolafabio** [comment]
Hi , call events should be instant, it doesn't poll, it doesn't use Isapi...
What do you see in the log when someone pressed the doorbell? Maybe you have a delay on the mqtt ?

**Comment by pergolafabio** [comment]
let me know if you still need help
