### ISSUE TITLE
Add K1T670M

### ISSUE THREAD

**Issue by mozzie1121** [pergolafabio/Hikvision-Addons#221]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

ValueError: 10552 is not a valid DeviceType

Device Modle: Hikvision K1T670M
Device Type :10552

**Comment by pergolafabio** [comment]
Hi , i added beta 66 , can you test it? make sure to refresh the addons to see beta 66
also, stop the main addon, dont run the addon twice

**Comment by pergolafabio** [comment]
were you able to test? do you see alarm events? probably call sensor doesnt wor, i i believe these K1T devices dont register a call event, you can try polling the call button to see if you receive the status
