### ISSUE TITLE
Feature: Creating a number entitity to define the output volume

### ISSUE THREAD

**Issue by pergolafabio** [pergolafabio/Hikvision-Addons#228]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

This fixed : https://github.com/pergolafabio/Hikvision-Addons/issues/226

Instead of mute/unmute and reading current values, it maybe better to create a number entity / service so the user can define the volume itself between 0..10

**Comment by 6PATyCb** [comment]
Don't forget read current value at add device step if it possible.

**Comment by pergolafabio** [comment]
Hi , there is now an text entity avaible, so you can put your onw isapi command to the indoor/outdoor to give full control, no need anymore to create an an seperate button now

**Comment by 6PATyCb** [comment]
Hello. Sounds great! Thanks for your work! I'll check it tomorrow.
