### ISSUE TITLE
DS-KH632-WTE

### ISSUE THREAD

**Issue by jtricerolph** [pergolafabio/Hikvision-Addons#229]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

Am tinkering with intergrating an older system.
By doorbell works well which is a KV6113 however there is an older 4 button villa intercom on the driveway gate I was hoping to link in also.
The gate intercom is a 8401 which can see 8201 is only lock supported which is similar on this but was hoping it would be possible to catch the call in the indoor station however this only shows the 2 internal relays.
All the listed models seem to be the external doorbel units but the screenshot shows indoor unit card?
Any advice on how I might achive this?

**Comment by jtricerolph** [comment]
Alternativly see DS-KV8413 listed as working? How does this present within HA? entity per extention/button? or can you specify one?

**Comment by pergolafabio** [comment]
Hi, a call event only comes from outdoor unit... You can also add indoor units to the addon config, butsvits very limited in use... Thee is s callerinfo button, bit there is no event, you need to manually press/poll it

**Comment by jtricerolph** [comment]
Thanks for the quick reply, so upgrading to say DS-KV8413 would be best option.
How does this work with the 4 buttons if it all comes from outdoor unit?

**Comment by pergolafabio** [comment]
Unfortunately you can't see in the call event what button is pressed :-(

You can make an automatiion to poll the caller info button, to see what indoor station is ringing at that moment

**Comment by jtricerolph** [comment]
Are there any indoor units known to work showing call state?

**Comment by pergolafabio** [comment]
For call events? No, dont think so

**Comment by jtricerolph** [comment]
Are there any indoor units known to work showing call state?

It's probably above my abilities but could setting the call center ip to something that can tap in that way?

**Comment by pergolafabio** [comment]
Isn't it easier for you to go ahead with SIP, then you do what you want

**Comment by jtricerolph** [comment]
I was just reading through the SIP docs 🤣
Already have a dev freepbx instance from previous project so will have a play.

Just trying to get my head arround the sip flow.

**Comment by pergolafabio** [comment]
i believe all hikvision cameras/doorbell use the same isapi commands for two way audio, it should work
note, on a real incoming call, its not possible to start two way audio, you first need to drop the callsignal command, by sending it to the correct indoor station

**Comment by jtricerolph** [comment]
indeed, have that setup there is no return audio to doorbell either in idle (as works with newer doorbell on house) or after answer/reject via corasponding indoor unit.
have ordered a 8413 outdoor unit, hopefully that plays ball a bit better

**Comment by jtricerolph** [comment]
Sorry, this probably.not the place tk ask but tried moving frigate to my main server in workshop/outbuilding with more power rather than the lower power ha serverPC in the house and switched to the frigate proxy and changed intergration to point to the external server but now the frigate cards have lost mic and not giving any sound.
Sound working in frigate and the frigate proxy tab with ha.
An sugestikns?

**Comment by pergolafabio** [comment]
hmm, no experience with that :-(

**Comment by jtricerolph** [comment]
Issue seems to be remote vs local network
