### ISSUE TITLE
How to use the SDK as docker container iso add-on

### ISSUE THREAD

**Issue by whulshof** [pergolafabio/Hikvision-Addons#23]
Hi pergolafabio,

Your add-on is great, I think. Using the intercom without the cloud is exactly what I am trying to achieve.
But I'm running HA in a docker container inside Truenas Scale (it is a Kubernetes pod really, but use it as a docker container). I'm therefor managing my addons myself as containers, because supervisor is not available. I created the docker image for hikvision SDK with the Dockerfile in this repo. In the repository also a file config.json is present, but in hik.py there is a /data/options.json needed. May I assume, that this is the same file?
Further only hik.py and hcnetsdk.py are copied to the image. What is the purpose of the other .py files?
Thanks in advance for your help!

**Comment by pergolafabio** [comment]
yeah, that json file is indeed stored in the /data folder, its a persistant share, specific for HA addons
you can store it offcourse where you want, its just for storing the IP and password and stuff

indeed those 2 .py files and offcourse the "lib" folder

the other folder / files were just for testing and sending other commands, but not used indeed in the container

**Comment by whulshof** [comment]
Ahh, thanks!

Verstuurd vanaf mijn iPhone

Op 17 aug. 2022 om 08:20 heeft pergolafabio ***@***.***> het volgende geschreven:

﻿

yeah, that json file is indeed stored in the /data folder, its a persistant share, specific for HA addons
you can store it offcourse where you want, its just for storing the IP and password and stuff

indeed those 2 .py files and offcourse the "lib" folder

the other folder / files were just for testing and sending other commands, but not used indeed in the container
