### ISSUE TITLE
Support for DS-KH8350-WTE1

### ISSUE THREAD

**Issue by 45Commando** [pergolafabio/Hikvision-Addons#230]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

Hi, would it be possible to support the  DS-KH8350-WTE1

Thanks!

**Comment by pergolafabio** [comment]
thats an indoor device? that should be possible already, but its limited, dont expect call events ... for the advanced stuff, you need to add the outdoor station in the config

**Comment by 45Commando** [comment]
Sorry DS-KH8350-WTE1 is the code for the indoor station that is central display for it and i thought that was the product code for my intercom.

I have a DS-KD8003-IME and see that ti si supported so thats great!!  Thanks

**Comment by pergolafabio** [comment]
i have the same 8003 device :-)

**Comment by 45Commando** [comment]
Great, i just have to find my login details now... doh

**Comment by 45Commando** [comment]
doy ou have sample config for a relay?  output_relays: ???

**Comment by pergolafabio** [comment]
Not needed, relays are added automatically, the first one...

**Comment by 45Commando** [comment]
Do what do i need to do to see it on my dashboard?

**Comment by pergolafabio** [comment]
Once addon is started, you should see an mqtt devices ,  they are all entities like sensors, switches ....

**Comment by 45Commando** [comment]
ok i must have a problem somewhere as it is not showing up... will invistigate...

**Comment by pergolafabio** [comment]
iP incorrect? Is HA on same network as device?

**Comment by 45Commando** [comment]
Yes should be correct, i can see it online in HIK-Connect App.  

same /24 network..

will leave until i am home... currently on vacation in Hawaii :-)

**Comment by 45Commando** [comment]
Thank you for your support, once i have it sorted and working ill donate :-)

**Comment by pergolafabio** [comment]
Ty! :-)
