### ISSUE TITLE
Source code or technical explanation?

### ISSUE THREAD

**Issue by ygoe** [pergolafabio/Hikvision-Addons#236]
### What happened?

First, I wanted to ask this in the HA forum but that forum won't let me create an account, so this is my only possibility to contact anybody here. I know it's not ideal but the ideal solution failed and this is the best fallback I have.

I'm interested in getting a video doorbell based on this Hikvision manufacturer and would like to learn how I can interact with it from a smart home system. I'm not sure whether it will be Home Assistant. Anyway, I'd like to take a look at the actual communication between a smart home system and the device itself. But I can't find anything. This repository doesn't contain any code or anything that I would identify as instructions how to communicate with the device. Is it a web API or something else? Where can I find that mentioned SDK from Hikvision? How can I be informed about the doorbell being pressed or the fingerprint being accepted so that the door can be opened? These are my primary concerns here. For now, I'm less interested in the audio/video features, those can be used with the indoor displays or apps as well.

I could probably intercept the doorbell button wire and also monitor the door opener wire and forward these signals with custom hardware, but if the network interface can give me this information, it'll be better.

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

0.0

### Installation type

Home Assistant add-on

**Comment by pergolafabio** [comment]
Hi , all source code is in the "dev" branch :-)

It's based on the SDK, using port 8000, grabbing events is better with SDK, all tough you can also use Isapi commands to poll status or send commands to open door etc...

**Comment by ygoe** [comment]
Thanks, I think I can make my way from there.

**Comment by pergolafabio** [comment]
Let me know if you need extra info
