### ISSUE TITLE
See door station inputs as entities 

### ISSUE THREAD

**Issue by fatmacheto** [pergolafabio/Hikvision-Addons#237]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

It will be useful to see the door station inputs so you can trigger events based on them like example move a ptz camera when someone press the request to exit button or have an alarm if the  door was left open for a set period of time.

**Comment by pergolafabio** [comment]
Hi, all alarms like inputs are device triggers, you can build your automations on those triggers
