### ISSUE TITLE
DS-K1T673DWX Support

### ISSUE THREAD

**Issue by 45Commando** [pergolafabio/Hikvision-Addons#238]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

Hi Fabio..  Hope your well.  Thank you for your support.

Do you know if you would be able to add support for the DS-K1T673DWX as i have one coming for my new front door!!!! :-)  Face recognition to open my door :-)

https://www.hikvision.com/uk/products/Access-Control-Products/Face-Recognition-Terminals/Pro-Series/ds-k1t673dwx/

Mark

**Comment by pergolafabio** [comment]
I think it will work, the only thing that doesnt work is the call event, you need to poll that manually

**Comment by pergolafabio** [comment]
Yeah, there are buttons , you can create an automation to poll/push it every xx seconds, there is also on hacs an hikconnect integration

**Comment by 45Commando** [comment]
Great thanks. ill checl it out.
