### ISSUE TITLE
sdk container exits without alert

### ISSUE THREAD

**Issue by whulshof** [pergolafabio/Hikvision-Addons#24]
The log shows:
08/17/2022, 12:01:31 Hikvision SDK Add-on started! Listening for events...
loop[2] find 2 mac and 0 ip

No clue what the last line implies

**Comment by pergolafabio** [comment]
thats correct, thats a normal line :-)
no idea where its coming from, its somekind of output of the login process

**Comment by whulshof** [comment]
The door bell is in a different network segment, but reachable over IP. Could that be the trouble?

**Comment by pergolafabio** [comment]
i have it too
but aware , first time you start the script, its downloading a log file from the device, so its possible you are seeing false events for the first few min


![image](https://user-images.githubusercontent.com/43251136/185116817-0286893a-9369-4d1d-91f3-95ce8b25ba1a.png)

**Comment by whulshof** [comment]
No, the thing is that the container quits

**Comment by pergolafabio** [comment]
ahh, thats not normal :)

**Comment by whulshof** [comment]
the 2 Mac and 0 ip could mean something regarding the network segment it is trying to connect in

**Comment by pergolafabio** [comment]
no, if it was not able to connect you would get an error
just try with a wrong ip, then you will see

**Comment by whulshof** [comment]
OK, I will try some things and report on it later

**Comment by pergolafabio** [comment]
i think your container just quites, becase there is no output

the addon was based on this script, i removed the "waiting for input"

https://github.com/laszlojakab/hikvision-intercom-python-demo/blob/main/hik.py

see line 72 of that script
maybe you need to add it back , but not sure if it works with docker, or you need some other wait command

**Comment by pergolafabio** [comment]
input("Press Enter to exit...\n")

add that again on correct place like in script above

**Comment by whulshof** [comment]
If I use non-existing IP for the intercom, I get a different error indeed: NET_DVR_Login_V30 failed, error code = 7

**Comment by pergolafabio** [comment]
yes, so i think the script works and is connected, but the container just quits, because there is no output

**Comment by pergolafabio** [comment]
when i sometimes test addons, i use the command below, to keep the container alive

`ENTRYPOINT ["tail", "-f", "/dev/null"]`

**Comment by pergolafabio** [comment]
yes, it should, but i think the addon is acting differently then when you start the script in a container
its a onetime run script, it doesnt do anything, it just waits as a listener

thats why in the original script, this line is there, because if you run that hik.py file as a normal python script, without line below,  it also quits...

`input("Press Enter to exit...\n")`

**Comment by whulshof** [comment]
I'm getting 
Traceback (most recent call last):
  File "hik.py", line 134, in <module>
    input("Press Enter to exit...\n")
EOFError: EOF when reading a line

**Comment by pergolafabio** [comment]
yeah , not sure if that command can be used in a container, i think you need to find an equivalent
but your are running HA as a core right? maybe on debian/ubuntu ? then you dont need to create a container at all, just run the script as a shell command ?

the reason why i created this addon for HassOS users, is because the library supplied by Hikvision doesnt run on Alpine

**Comment by whulshof** [comment]
aha! So I put the python code and the lib somewhere in HA and it will run?

**Comment by whulshof** [comment]
but how should I keep that script running? Same problem I think?

**Comment by pergolafabio** [comment]
see also here about that EOF error
https://stackoverflow.com/questions/44210435/docker-python-file-input-selector

you need interactive mode

**Comment by whulshof** [comment]
I don't know on which linux it runs

**Comment by pergolafabio** [comment]
the docker image makes use of your host, right?

**Comment by whulshof** [comment]
yes, that is running Trueness Scale. Not clear to me what the base of that is, but no Alpine

**Comment by pergolafabio** [comment]
you can try, but i dont think it will work :-) , the library supplied by hikvision is quite limited to specific OS

if doesnt work, try to run the docker image sdk as interactive, or search for another command instead of input() , because input() indeed interactive mode .... maybe somekind of wait/sleep method in python

**Comment by whulshof** [comment]
yes, there are wait commands, so I'll look for that.

**Comment by pergolafabio** [comment]
not sure if wait is going to work, because the script needs to continue , otherwise you dont see any output in case of event
i think you need to run the script in somekind of background mode, or why not using the interactive mode?

**Comment by pergolafabio** [comment]
hmm, disregard, maybe wait indeed works :-)

**Comment by whulshof** [comment]
What I read is that I should make use of threading.Event.
What I do not understand in the add-on as it is is the way the hik.py is restarted every time. 
Suppose it waits somehow until response from intercom has arrived and is processed towards HA. How does it restart the hik.py script again?

**Comment by pergolafabio** [comment]
no, the addon doesnt restart the hik.py file, its just one running process, and keeps running forever

have you tried the wait process?

**Comment by whulshof** [comment]
working on it

**Comment by pergolafabio** [comment]
i had it running also a as a script before, as you can see i also had the EOF error
https://community.home-assistant.io/t/ds-kd8003-ds-kv8113-ds-kv8213-ds-kv6113-ds-kv8413-and-integration-hikvision-hikconnect-video-intercom-doorbell/238535/521

but i dont remember anymore the command i used as alternatie in docker

**Comment by pergolafabio** [comment]
i believe it was indeed somekind of sleep or wait , was quite simple :-)

**Comment by pergolafabio** [comment]
did you fix it?

**Comment by whulshof** [comment]
No, not yet. I am setting up the virtual machine on Truenas with a Debian 11 OS. I want to try the docker image on that one.

Verstuurd vanaf mijn iPhone

Op 18 aug. 2022 om 18:19 heeft pergolafabio ***@***.***> het volgende geschreven:

﻿

did you fix it?

**Comment by pergolafabio** [comment]
Ok, haven't you tried the interactive mode? Then the input command should work

**Comment by whulshof** [comment]
Mmmm.. that is not a bad idea!

**Comment by whulshof** [comment]
Yes, now I'm getting response from intercom. And the container also updates HA. Only motion detection all the time, but in each case we're having a response!

**Comment by whulshof** [comment]
I wanted to activate that virtual machine anyway, so no worries.

**Comment by whulshof** [comment]
The funny thing is, that I commented out the input command, but the interactive mode keeps running anyway

**Comment by pergolafabio** [comment]
Yeah, all the motion and log you are now seeing is history data, it will stop soon :-)

Only first time

**Comment by pergolafabio** [comment]
for open door, it was also part of the addon to send a stdin message to the docker
but you can also just use a curl ISAPI command, probably easier for you :-)

**Comment by whulshof** [comment]
It is still receiving motion detection messages. Already for the past 1,5 hours. Every 7 seconds a message.

**Comment by pergolafabio** [comment]
Hmm, maybe false detections? Maybe a tree moving? :+)

I don't use motion, I have that turned off on my device itself...

Or just strip the event from the script, comment out that print line :-)

**Comment by pergolafabio** [comment]
Maybe you setup the sensitivity on the device itself?

**Comment by whulshof** [comment]
Yeah, I'll switch off the motion detection, bcs every passing car or moving tree will trigger it.

**Comment by whulshof** [comment]
It already was switched off.... mystery

**Comment by pergolafabio** [comment]
That's strange indeed, maybe the SDK is downloading it anyway, just comment out the lines where I update the sensor then :-)

**Comment by whulshof** [comment]
I'll keep you updated with my Hikvision adventure

**Comment by pergolafabio** [comment]
Veel geluk ermee ;-)

**Comment by whulshof** [comment]
Dankjewel
