### ISSUE TITLE
Asterisk Docs improvement for Doorbell without indoor 

### ISSUE THREAD

**Issue by berga** [pergolafabio/Hikvision-Addons#241]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

Hi Fabio,

I've read the explanation at asterisk/asterisk.as.indoor.md

but maybe I can't apply it to my case:
I've got a Doorbell DS-KV8113-WME1(C) without indoor.
I've set up the HA Addon and the Asterisk as well
and the HA NSPanels with the Asterisk card (both doorbell and panels seems to be registered).

Right now I can't pick up the call and the panel doesn't ring on upcoming calls, 
also when pushing the doorbell button it replies right back with busy tone.

The manual asterisk/asterisk.as.indoor.md treats the case of a doorbell with indoor station,
can I help to make a further version or a new one for people who haven't the indoor unit?

kind regards
  Marco

**Comment by pergolafabio** [comment]
If you don't have an indoor device , you don't need my workaround, you need to configure the SIP settings in your device itself

**Comment by pergolafabio** [comment]
There is an asterisk addon and wiki there, how to use sip on doorbell device, it's out of scope for this addon...

The workaround I created is just a guide a wanted to share how to use the forward the call to HA without using the official show to have the advantages I mentioned in the guide :-)
