### ISSUE TITLE
A windows question rather then an Issue

### ISSUE THREAD

**Issue by giluriel** [pergolafabio/Hikvision-Addons#25]
Hi,
I'm trying to implement the door intercom solution on my system.
I have two questions:
1. the "sensor" section is preaty much clear. in my case the is an include line in configuration.yaml so I added it in the sensors.yaml file.
But, to which  files do I add the service section?
also, I installed the add on (or, I think I did LOL) But i don't see its configuration and I guess that the ip\username\password.... section should be there, right? any idea what am I missing?
** EDIT ** for the ones to run into the same issue - after adding the repository it is "only" in the store. it seems I forgot to actually install it :)

2. My current HASS is on an Oracle vmbox - inside a windows machine. would it be ok for the SDK or must I reinstall it as a hyperV machine? (any other option?)

many thanks 
Gil

**Comment by pergolafabio** [comment]
Hi, not sure what you mean by:  "But, to which files do I add the service section?"

IF the addon is installed correctly, you should see this, what do you see then?
You used HassOS an a vmbox? that should not be a problem, doesnt mather if your PC is a windows
I'm running also HassOS on a esxi system

![image](https://user-images.githubusercontent.com/43251136/185443534-3b69392e-8ef2-470b-bcf7-8d918058ef48.png)

**Comment by giluriel** [comment]
Hi, Thank for the prompt response :)
I got the configuration screen you attached (and completed the token as well).
I now have to add this section - but I;m not sure where I should add it:

sensor:
  - platform: template
    sensors:
      hikvision_door:
        value_template: "off"
      hikvision_callstatus:
        value_template: "off"
      hikvision_motion:
        value_template: "off"

**Comment by pergolafabio** [comment]
No, I have my sensors in a seperate sensor.yaml file that I include

**Comment by giluriel** [comment]
> No, I have my sensors in a seperate sensor.yaml file that I include

Thanks. 
I can't seem to find your file. can you point me where it is?

**Comment by pergolafabio** [comment]
No, you need to make it yourself, and include... The same as the one with the secrets.yaml

**Comment by pergolafabio** [comment]
or use the new template, the code I posted is the legacy version

**Comment by pergolafabio** [comment]
https://www.home-assistant.io/integrations/template/

**Comment by giluriel** [comment]
Hi,
Thanks for all the help. Still working on it. 
I looked at this project: "hikvision-intercom-python-demo" and specifically at the hcnetsdk.py file.

I need to install these files as well? if so- where do I put them? or how do I point the HASS to these files?

thanks again for all the help. probably seems very basic for you but it's still some mystery for me LOL

**Comment by pergolafabio** [comment]
if running on windows, yes, you need linwin64 also, i added those files also on my dockerfile, but i dont copy them , i dont se it

https://github.com/pergolafabio/Hikvision-Addons/blob/main/hikvison-sdk/hcnetsdk.py#L157

i only copy lib for linux, so the addon doesnt work for windows, i didnt test it
if you want to run as addon , change also this line then:

https://github.com/pergolafabio/Hikvision-Addons/blob/main/hikvison-sdk/Dockerfile#L7
