### ISSUE TITLE
multiple outdoor stations

### ISSUE THREAD

**Issue by fabianbonte** [pergolafabio/Hikvision-Addons#28]
Hi Fabio, is it possible to run multiple instances of the SDK? I have more then one outdoorstation that i would like to have status updates on

**Comment by pergolafabio** [comment]
hmm, no , but just fork my project/addon and load it as a second addon :-)

it should work, with this addon, but its not coded yet :-)

**Comment by fabianbonte** [comment]
I think you can’t add two of the same addon’s

 

mvg,

 

Fabian Bonte

 

 

Van: pergolafabio ***@***.***> 
Verzonden: donderdag 29 september 2022 15:46
Aan: pergolafabio/Hikvision-Addons ***@***.***>
CC: fabianbonte ***@***.***>; Author ***@***.***>
Onderwerp: Re: [pergolafabio/Hikvision-Addons] multiple outdoor stations (Issue #28)

 

hmm, no , but just fork my project/addon and load it as a second addon :-)

it should work, with this addon, but its not coded yet :-)

**Comment by fabianbonte** [comment]
Ah yeah, that way it would work 😊

 

mvg,

 

Fabian Bonte

 

 <http://trifase.be/> trifase.be ////

------------------------------

TriFase BVBA

 <x-apple-data-detectors://7/1> Rumbeeksesteenweg 187

 <x-apple-data-detectors://7/1> 8800 Roeselare-Rumbeke

 <x-apple-data-detectors://7/1> Belgium

------------------------------

BTW: BE  <tel:0832%20787%20857> 0832 787 857

BE02  <tel:3630%208130%205440> 3630 8130 5440

BIC: BBRUBEBB 

------------------------------

Tel:  <tel:+32%2051%2043%2040%2049> +32 51 43 40 49

 ***@***.***> ***@***.***

 <http://www.trifase.be/> www.trifase.be

 <http://www.trifase.be/disclaimer> disclaimer

 

Van: pergolafabio ***@***.***> 
Verzonden: donderdag 29 september 2022 16:05
Aan: pergolafabio/Hikvision-Addons ***@***.***>
CC: fabianbonte ***@***.***>; Author ***@***.***>
Onderwerp: Re: [pergolafabio/Hikvision-Addons] multiple outdoor stations (Issue #28)

 

yes, you can, fork my project and then add it again as custom repository, with your github url then

**Comment by fabianbonte** [comment]
Can only fork it once though

 

mvg,

 

Fabian Bonte

 

 <http://trifase.be/> trifase.be ////

------------------------------

TriFase BVBA

 <x-apple-data-detectors://7/1> Rumbeeksesteenweg 187

 <x-apple-data-detectors://7/1> 8800 Roeselare-Rumbeke

 <x-apple-data-detectors://7/1> Belgium

------------------------------

BTW: BE  <tel:0832%20787%20857> 0832 787 857

BE02  <tel:3630%208130%205440> 3630 8130 5440

BIC: BBRUBEBB 

------------------------------

Tel:  <tel:+32%2051%2043%2040%2049> +32 51 43 40 49

 ***@***.***> ***@***.***

 <http://www.trifase.be/> www.trifase.be

 <http://www.trifase.be/disclaimer> disclaimer

 

Van: pergolafabio ***@***.***> 
Verzonden: donderdag 29 september 2022 16:05
Aan: pergolafabio/Hikvision-Addons ***@***.***>
CC: fabianbonte ***@***.***>; Author ***@***.***>
Onderwerp: Re: [pergolafabio/Hikvision-Addons] multiple outdoor stations (Issue #28)

 

yes, you can, fork my project and then add it again as custom repository, with your github url then

**Comment by pergolafabio** [comment]
ah, you can also copy/paste the hikvision-sdk folder to your "addons" folder , then it shows up as  local addon

**Comment by fabianbonte** [comment]
Dag Fabio, werkt jou 8003 standalone? Zou graag meerdere integreren zonder de binnenpost.
Vanaf dat de binnenpost afgekoppeld is werken de statusupdates nog (krijg wel geen satusupdates van de 8003 zonder dat deze eerst eens verbinding gemaakt heeft met een binnenpost) maar de buitenpost zegt steeds "bellen is mislukt", in het menu is er alvast geen optie om dit uit te zetten..

**Comment by pergolafabio** [comment]
Hey, new , binnenpost is noodzakelijk bij een 8003... Tenzij je sip gebruikt

**Comment by fabianbonte** [comment]
firmware update gedaan en kan niet meer in conf menu van de 8003 grrrr...

**Comment by pergolafabio** [comment]
Van welke firmware naar welke versie?

Wellicht moet je ook je ivms updaten

**Comment by pergolafabio** [comment]
Hey @fabianbonte , we released a new beta, can you test it? You can define multiple doorstations...

If it works, we can create a main release

**Comment by fabianbonte** [comment]
Where can u find it? 

 

mvg,

 

Fabian Bonte

 

 <http://trifase.be/> trifase.be ////

------------------------------

TriFase BVBA

 <x-apple-data-detectors://7/1> Rumbeeksesteenweg 187

 <x-apple-data-detectors://7/1> 8800 Roeselare-Rumbeke

 <x-apple-data-detectors://7/1> Belgium

------------------------------

BTW: BE  <tel:0832%20787%20857> 0832 787 857

BE02  <tel:3630%208130%205440> 3630 8130 5440

BIC: BBRUBEBB 

------------------------------

Tel:  <tel:+32%2051%2043%2040%2049> +32 51 43 40 49

 ***@***.***> ***@***.***

 <http://www.trifase.be/> www.trifase.be

 <http://www.trifase.be/disclaimer> disclaimer

 

Van: Pergola Fabio ***@***.***> 
Verzonden: zaterdag 25 februari 2023 12:17
Aan: pergolafabio/Hikvision-Addons ***@***.***>
CC: fabianbonte ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [pergolafabio/Hikvision-Addons] multiple outdoor stations (Issue #28)

 

Hey @fabianbonte <https://github.com/fabianbonte>  , we released a new beta, can you test it? You can define multiple doorstations...

If it works, we can create a main release

**Comment by pergolafabio** [comment]
Hi, you have added me repo, right? There should me a new addon visible with beta image... Make sure to read the docs how to configure multiple door intercoms

**Comment by mion00** [comment]
Hi @fabianbonte.
You can find all the instructions for using the beta version [here](https://github.com/pergolafabio/Hikvision-Addons/tree/main/doorbell_beta).

**Comment by pergolafabio** [comment]
duplicate, maybe we can discuss here: https://github.com/pergolafabio/Hikvision-Addons/issues/18
