### ISSUE TITLE
Backlog of events can be a physical security risk

### ISSUE THREAD

**Issue by fiskn** [pergolafabio/Hikvision-Addons#29]
Currently it seems that if any events occur on the doorbell whilst the SDK->HA bridge is not running, they are buffered up and sent when it comes back online. This is a minor annoyance for things like the call/bell button, but in the case where you may have automations to trigger a separate smart door latch, this may lead to unexpected door openings. 

Is there anyway to ignore any backlogged events or pass a timestamp (when it originally occurred) along with each action, so that this can be compared to the current time?

**Comment by pergolafabio** [comment]
Yeah , o noticed that too, not sure if it's possible to ignore those... Will havea look later

**Comment by pergolafabio** [comment]
hey @laszlojakab , can you give a hand here? any idea how to disable the backlog/cache?

**Comment by head73** [comment]
I didn't undertand why doesnt'work.
I used service in a script.

alias: Apri Cancelletto
sequence:
  - service: hassio.addon_stdin
    data:
      addon: a53439b8-hikvision-sdk
      input: unlock1
mode: single
icon: mdi:gate-open

**Comment by pergolafabio** [comment]
Gonna close this for now, don't think we can't do anything about it

**Comment by Xmister** [comment]
@pergolafabio Sorry for "resurrecting" an old issue, but the solution seems pretty straightforward to me: Don't forward events to HA after connecting to the station until there is a few seconds without any events.
