### ISSUE TITLE
Just an idea: new sensors

### ISSUE THREAD

**Issue by michalwu** [pergolafabio/Hikvision-Addons#30]
Hi
Thank you for fantastic work. Any chance you could add another sensors? 
Like tamper alarm, or what ID unlocked door.
m

**Comment by pergolafabio** [comment]
hi, the ID for unlocked door is already pressent, its in the attributes of the sensor

the tamper, i can add that indeed if you want?

**Comment by pergolafabio** [comment]
added tamper in 4.1 :-)
