### ISSUE TITLE
New command for call dismiss, maybe?

### ISSUE THREAD

**Issue by vavsaftoiu** [pergolafabio/Hikvision-Addons#31]
Hi there,

Congrats on your work. I have a DS-KV8113-WME1 (V2.2.53 220713) paired with a DS-KH6320-WTE1 and this addon is the only one which works with the KV. I only got one annoying thing going on and was thinking if it would be too hard to get rid of it. Since I have the indoor station as well it keeps on ringing after I open the door using the addon. I see on logs that it finds the "Call dismissed" event thus I was wondering if you could add a command for it, which should do the job of canceling the ringing. 

All the best.

**Comment by pergolafabio** [comment]
hi,  i can add a sensor for call dismissed, but it doesnt stop the call
You can however, send an ISAPI command when door is unlocked, there is a callsignal ISAPI command, look at the forums, it was posted before

**Comment by pergolafabio** [comment]
dimiss sensor coming soo

also the callsignal command is coming :-)

**Comment by vavsaftoiu** [comment]
Wow, many thanks.

**Comment by pergolafabio** [comment]
It's been added yesterday , but you need to remove the old addon, and reinstall again, seems I had a type error in folder name

Config is also easier now , no bearer and url_states needed anymore

**Comment by pergolafabio** [comment]
With the new addon I have added an option to specify the indoor IP... We need to send the dismiss/reject to the indoor station, it's all in the readme

**Comment by vavsaftoiu** [comment]
Great, will update it later today. I'll also help with my current Node Red setup with Android notifications so that I give back something. I'm not using Hikconnect anymore since they are so bad with privacy, thus your addon is the only which works for me. Regards

**Comment by vavsaftoiu** [comment]
I've tried them all, stupid errors and lots of configuration, hard external access. I managed to get PBX in a good shape with two working extensions (two phones), external access (https on PBX HA), could call the Indoor station and pick up but the Outdoor station failed. I also tried the new addon from AlexxIT go2rtc and that almost works with my other cameras(also Hikvision) but not with the  Outdoor Station. I also have BlueIris which in theory should do bidirectional but fails on output. Only thing which works is IVMS4500 on Android (no need for HikConnect) and IVMS4200 on Windows.  It is clear that ISAPI is not working for my station, most probably because of the firmware. Will see.

**Comment by pergolafabio** [comment]
What outdoor station do you have?

**Comment by vavsaftoiu** [comment]
DS-KV8113-WME1 (V2.2.53 220713) paired with a DS-KH6320-WTE1

**Comment by pergolafabio** [comment]
Idapi works on all hikvision devices... But all cameras apps, also Blueiris are using rtsp back channel or onvif , that's something not supported on Hikvision...

Only Synology is able to use idapi, they developed it...

As for PBX , you can register asterisk as a trunk on your indoor station as an extension, that will forward the call to asterisk, and then use a Lovelace sip card to pick up...
The video will be feed from rtsp

**Comment by vavsaftoiu** [comment]
thanks for info. I tried the PBX extension as a trunk but after the update where you didn't need the second PBX server I couldn't make it work.

**Comment by pergolafabio** [comment]
Yeah, seems indeed with some indoor stations, you need to send the regxml part, if you want I can upload the addon again with opensips...

Or you can use the register script that will make the register happen, and the invite will be send to asterisk

**Comment by vavsaftoiu** [comment]
Hi, 

Thanks a lot for your time and help. I might give it another try with the additional info.
