### ISSUE TITLE
Upgrade error

### ISSUE THREAD

**Issue by rjmontenegro** [pergolafabio/Hikvision-Addons#32]
Hello good day.
First of all, thanks for the add-on that I've been using for a long time, https://github.com/pergolafabio/Hikvision-Addons/tree/main/hikvision-sdk.
Now I saw that there was an update but I thought it was strange because the current version is 4.1 and the new one is 1.5. And yet?
I tried to update but I'm getting this error:
![image](https://user-images.githubusercontent.com/6449156/203022418-82459863-9692-4f5e-bc69-265e94634004.png)
Any tips?
Thanks

**Comment by pergolafabio** [comment]
yeah, i made an type error in the folder on github
just remove/complete uninstall old version, then install again
do a refresh of your addons too

**Comment by rjmontenegro** [comment]
Thanks
