### ISSUE TITLE
hikvision_door entity stopped working

### ISSUE THREAD

**Issue by fabianbonte** [pergolafabio/Hikvision-Addons#33]
Hey Fabio, you have any idea to why my hikvision_door entity stopped working? 
I think it started after an (auto) update to the latest version, I saw in your description that a user id and time are presented as well now
But where do this extra attributes come from if the template sensor is declared as bool? (on/off), could it be that, that is where the problem lies?

**Comment by pergolafabio** [comment]
no, those timestamsp are just for logging , nothing todo with the entity
i indeed created a new version, i have made a type error in the foldername on github
best to complete uninstall the addon and remove , then do a refresh and install new version

normally nothing changed in code, s should still work, just added some additional sensors and callsignal command
