### ISSUE TITLE
Cannot build aarch64 image

### ISSUE THREAD

**Issue by dgaus** [pergolafabio/Hikvision-Addons#34]
Hi, I saw you uploaded an aarch64 image and wanted to try it out, however it's failing to build. The output is

```
rock64:hikvision-sdk-aarch64:% docker build .                                                                                                                                                                                        <main>
Sending build context to Docker daemon  29.31MB
Step 1/7 : FROM openeuler/openeuler
 ---> ca894bc0249e
Step 2/7 : RUN yum -y install python-pip
 ---> Running in 23b8acea0492
OS                                              2.4 kB/s | 2.2 MB     16:07
Errors during downloading metadata for repository 'OS':
  - Curl error (28): Timeout was reached for http://repo.openeuler.org/openEuler-22.09/OS/aarch64/repodata/45ae80d99816da5dfd71e925f5c92204420897b4b57d648a1ff8c6a9e85f0287-primary.xml.gz [Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds]
  - Curl error (28): Timeout was reached for http://repo.openeuler.org/openEuler-22.09/OS/aarch64/repodata/bcdd920214ddabc90024f4636668569fd8b3990dafe897d8686d456c5bfa6581-filelists.xml.gz [Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds]
  - Curl error (18): Transferred a partial file for http://repo.openeuler.org/openEuler-22.09/OS/aarch64/repodata/bcdd920214ddabc90024f4636668569fd8b3990dafe897d8686d456c5bfa6581-filelists.xml.gz [transfer closed with 1162825 bytes remaining to read]
Error: Failed to download metadata for repo 'OS': Yum repo downloading error: Downloading error(s): repodata/bcdd920214ddabc90024f4636668569fd8b3990dafe897d8686d456c5bfa6581-filelists.xml.gz - Cannot download, all mirrors were already tried without success
The command '/bin/sh -c yum -y install python-pip' returned a non-zero code: 1
```

Thanks

**Comment by pergolafabio** [comment]
Hmm , looks like somekind of issue with Internet? Or that the mirror site is down from openeuler? I have feedback from other people that it worked...

Maybe try again tomorrow?

**Comment by dgaus** [comment]
My network seems fine, I tried building this on my macbook and it also times out. Is there any reason why you chose openeuler for this base image instead of python3?

**Comment by pergolafabio** [comment]
Yes, the SDK supplied on that folder is a non official release, they only use it internall... I was told it only works on Huawei OS ...I tried other systems already, but then there is error 29 on login... This one was the first one I found that worked...

Maybe you can try changing to harmony OS?

**Comment by pergolafabio** [comment]
Can you try forking my project, and then just change it to harmony OS on your own GitHub? I think the issue is related to openeuler, and just a temp issue?

Sure you have enough disk space?

**Comment by dgaus** [comment]
It seems it was just a network issue, I tried again today and it installed correctly. Seems to be connected now and downloading events, sorry for the premature ticket. Anyway let me know if you would like me to test anything, thanks.

**Comment by pergolafabio** [comment]
Ah, cool, thnx for feedback :+)
