### ISSUE TITLE
docker use.

### ISSUE THREAD

**Issue by Anzic23** [pergolafabio/Hikvision-Addons#35]
How can I run this addon with a docker container? I saw issy #23, but I didn't understand how to repeat that :(.

**Comment by pergolafabio** [comment]
You can't run it as an docker container,  HA is passing data like the IP an the password to the container, so the container is expecting data to run the script....

You need to modify it and pass it somehow or hardcoded in the script

**Comment by pergolafabio** [comment]
Here is something helpful

https://community.home-assistant.io/t/ds-kd8003-ds-kv8113-ds-kv8213-ds-kv6113-ds-kv8413-and-integration-hikvision-hikconnect-video-intercom-doorbell/238535/2210
