### ISSUE TITLE
Rpi4 - non 64 bit

### ISSUE THREAD

**Issue by zsbagyura** [pergolafabio/Hikvision-Addons#36]
Hi, I would like to try the Hikvision SDK for Door Intercoms but I user 32 bit respbian on rpi4. Do you have it for non-64 bit ARM as well?
Thanks in advance

**Comment by pergolafabio** [comment]
For RPI? No , I only received the aarch64

The only 32  bits you can download are for Linux or windows with x86

**Comment by zsbagyura** [comment]
Ok, thanks. I will have to change the OS on the pi!

BW

**Comment by pergolafabio** [comment]
yeah, the SDK i received for RPI was by luck, it was an internal release, not even offcially supported...
but it works :-), confirmed by other users running aarch64

**Comment by zsbagyura** [comment]
I've tried to istall QUEMU (https://www.qemu.org/), and compiled the  64 bit version...
when I try to run it I get: NET_DVR_Login_V30 failed, error code = 29

Maybe you have and idea what does it mean?

**Comment by pergolafabio** [comment]
Yeah, that will not work, been there done that :-)
Error 29 , means not supported OS


The SDK is verry limited, is only compiled for specific OS, the aarch64 edition was for internal release only, and only works on Euler or harmony OS, that's why I had to choose to run docker on EulerOS... 

Otherwise it was easier, I never had to make an addon and run it directly on Alpine

**Comment by pergolafabio** [comment]
Can you specify the OS too with qemu? If yes, try to run openeuler OS

**Comment by zsbagyura** [comment]
Interesting, but the amd64 version is ok, I was able to start it. So, what I did on my rp4 with raspbian 32 bit:
- run: sudo apt-get install qemu binfmt-support qemu-user-static
- added:  platform: linux/amd64 to the docker-compose.yml I use
- run: docker compose 
build

Sometimes it just does not start (NET_DVR_Login_V30 failed, error code = 9), but restart solves the issue.

**Comment by pergolafabio** [comment]
Hmm, error 9 means : failed to retrieve data?
Is it the first time you use addon? I know from other people, when they start first time, it downloads a huge backlog data... Once done, it's all good

**Comment by pergolafabio** [comment]
But the add-ons I created are meant for Home Assistant, because there are options to pass data to the container in the options..
How do you pass date to the docker? Like the IP / username/ password?

**Comment by zsbagyura** [comment]
Actually I don't use your addon as I use openhab.  I tried to use  the sdk with mqtt with this: https://github.com/psy0rz/hikvision-intercom-mqtt I just found that you have the SDK for arm here, that's why I asked for the 32 bit version. ... Than I read on a forum that you had similar problem with the error code 29 that's why I ased again... sorry...

Anyway, I think the information that  raspbian with 32 bit os can run the sdk with this trick is useful for anybody...

**Comment by pergolafabio** [comment]
Ah, ok, that makes sense:-)

Thnx for sharing, it's indeed based on same code

**Comment by pergolafabio** [comment]
But for home assistant users , I don't think it's needed, I don't think there is an HassOS that runs on 32 bit...

But again, I was very lucky to receive an SDK for aarch64, you won't find it anywhere else :+)

Allthough I don't use it, I just sharing it:+)

**Comment by zsbagyura** [comment]
Unfortunately something is not ok. Even it seems that it connects nothing happens when I ring the bell. 

I read messages like this in the docker logs:
loop[2] find 2 mac and 0 ip
Connected!

But nothing else. Maybe my device is not spupported I dont know as it is DS-KIS703-P and I can reach only the indoor unit trough wifi.

**Comment by pergolafabio** [comment]
maybe try this, enable the call linkage on your indoor, this will trigger an relay on your indoor when somepress the button
maybe then  you see event in the SDK? allthough not sure, if input/output are enabled in the script, maybe it needs to be added

![image](https://user-images.githubusercontent.com/43251136/215809487-d1bf2ca2-1e07-42ee-9eee-3c1b3ac41551.png)

**Comment by pergolafabio** [comment]
what do you want to acrhieve, just a call sensor?

**Comment by zsbagyura** [comment]
Oh, that's a pity...for me there is no option for call linkage (se below).
Yes. I want just a call sensor.

[image: image.png]

pergolafabio ***@***.***> ezt írta (időpont: 2023. jan. 31.,
K, 16:52):

**Comment by pergolafabio** [comment]
well, 2 options if you dont have access to outdoor
1) use the hikconnect cloud integration
2) SIP approach, if you dont want a full asterisk server, i have a simple sip script that will register on your indoor ( it acts as an indoor extensions) and it can retrieve the invite events ... then you can trigger what you want a mqtt or rest api
All described here: https://github.com/pergolafabio/Hikvision-Addons/tree/main/hikvision-baresip

**Comment by pergolafabio** [comment]
script based on sip register : https://gist.github.com/pergolafabio/9964ff2c2750fba447c5ca63382f4600
