### ISSUE TITLE
error code = 153

### ISSUE THREAD

**Issue by taanczos** [pergolafabio/Hikvision-Addons#37]
I have a ds-kv6113-wpe1(c) with V2.2.57 build230110 firmware. When I try to start your add-on, it run out to this error:
I have only the door unit, so I just set up the ip, and I leave ip_indoor blank. The IP address and user/passw are correct, checked many times.

Using OS: Linux with architecture: x86_64
01/30/2023, 20:51:10 Hikvision SDK Add-on started! Listening for events...
loop[2] find 8 mac and 16 ip
NET_DVR_Login_V30 failed, error code = 153

Any idea?

Thanks!

**Comment by pergolafabio** [comment]
Are you using the correct password? Error 153 means incorrect password or too many attemps

**Comment by taanczos** [comment]
Yes, I'm using the correct password. I checked it many times.
I tried the pw with some curl too, and it worked, so not my special caracters cause the error.
do you know maybe how many concurrent connection the doorbell can handle?
I record it with nvr, with the same user. And it is not possible to add more user. :/

**Comment by pergolafabio** [comment]
Hmm, not sure about how many users :-(

**Comment by pergolafabio** [comment]
Maybe try rebooting the device and stop your NVR as a test?

**Comment by taanczos** [comment]
I've just restarted the doorbell (power cycle) and now it seems working. Befor I onmly did software restart.
The addon log shows the past events too.
The only thing missing is the sensors not changing state, I can only see the events in the add-on log.

**Comment by pergolafabio** [comment]
Ahh thats good :+)
Sensor is only on for 2 sec

**Comment by pergolafabio** [comment]
But wait, it's downloading a huge backlog, let it settle
