### ISSUE TITLE
Provide more useful messages for Hikvision error codes

### ISSUE THREAD

**Issue by mion00** [pergolafabio/Hikvision-Addons#41]
Right now in case of error we output directly the code provided by the SDK `HCNetSDK.NET_DVR_GetLastError()`.
What if we parse this error and provide a more user-friendly version in output? For instance code `7` (IMO) means device is not reachable, so we could write that in the log to inform the user, instructing it to check for instance the `ip` configuration option.

I don't know if there are any Python libraries that already provide this information for us, without having to manually build a map from sdk_error_code => user_message.

**Comment by pergolafabio** [comment]
Indeed a great idea! This week I had some users reporting the addon was not able to start anymore, seems python updated to 3.10.9 and not compatible anymore... Better logging is indeed an improvement...
There is no libabry in python, my addon was based on someone else script, he created it from scratch...

The error codes, like error 7, I have a list of them

**Comment by pergolafabio** [comment]
https://open.hikvision.com/hardware/definitions/NET_DVR_GetErrorMsg.html

**Comment by mion00** [comment]
Already in `dev`, implemented in b380de5

**Comment by pergolafabio** [comment]
ah, i tought it would provide better output, like 1 = user/pass wrong , 153 = locked...

Now i saw this in his log?

```
[2023-03-02 10:56:55.187][INF] CSSLTrans::SSLCtxInit, dwSSLVersion[0], m_fnClientMethodV23
Traceback (most recent call last):
File "/app/main.py", line 85, in
asyncio.run(main())
File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
return future.result()
File "/app/main.py", line 40, in main
doorbell.authenticate()
File "/app/doorbell.py", line 56, in authenticate
raise RuntimeError(f"SDK error code {self._sdk.NET_DVR_GetLastError()}")
RuntimeError: SDK error code 1
```

**Comment by mion00** [comment]
Yeah it should, the SDKError class automatically extract the error message.

https://github.com/pergolafabio/Hikvision-Addons/blob/c246213aeda1ec6b728797ccc4210d85fd7d50c2/hikvision-doorbell/src/sdk/utils.py#L108-L121

Are you running the latest version?

**Comment by pergolafabio** [comment]
No, i didt copy/paste the log from my addon, but from issue : https://github.com/pergolafabio/Hikvision-Addons/issues/74

Not sure what version he is running

**Comment by pergolafabio** [comment]
so probably already ok then :-)

**Comment by pergolafabio** [comment]
indeed, just tested, see it correct when i input wrong user/password
