### ISSUE TITLE
Use addon as docker container

### ISSUE THREAD

**Issue by mion00** [pergolafabio/Hikvision-Addons#46]
As was already requested in #23 #35, it could be useful to use this the addon as a standalone docker container, for installations without the HA _supervisor_.
This issues provides an overview to track the implementation changes. There are some initial requirements:

- [ ] Read configuration from environment variables (or via a user-mounted file?)
- [ ] Communicate to HA from a external container to the main instance
  - [ ] Need to configure url to reach instance

**Comment by pergolafabio** [comment]
Added in beta
