### ISSUE TITLE
ds-kv8113-wme1 doesnt end call

### ISSUE THREAD

**Issue by Rubiolaso** [pergolafabio/Hikvision-Addons#49]
Hello, 
I have a ds-kv8113-wme1 calling a Dahua VTH via SIP, when i try to end the call like documentation the log return me this 
Trying reject the call... Stdin message: reject
Inputbuffer: {"CallSignal":{"cmdType":"reject"}}
Response buffer: 
Response output: {
	"requestURL":	"/ISAPI/VideoIntercom/callSignal",
	"statusCode":	1,
	"statusString":	"OK",
	"subStatusCode":	"ok"
}
but the call doesn't stop.

This is my configuration
ip: 192.168.2.233
ip_indoor: 192.168.2.233
username: admin
password: *********
sensor_door: hikvision_door
sensor_callstatus: hikvision_callstatus
sensor_motion: hikvision_motion
sensor_tamper: hikvision_tamper
sensor_dismiss: hikvision_dismiss

and this is the service called to stop the call

service: hassio.addon_stdin
data:
  addon: aff2db71_hikvision_sdk
  input: reject

the addon field is correct
HA running in a virtualmachine in a server
Addon Hikvision-SDK
The addon works detecting whenever someone calls

**Comment by pergolafabio** [comment]
My guess it doesnt work SIP, only when using propertiary protocol
Whats your PBX? Asterisk? i think you need to use Asterisk then to stop the channel

**Comment by Rubiolaso** [comment]
The SIP server is a dahua VTO already working, no Asterisk or PBX in the instalation. Maybe doesn't work on SIP.

**Comment by pergolafabio** [comment]
can you do a test for me? You can also send commands with curl

what i do, i send this with curl:

 "PUT /ISAPI/VideoIntercom/callSignal?format=json"

can you test in SSH first sending this command:

"DELETE"  "/ISAPI/VideoIntercom/ring"

and afterwards the callsignal (reject)

only send offcourse when its actually ringing, both command should give a  200 response

**Comment by pergolafabio** [comment]
So first:

`curl -i --digest -u admin:xxx -X DELETE http://192.168.0.70/ISAPI/VideoIntercom/ring`

then:

`curl -i --digest -u admin:xxxx  -d '{"CallSignal":{"cmdType":"reject"}}' -H "Content-Type: application/json" -X PUT http://192.168.0.70/ISAPI/VideoIntercom/callSignal?format=json`

**Comment by Rubiolaso** [comment]
Same response, addon working as intended. Just can't end the call for some reason

**Comment by Rubiolaso** [comment]
![image](https://user-images.githubusercontent.com/103433137/217844621-45182457-a839-4b67-aadf-c293277b38f7.png)

**Comment by pergolafabio** [comment]
en sending the DELETE first  while ringing? and then the reject? do both commands give 200 status?

**Comment by Rubiolaso** [comment]
wait, didnt send the delete first. Give me a minute

**Comment by Rubiolaso** [comment]
![image](https://user-images.githubusercontent.com/103433137/217846027-cf05bf75-d929-4417-a289-a65fcac271da.png)
Both commands ok, the calling still ringing

**Comment by pergolafabio** [comment]
you have a type error in first command! :-)

its "ring" not "ringn"

**Comment by Rubiolaso** [comment]
fuck, i just copied. lets try again

**Comment by Rubiolaso** [comment]
![image](https://user-images.githubusercontent.com/103433137/217847513-187b72ac-0184-4af7-82f2-e7ebbd037778.png)
Still ringing

**Comment by pergolafabio** [comment]
yeah thought so, i dont think it will work when using SIP :-(
i think you need to look if you can use the Dahua to reject something? 

I have an ds-kd8003 , i also need to send the callsignal to the indoor station, not outdoor

**Comment by pergolafabio** [comment]
Or setup an Asterisk maybe between? there you can reject also

**Comment by pergolafabio** [comment]
np, sorry i was not able to help

what device do you have btw? You know Hikvision runs a SIP propertiary protocol to register their indoor stations on...
What you can do, do it the other way around, now tou are registering hikvision on your dahua right?

Register your dahua on Hikvision so it acts as an indoor station, use as username : 10010110001

Use the Ip of your doorstation to register on, the port is 5065  !! not 5060

not sure if audio/video works, but its worth a try
