### ISSUE TITLE
How to install samp addon? Where is the link to it?

### ISSUE THREAD

**Issue by TokarevSergey** [pergolafabio/Hikvision-Addons#6]
How to install samp addon? Where is the link to it?

**Comment by pergolafabio** [comment]
What is a samp addon?

**Comment by TokarevSergey** [comment]
> 
Please tell me how to get a link to the Home Assistant Add-on: "Register Openips/PBX as extension on your indoor panel"?
How do I install it in Home Assistant?

**Comment by TokarevSergey** [comment]
How to install the Home Assistant Add-on Openips/PBX?

**Comment by TokarevSergey** [comment]
Get started
Open your Home Assistant instance and add an custom repositoryfor your add-ons: [https://github.com/](https://github.com/pergolafabio/Hikvision-SDK-Addon)............????

**Comment by pergolafabio** [comment]
Yes, you need to add the GitHub link as a custom repository in your HA addons

**Comment by TokarevSergey** [comment]
> 

Yes, what link? You didn't provide a link.
Please link to Home Assistant Add-on: Register Openips/PBX as extension on your indoor panel

**Comment by pergolafabio** [comment]
its also not an integration, its an add-on , there is no relationship to HACS
you need to add it as a custom repository on your addons page , not on the hacs page

**Comment by TokarevSergey** [comment]
Does not work
Unknown error, see supervisor logs

**Comment by pergolafabio** [comment]
sorry, dont know, it works for me as well for others too
what error you do have on supervisior logs?
