### ISSUE TITLE
Doorbell name in input command

### ISSUE THREAD

**Issue by mion00** [pergolafabio/Hikvision-Addons#61]
Given that there could be multiple doorbells, modify the way we treat incoming commands to include the doorbell `name` we are referring to. Use the doorbell `name` specified by the user in the config.

Example input command:
```
unlock main entrance door1
```
To unlock `door1` on the doorbell named `main entrance`.

Questions:
- What if the name contains some spaces? Should we "sanitize" the name with underscore and lowercase? Otherwise parsing the input string will become troublesome if it is an arbitrary name.
For instance use `main_entrance` to refer to a doorbell named `Main Entrance`

**Comment by pergolafabio** [comment]
Added in beta
