### ISSUE TITLE
Inputs AI1-4 (Alarm in) in Home Assistant

### ISSUE THREAD

**Issue by bladika** [pergolafabio/Hikvision-Addons#64]
Please include (if possible) in Home Assistant alarm inputs of Hikvision DS-KV8x13.
Alarm inputs are for door contacts and exit buttons.
AI1 & 2 = Door contact -> if implemented as a sensor, no need of additional door sensor
AI3 & 4 = Exit button -> actual "hikvison_door" sensor in home assistant is not triggered if door opened by exit button via AI3 or 4 -> if therefore automatons based on "hikvison_door" will not trigger -> if implemented automation can be extended with that new sensor

Thank you!

**Comment by pergolafabio** [comment]
Hey, yes more events are indeed coming, keep an eye on upcoming releases...

What is actually an exit button? How can you trigger it?

**Comment by bladika** [comment]
This sounds good! Looking forward.

Exit button: purpose is to open the door with the press of an external button. You press it and it opens the door. e.g mounted inside the house.
In my case through those inputs I connected an additional devices, pinpad and the output of control board of may electric gate (for cars). Therefore if the trigger of IN3 & IN4 would appears in HA, I could make automations if the gates were opened regardless of the source (pin pad, RF remote of electric gate etc)

I hope I could explain, if not please let me know.

**Comment by pergolafabio** [comment]
ok, makes sense 

lets wait for new version to come out to see more events

**Comment by bladika** [comment]
Do you have an estimation of release date?

**Comment by pergolafabio** [comment]
If you want to test, download the refactor branch, and load it as a local addon, then you have the new version (untested)

**Comment by pergolafabio** [comment]
Hi, wait a bit, a beta release will come soon, it will pop-up in the add-ons

**Comment by pergolafabio** [comment]
Hi, beta released , can you test and have a look at the events in log , what do you see now?

**Comment by bladika** [comment]
Hi, tested AI3/4 (exit button input) -> Both AI3/4 I triggered (pulled to ground and doorbell reacted on them), but nothing in HA log related to that. 

Log:
"[2023-02-25 11:43:01.416][DBG] Alarm chan [0] recv timeout[2]!
[2023-02-25 11:43:31.450][DBG] Alarm chan [0] recv timeout[2]!
[2023-02-25 11:44:01.488][DBG] Alarm chan [0] recv timeout[2]!"

Log settings I used:
"log_level: DEBUG
sdk_log_level: DEBUG"

AI1/2 (door contacts) I cannot test right now -> I have to disassemble gate electronics to do so (and its raining)

**Comment by pergolafabio** [comment]
Hmm, not sure if it will work then, I tested my indoor, there are also 2 IO relays, they didnt create an event either....

Do you think it will work @mion00 ?

**Comment by pergolafabio** [comment]
Question, in ivms4200, if you trigger those relays, do you see the event there? Ivms is also using SDK, then in theory it should work...

Maybe it's just another module in the SDK that's needed, like for alarm panels

**Comment by mion00** [comment]
Hi. If I understood correctly in your setup the Alarm IN relays trigger the OUTPUT relays of the outdoor station?
As @pergolafabio said, do you have any indoor unit or Hikvision application that can trigger those same OUTPUT relays manually? This way we can check if we are talking about the same IN/OUT relays. :wink: 
I found this schema. Does it sound familiar to what you are referring to?
![Screenshot from 2023-02-25 12-42-02](https://user-images.githubusercontent.com/4510647/221354992-dbaecc54-92d6-4620-81b9-55147ec20b34.png)

**Comment by pergolafabio** [comment]
Yeah, I think those relays are also possible with SDK, but we need to focus on alarm IO , it's also in the SDK docs...

**Comment by bladika** [comment]
Yes that semantic is correct.
I can trigger those two relays by:
a., Hik-Connect app
b., assio.addon_stdin
c., AI3 and AI4

The difference is triggering by a. or b. “binary_sensor.door_bell_door” also triggered (kind of door bell reports back)
but with option c., “binary_sensor.door_bell_door” is not triggered. Nothing appeared in log actually.

**Comment by mion00** [comment]
> Yeah, I think those relays are also possible with SDK, but we need to focus on alarm IO , it's also in the SDK docs...

I am not very familiar still with the complete SDK. Do you have by any chance a link to the relevant documentation?

**Comment by pergolafabio** [comment]
Will have a look later...
I also believe someone created an integration with SDK for alarm panels, need to look if I can find it on forums

Not sure if it was based in SDK or ISAPi

**Comment by pergolafabio** [comment]
Hey @bladika , can you try ISAPi commands below? If those work, they can easily added in the addon, ISAPi is already used for reject command...

https://community.home-assistant.io/t/integration-with-hikvision-ax-pro-alarm-system/308319/16

**Comment by pergolafabio** [comment]
Hey @Supergiovane , can you provide some feedback? You are more aware of other hardware

**Comment by Supergiovane** [comment]
Hi Fabio
node-red-contrib-hikvision-ultimate for nodered does have an AX Pro Alarm node, that uses ISAPI for everything. 
Feel free to take a look at the code.

**Comment by bladika** [comment]
Checked AI1 & 2. Situation is the same, nothing in log. 
ISAPI I will try later when I’m home

**Comment by bladika** [comment]
@pergolafabio please guide me what to exactly do with ISAPI.
What to copy where? What to check?

**Comment by pergolafabio** [comment]
Hey , try these isapi commands
https://tpp.hikvision.com/Wiki/ISAPI/Access%20Control%20on%20Person/GUID-C77BDBF6-2EC7-4CCC-AC4E-CFFEAE425089.html

How to triggger... Use my examples that I provided here:
`
curl -i --digest -u admin:xxx http://192.168.0.x/ISAPI/VideoIntercom/callStatus?format=json
curl -i --digest -u admin:xxx -X PUT -d '<RemoteControlDoor><cmd>open</cmd></RemoteControlDoor>' http://192.168.0.x/ISAPI/AccessControl/RemoteControl/door/1
curl -i --digest -u admin:xxx -X PUT -d '' http://192.168.0.x/ISAPI/System/reboot
curl -i --digest -u admin:xxx  -d '{"CallSignal":{"cmdType":"reject"}}' -H "Content-Type: application/json" -X PUT http://192.168.0.x/ISAPI/VideoIntercom/callSignal?format=json
# Two Way Audio:
curl -i --digest -u admin:xxx -X PUT http://192.168.0.x/ISAPI/System/TwoWayAudio/channels/1/open
curl -i --digest -u admin:xxx http://192.168.0.x/ISAPI/System/TwoWayAudio/channels/1/audioData
curl -i --digest -u admin:xxx -X PUT -d '' http://192.168.0.x/ISAPI/System/TwoWayAudio/channels/1/audioData
curl -i --digest -u admin:xxx -X PUT  http://192.168.0.x/ISAPI/System/TwoWayAudio/channels/1/close
`

**Comment by pergolafabio** [comment]
Just want to know if we are able to see the IO with ISAPi so we need to know where to look in the SDK

**Comment by pergolafabio** [comment]
Can you also look in ivms 4200 if you see events there of the AI relays?

**Comment by bladika** [comment]
No luck with ISAPI or ivms.  This is the only command I could get response " curl -i --digest -u admin:xxx http://192.168.0.x/ISAPI/VideoIntercom/callStatus?format=json"

However:
- Under [https://tpp.hikvision.com/Wiki/ISAPI/Access%20Control%20on%20Person/GUID-3DA08C41-78D4-41C4-A22C-5B0B57D23C15.html?hl=event_acs_door_button_press](url)
EVENT_ACS_DOOR_BUTTON_PRESS, EVENT_ACS_DOOR_BUTTON_RELEASE, EVENT_ACS_DOOR_OPEN_NORMAL, EVENT_ACS_DOOR_CLOSE_NORMAL those seems to me the events which we are elooking for.

- small step w/ AI1/2 (door contacts). I found out, it is not enough to turn on the contact inputs in doorbell config, but there is a separate setting to turn on alarm notification. Today tested again with the mentioned alarm enabled and if I trigger AI1 or AI2 then I can see in log the following:
2023-02-26 14:09:57.269 | DEBUG    | event:_handle_callback:169 - Callback invoked from SDK
2023-02-26 14:09:57.270 | DEBUG    | event:_invoke_handlers:145 - Invoking 2 handlers
2023-02-26 14:09:57.270 | INFO     | home_assistant:video_intercom_alarm:172 - Door not closed alarm
2023-02-26 14:09:57.270 | INFO     | event:video_intercom_alarm:99 - Video intercom alarm from Kaputelefon
[2023-02-26 14:09:57.269][INF] Alarm[0] IP[192.168.10.33] data_len[568] alarm_len[568] status[430]

[2023-02-26 14:10:18.793][DBG] Alarm chan [0] recv timeout[2]!

2023-02-26 14:10:28.426 | DEBUG    | event:_handle_callback:169 - Callback invoked from SDK
2023-02-26 14:10:28.427 | DEBUG    | event:_invoke_handlers:145 - Invoking 2 handlers
2023-02-26 14:10:28.428 | INFO     | home_assistant:video_intercom_alarm:172 - Door not closed alarm
2023-02-26 14:10:28.428 | INFO     | event:video_intercom_alarm:99 - Video intercom alarm from Kaputelefon
[2023-02-26 14:10:28.426][INF] Alarm[0] IP[192.168.10.33] data_len[568] alarm_len[568] status[430]

**Comment by pergolafabio** [comment]
What do you mean by : turn on alarm notification?? Is that a setting in ivms?

**Comment by bladika** [comment]
I found it in doorbell's own config page (web browser -> doorbell IP address)
![door event](https://user-images.githubusercontent.com/669628/221413299-98dc7e68-02d6-4b43-85bc-16c6cbe7c2c2.JPG)

**Comment by pergolafabio** [comment]
Ah ok , same setting for motion ... Interesting... Gonna see if I can do that too on my indoor tomorrow

**Comment by pergolafabio** [comment]
Seems those events are indeed already part of our addon...

https://github.com/pergolafabio/Hikvision-Addons/blob/eb0a57fbecf6ba39e198eb2dccf5c7aad6e7f3e9/hikvision-sdk/src/hcnetsdk.py#L139

Should be easy then to make another sensor

**Comment by bladika** [comment]
Question if it possible to distinguish which door contact input was triggered.

**Comment by pergolafabio** [comment]
Will have a look tomorrow, but already good news it seems

**Comment by pergolafabio** [comment]
hi, had a quick look, it should be visible, its the same event when door was open, then we also see the door relay id, and in HA its visbible as an attribute

look below, for event 5 or 6, the lockid is also valid

@mion00 , what do you think? create an extra binary sensor like we do with the door? and then use attributes?
```

byAlarmType
Alarm type: 1-zone alarm, 2-tampering alarm, 3-duress alarm, 4-opening door by password failed for multiple times, 5-opening door failed, 6-closing door failed, 7-panic alarm), 8-intercom alarm, 9-smart lock: fingerprint duress alarm, 10-smart lock: password duress alarm, 11-smart lock: tampering alarm, 12-smart lock: locked alarm, 13-smart lock: low battery alarm, 14-blocklist alarm, 15-smart lock disconnected, 16-access control module: anti-tampering alarm, 17-video intercom started, 18-video intercom stopped.

byRes1
Reserved, set to 0.

uAlarmInfo
Alarm information, it is valid when byAlarmType equals to 1. Refer to the union [NET_DVR_VIDEO_INTERCOM_ALARM_INFO_UNION](https://github.com/pergolafabio/Hikvision-Addons/issues/GUID-7C171152-5616-4A52-BE0C-97DCAAFF8DDA.html#GUID-7C171152-5616-4A52-BE0C-97DCAAFF8DDA) for details.

wLockID
Lock ID, it is valid when alarm type is 5 or 6. When the ID is 0, it represents the lock of door station, when the ID is 1, it represents the lock of external access control module.
```

**Comment by pergolafabio** [comment]
ah, i see "door not closed" is already part of the beta? do you see that event coming in @bladika 

https://github.com/pergolafabio/Hikvision-Addons/blob/dev/hikvision-doorbell/src/home_assistant.py#L171

**Comment by bladika** [comment]
Below the result w/ the beta version. Log shows the result of triggering both inputs one after the other
[2023-03-01 22:49:32.248][DBG] Alarm chan [0] recv timeout[2]!

2023-03-01 22:49:56.985 | DEBUG    | event:_handle_callback:169 - Callback invoked from SDK
2023-03-01 22:49:56.986 | DEBUG    | event:_invoke_handlers:145 - Invoking 2 handlers
2023-03-01 22:49:56.987 | INFO     | home_assistant:video_intercom_alarm:172 - Door not closed alarm
2023-03-01 22:49:56.987 | INFO     | event:video_intercom_alarm:99 - Video intercom alarm from Kaputelefon
[2023-03-01 22:49:56.985][INF] Alarm[0] IP[192.168.10.33] data_len[568] alarm_len[568] status[430]

[2023-03-01 22:50:02.269][DBG] Alarm chan [0] recv timeout[2]!

2023-03-01 22:50:22.604 | DEBUG    | event:_handle_callback:169 - Callback invoked from SDK
2023-03-01 22:50:22.604 | DEBUG    | event:_invoke_handlers:145 - Invoking 2 handlers
2023-03-01 22:50:22.604 | INFO     | home_assistant:video_intercom_alarm:172 - Door not closed alarm
2023-03-01 22:50:22.605 | INFO     | event:video_intercom_alarm:99 - Video intercom alarm from Kaputelefon
[2023-03-01 22:50:22.604][INF] Alarm[0] IP[192.168.10.33] data_len[568] alarm_len[568] status[430]

[2023-03-01 22:50:32.311][DBG] Alarm chan [0] recv timeout[2]!

What would be nice if can have also a trigger when contact closed again or a simple poll of the status of the input. Currently it works in a way that if contact remains open for a certain time (settings on doorbell config page) then event fires, but it is unknown after if the contact closed or not.

**Comment by bladika** [comment]
I can see there is such thing called "VIDEO_INTERCOM_ALARM_ALARMTYPE_DOOR_NOT_OPEN" in "hcnetsdk.py" which is nowhere implemented and I would assume this is what I described above. 
However even if it is not implemented I should at least see in the log that an unhandled event triggered.
Right?

**Comment by pergolafabio** [comment]
Hi, I see in the code the event "door not closed" ,like  that you indeed see in the log ... "Door not open" is also an event,  but is not defined yet... I think if we can define that one too, then you know the state?

Not sure if polling is possible?  Havent found that command... Also the ID of the relay is possible , same as with the door, we can put that as an attribute...

Maybe to start a new binary_sensor.alarm that can trigger on/of based on door not open/closed with an attribute from the relay id ?

Alltough the state is lost after an HA restart

**Comment by pergolafabio** [comment]
Hi, can you try beta6, created a new alarm sensor, that grabs event door not open or closed, and it uses attributes about the lay id

can you test?

**Comment by bladika** [comment]
Hi, sry for not giving feedback I was sick the last couple of days. I will test it soon

**Comment by pergolafabio** [comment]
When you have time to test, use beta 10, a LOT is changed, all events are now visible, make sure to read the changelog, it's now based on MQTT with the great work of @mion00 !!!!!!!

**Comment by bladika** [comment]
Hi,
First of all thank you for the new release and your efforts!
So finally tested w/ 3.0.0-beta.13.
Triggered AI1 & AI2 one by one.
Observation:
- when contact closed -> nothing in log
- when contact opened -> appears in log, however the two inputs are not distinguished (both lands on "door 0"

[2023-03-12 00:19:31.472][DBG] Alarm chan [0] recv timeout[2]!

2023-03-12 00:19:37.916 | DEBUG    | event:_handle_callback:192 - Callback invoked from SDK
2023-03-12 00:19:37.917 | DEBUG    | event:_invoke_handlers:166 - Invoking 2 handlers
2023-03-12 00:19:37.918 | INFO     | event:video_intercom_alarm:109 - Video intercom alarm from Kaputelefon
2023-03-12 00:19:37.918 | INFO     | mqtt:video_intercom_alarm:246 - Alarm <sdk.hcnetsdk.LP_NET_DVR_VIDEO_INTERCOM_ALARM_INFO_UNION object at 0x7f4b02bd1940> detected on door 0
2023-03-12 00:19:37.918 | DEBUG    | mqtt:handle_device_trigger:298 - Invoking device trigger {'name': 'door_not_closed_0', 'type': 'not closed', 'subtype': 'Door 1'}
[2023-03-12 00:19:37.916][INF] Alarm[0] IP[192.168.10.33] data_len[568] alarm_len[568] status[430]

[2023-03-12 00:20:01.503][DBG] Alarm chan [0] recv timeout[2]!

2023-03-12 00:20:05.871 | DEBUG    | event:_handle_callback:192 - Callback invoked from SDK
2023-03-12 00:20:05.872 | DEBUG    | event:_invoke_handlers:166 - Invoking 2 handlers
2023-03-12 00:20:05.872 | INFO     | event:video_intercom_alarm:109 - Video intercom alarm from Kaputelefon
2023-03-12 00:20:05.873 | INFO     | mqtt:video_intercom_alarm:246 - Alarm <sdk.hcnetsdk.LP_NET_DVR_VIDEO_INTERCOM_ALARM_INFO_UNION object at 0x7f4b02bd19c0> detected on door 0
2023-03-12 00:20:05.873 | DEBUG    | mqtt:handle_device_trigger:298 - Invoking device trigger {'name': 'door_not_closed_0', 'type': 'not closed', 'subtype': 'Door 1'}
[2023-03-12 00:20:05.871][INF] Alarm[0] IP[192.168.10.33] data_len[568] alarm_len[568] status[430]

[2023-03-12 00:20:31.543][DBG] Alarm chan [0] recv timeout[2]!

**Comment by pergolafabio** [comment]
Hmm, thnx for feedback, the SDK is listening for both events, is it maybe possible that the "door closed" is not enabled in IVMS? Do you see something there? Can you see if the door ID is also correct in IVMS when "door open" event occurs?

Cause looking in the code, everything should be OK...

```
case VideoInterComAlarmType.DOOR_NOT_OPEN | VideoInterComAlarmType.DOOR_NOT_CLOSED:
                # Get information about the door that caused this alarm
                door_id = alarm_info.wLockID
                logger.info("Alarm {} detected on door {}", alarm_info.uAlarmInfo, door_id)
                
                # Create the key to extract the entity from the `sensors` dict, depending on the alarm type
                # use `subtype` to display doors starting from index 1 in the UI
                if alarm_info.byAlarmType == VIDEO_INTERCOM_ALARM_ALARMTYPE_DOOR_NOT_OPEN:
                    trigger = DeviceTriggerMetadata(name=f"door_not_open_{door_id}", type="not open", subtype=f"Door {door_id+1}")
                else:
                    trigger = DeviceTriggerMetadata(name=f"door_not_closed_{door_id}", type="not closed", subtype=f"Door {door_id+1}")
```

**Comment by pergolafabio** [comment]
In my ivms, i can only enabled event for "door open", "door closed" is not listed there, thats why the event is not coming in my guess?

![image](https://user-images.githubusercontent.com/43251136/224529596-7da9c3ca-29cb-479a-b340-873a87f33cad.png)

**Comment by pergolafabio** [comment]
also try beta 16, added device triggers for Zone alarm for indoor/outdoor

**Comment by giedriuskilcauskas** [comment]
Any chance of getting binary sensor for door opened/closed? Or that's not available in sdk?

**Comment by pergolafabio** [comment]
Hi, that alarm is already included, all events are now device triggers in HA, you can build automations based on those...

Normally you should see it in the addon log, make sure to run the beta addon

**Comment by pepsonEL** [comment]
Hi
If i use alarm input in door station KD8003(B) to connect switch contact ,
how it informed me on indoor LCD  when door will be open ? Show alarm or
what ?

czw., 20 kwi 2023 o 10:16 Pergola Fabio ***@***.***>
napisał(a):

**Comment by pergolafabio** [comment]
Hmm, don't think you can link an alarm input/output from outdoor to indoor...

**Comment by giedriuskilcauskas** [comment]
> Any chance of getting binary sensor for door opened/closed? Or that's not available in sdk?

That one is fine, but it's triggered one way, it's good for some automation to see that gates were left open. I'd prefer to see the status of door sensor as binary in my dashboard (doorbell itself lights and LED when doors are open)

**Comment by pepsonEL** [comment]
No....
Door station has inputs/output... one i use for button exit and one i use
for electric lock.
But one i want use for switch contact.... But i this how it show me info on
INDOOR station that door is still open.

czw., 20 kwi 2023 o 10:22 Pergola Fabio ***@***.***>
napisał(a):

**Comment by pergolafabio** [comment]
Or maybe an mqtt template sensor? That's even better, so you know last state also...

You can check with Mqtt explorer to see all the Mqtt payloads that are available

**Comment by pergolafabio** [comment]
duplicate #95
