### ISSUE TITLE
Build docker images for the addon

### ISSUE THREAD

**Issue by mion00** [pergolafabio/Hikvision-Addons#67]
When a release of the add-on is ready, this repository should provide a Docker image pre-built for both `amd64` and `aarch64` architectures.
This way when users install the add-on in their HA instance they won't have to build the image locally, but instead rely on pre-built and already tested images built automatically by Github CI. This can help avoid unexpected results if the users has some connectivity problems or other issues related to the local build. (see #66 )

**Comment by pergolafabio** [comment]
Added in beta
