### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TokarevSergey** [pergolafabio/Hikvision-Addons#7]
![VirtualBox_HAS_28_03_2022_23_29_58](https://user-images.githubusercontent.com/98225056/160482637-f9e2976c-4af3-40c9-b92d-564ca3f27184.png)

Tell me what am I doing wrong? After running hikvison-opensips, an error appears and homeassistant stops working. Please help?

**Comment by pergolafabio** [comment]
Maybe you are running out of freespace? The addon is rather big

**Comment by TokarevSergey** [comment]
I have a standard 32 gb Oracle VM VirtualBox build. Can you tell me how to see the memory? It's just that as soon as I launch it, I can't go to lovelase.

**Comment by pergolafabio** [comment]
no id , maybe you can ask community forums

**Comment by pergolafabio** [comment]
but the issue is not related to this addon, you have disk errors

**Comment by TokarevSergey** [comment]
Thanks
