### ISSUE TITLE
Beta version no run

### ISSUE THREAD

**Issue by pepsonEL** [pergolafabio/Hikvision-Addons#72]
Hi. I installed version beta 3.00 beta 4 and it no run with my config.

```

doorbells:
  - name: Outdoor
    ip: 192.168.xx.xx
    username: admin
    password: MyPass
  - name: Indoor
    ip: 192.168.xx.xx
    username: admin
    password: MyPass
home_assistant:
  url: http://supervisor/core
system:
  log_level: DEBUG
  sdk_log_level: DEBUG
```

```
2023-02-23 17:40:36.798 | DEBUG    | __main__:main:24 - Importing Hikvision SDK
2023-02-23 17:40:36.801 | INFO     | sdk.utils:loadSDK:44 - Using OS: Linux with architecture: x86_64
2023-02-23 17:40:36.801 | DEBUG    | sdk.utils:loadSDK:57 - Loading library from lib-amd64/libhcnetsdk.so
2023-02-23 17:40:36.823 | DEBUG    | __main__:main:28 - Hikvision SDK loaded
2023-02-23 17:40:36.823 | DEBUG    | sdk.utils:setupSDK:83 - Initializing SDK
loop[2] find 2 mac and 0 ip
[2023-02-23 17:40:36.843][DBG] CCoreGlobalCtrlBase::LoadDSo, HPR_LoadDSo Succ, Path[/lib/x86_64-linux-gnu/libz.so.1.2.11], hHandleRet[73206240]
[2023-02-23 17:40:36.843][INF] The COM:HCCoreBase ver is 6.1.4.15, 2020_03_05. Async:1.
[2023-02-23 17:40:36.843][INF] The COM:Core ver is 6.1.6.45, 2021_03_02. Async:1.
[2023-02-23 17:40:36.843][INF] This HCNetSDK ver is 6.1.6.45 Ver 2021_03_02.
2023-02-23 17:40:36.843 | DEBUG    | sdk.utils:setupSDK:97 - SDK initialized
2023-02-23 17:40:36.843 | DEBUG    | doorbell:__init__:37 - Setting up doorbell: Outdoor
2023-02-23 17:40:36.843 | DEBUG    | doorbell:authenticate:44 - Logging into doorbell
[2023-02-23 17:40:36.843][INF] Login dev 192.168.xx.xx:8000.
[2023-02-23 17:40:36.843][INF] dwTotalNum[2048]
[2023-02-23 17:40:36.844][INF] Private connect 192.168.xx.xx:8000 sock=135 this=0x49c4534 cmd=0x10000 port=52438
[2023-02-23 17:40:36.844][INF] LogonDev1 in[192.168.xx.xx:8000]
[2023-02-23 17:40:36.845][DBG] CCoreGlobalCtrlBase::LoadDSo, HPR_LoadDSo Succ, Path[/app/lib-amd64/libcrypto.so], hHandleRet[77390784]
[2023-02-23 17:40:36.845][DBG] CCoreGlobalCtrlBase::LoadDSo, HPR_LoadDSo Succ, Path[/app/lib-amd64/libssl.so], hHandleRet[77392016]
[2023-02-23 17:40:36.845][INF] SSLTRANSAPI::LoadAPI, libeay, Load Real Path[/app/lib-amd64/libcrypto.so]
[2023-02-23 17:40:36.846][INF] SSLTRANSAPI::LoadAPI, libssl, Load Real Path[/app/lib-amd64/libssl.so]
[2023-02-23 17:40:36.846][INF] SSLTRANSAPI::IsAllAPILoaded, OpenSSL_version Unload
[2023-02-23 17:40:36.846][INF] OpenSSL, Not All Function Loaded!
[2023-02-23 17:40:36.846][INF] SSLTRANSAPI::PrintVersion, SSLeay_version info [OpenSSL 1.0.2t  10 Sep 2019]
[2023-02-23 17:40:36.846][INF] CSSLTrans::SSLCtxInit, dwSSLVersion[0], m_fnClientMethodV23
Traceback (most recent call last):
  File "/app/main.py", line 85, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/main.py", line 40, in main
    doorbell.authenticate()
  File "/app/doorbell.py", line 58, in authenticate
    self._type = DeviceType(self._device_info.wDevType)
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 605 is not a valid DeviceType
[2023-02-23 17:40:37.145][INF] COM_Logout[0][1]
[2023-02-23 17:40:37.154][DBG] CUserMgr::UnRegisterHeartProxy[0]
[2023-02-23 17:40:37.155][INF] Private connect 192.168.xx.xx:8000 sock=3 this=0x49c4534 cmd=0x10100 port=52446
```

**Comment by mion00** [comment]
Hi @pepsonEL. I am sorry to hear that you have encountered this issue. Let me try and find the root cause of the problem.
What model of doorbell are you connecting to? Is it a `Villa VTO` device?

**Comment by pepsonEL** [comment]
It is Villa DS-KV8102IM and indoor DS-KH8301WT

**Comment by mion00** [comment]
Understood thanks! Let me see if I can come up with a quick solution..

**Comment by pepsonEL** [comment]
Thanks i am waiting

**Comment by mion00** [comment]
I just published a fix.
You should be able to immediately apply it by going to `Settings` -> `Add-ons` -> `Add-on Store` -> `Check for updates` (upper right corner), then after some seconds go back to the `Add-ons` page, the add-on should appear with an orange overlay indicating an update available.

**Comment by pepsonEL** [comment]
Ok installed and start test

**Comment by pepsonEL** [comment]
OK when i try call from front door nothing change in binary senosrs Outdoor callstatus, Outdoor dismiss, Outdoor door, Outdoor motion, Outdoor tamper

**Comment by pergolafabio** [comment]
Hi, don't focus on the sensor for now , check the addon log if you see an event

**Comment by pepsonEL** [comment]
logs debug no show any events about call. Where i can share my logs ?

**Comment by pergolafabio** [comment]
If there is no event, then there is nothing to share...

I think it's the end of the road for that old device...
You should use Hikconnect or use my sip register script

**Comment by pepsonEL** [comment]
No good infor for me.... But by cloud it call on my Android phone.

**Comment by pergolafabio** [comment]
Indeed, you are on latest firmware?

Only possible working solution is the Hikconnect or sip script... Or you can remove Hikconnect completely and go fully SIP

**Comment by pepsonEL** [comment]
Yes i have latest FW. 
https://www.hikvisioneurope.com/eu/portal/?dir=portal/Technical%20Materials/07%20%20Video%20Intercom/00%20%20Product%20Firmware/01%20Door%20Station%20%28KD%20KV%20KB%29/KV%20Series/KV8102%20KV8202%20KV8402%20EOL/V1.5.1%20Build%20190613/Version%20A%20-%20EN%20FR%20PT%20ES%20DE%20IT%20CZ%20PL/KV%20Villa%20door%20Station

**Comment by pergolafabio** [comment]
Sorry, we can't do anything more ;-(

**Comment by pepsonEL** [comment]
Ok thanks..... no good.... very bad devices....

**Comment by pergolafabio** [comment]
No, you just have old device :+)

But why not use my sip script, it's easy and you don't need knowledge about sip, you don't need a sip server..

It only act as extension indoor and will update a sensor in HA

**Comment by pepsonEL** [comment]
But how configure it....step by step

**Comment by pergolafabio** [comment]
download this one:

https://gist.github.com/pergolafabio/9964ff2c2750fba447c5ca63382f4600

Then open up your SSH addon and start it with this command, just a test:
in example below 0.17 is the IP of HA, 0.71 is your indoor station, and XXX needs to be changed to your session password
Show me the output, normally you should see a register state ... then try pressing the doorbutton, then you should see an invite/ringing state... 

It doesnt update anything in HA yey, just test first below

`python3 hikvision_register.py --ip 192.168.0.17 --domain 192.168.0.71 --username 10000000005 --extension 10000000005 --name Asterisk --password XXX --debug`

**Comment by pepsonEL** [comment]
I use HASSOS... But when i call ring but where on what sensor it show me that ring call ?

**Comment by pergolafabio** [comment]
No sensor yet, look at the output first, step by step...
I want to know if the scripts works on your indoor... Show me the output

**Comment by pepsonEL** [comment]
But it runs on Windows ?

**Comment by pergolafabio** [comment]
Doesn't mather, but best to run it inside the SSH addon that you can access with putty

**Comment by pergolafabio** [comment]
Also change line 69, there is port 5061, change to 5060, otherwise you don't see the invite coming in

**Comment by pergolafabio** [comment]
Do first:

Python3 pip install requests

**Comment by pepsonEL** [comment]
no PIP

**Comment by pergolafabio** [comment]
Then install pip first, no worries, this is just for testintg, not needed when you go live

**Comment by pepsonEL** [comment]
but what command install on HASSOS this PIP ?

**Comment by pergolafabio** [comment]
Gimme 20 min, almost home

**Comment by pergolafabio** [comment]
ok, sorry , forgot the "-m"

![image](https://user-images.githubusercontent.com/43251136/221007350-ed080585-5881-443a-be4d-44556b8d8236.png)

**Comment by pepsonEL** [comment]
![IMG20230223204937](https://user-images.githubusercontent.com/71824185/221015075-c7e7bb2b-e995-4b35-9a63-cd1f9ff05f1b.jpg)

**Comment by pergolafabio** [comment]
GOOD news for you :-)

**Comment by pergolafabio** [comment]
now, do this, drop the debug , no need for it 
instead fill in the bearer token and your HA url including the sensor name  , localhost is fine
sensor.callsensor , this one will be created when invite is received , you can define it in the url below

`python3 hikvision_register.py --ip 192.168.0.17 --domain 192.168.0.71 --username 10000000005 --extension 10000000005 --name Asterisk --password XXX --token YOURBEARERTOKEN --state-url http://localhost:8123/api/states/sensor.callsensor`

**Comment by pergolafabio** [comment]
on invite, it will change to state "ringing"

**Comment by pergolafabio** [comment]
test it first again in putty, if it works, i show you how to automate in in HA

**Comment by pepsonEL** [comment]
ok but how get token YOURBEARERTOKEN ??

**Comment by pergolafabio** [comment]
In HA , go you your profile, then at bottom, you can create a long lived token

**Comment by pergolafabio** [comment]
if this work and and you want to learn SIP, then you can actually use HA Companion as a call app, with Asterisk setup as an indoor station that receives the call

**Comment by pepsonEL** [comment]
Traceback (most recent call last):
  File "/config/hikvision_register.py", line 436, in <module>
    sip_session = SIPSession(options.ip, options.extension, options.domain, options.password, options.username, display_name=options.name)
  File "/config/hikvision_register.py", line 92, in __init__
    self.sipsocket.bind(("0.0.0.0", account_port))
OSError: [Errno 98] Address in use
➜  config

**Comment by pergolafabio** [comment]
ok, then just use the script :-)

**Comment by pepsonEL** [comment]
INFO:sip-server:Registering
INFO:sip-server:OK REGISTER
INFO:sip-server:Received invite (call)
INFO:sip-server:Call ended by caller
INFO:sip-server:Call ended by caller
INFO:sip-server:Call ended by caller
INFO:sip-server:Call ended by caller
INFO:sip-server:Call ended by caller
INFO:sip-server:Call ended by caller
INFO:sip-server:Call ended by caller
INFO:sip-server:Call ended by caller
INFO:sip-server:Call ended by caller
INFO:sip-server:Call ended by caller
INFO:sip-server:Call ended by caller

**Comment by pergolafabio** [comment]
yeah, thats good

**Comment by pergolafabio** [comment]
is the sensor changing?

**Comment by pergolafabio** [comment]
if not, turn on --debug again

**Comment by pepsonEL** [comment]
yes change to ringing then go to registered

**Comment by pergolafabio** [comment]
good!! :-)

**Comment by pergolafabio** [comment]
Now, create a shell command in HA:

https://www.home-assistant.io/integrations/shell_command/

place the script in your config folder, change the script like below, it needs to run in background, make sure to use the correct path... and add those /dev stuff behind it

`hikvision_sip: nohup python3 /config/hikvision_register.py --ip 192.168.0.17 --domain 192.168.0.71 --username 10000000005 --extension 10000000005 --name Asterisk --password XXX --token YOURBEARERTOKEN --state-url http://localhost:8123/api/states/sensor.callsensor $1 > /dev/null 2>&1 &`

Then create an automation that starts the shell command when you start HA

```
# Automation:
- alias: Register hikvision 
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: shell_command.hikvision_sip
```

Done!

**Comment by pergolafabio** [comment]
also restart your SSH addon, to make sure port 5060 is free

**Comment by pepsonEL** [comment]
But you can not implement it to your addon to add support for this my old
device....? I was more friendly for users begginer. It was very friendly.
And also user as i can also use script to open door.

czw., 23 lut 2023, 21:18 użytkownik Pergola Fabio ***@***.***>
napisał:

**Comment by pergolafabio** [comment]
No this script will not be part of the addon, it's used for a complete other purpose, it was not meant be used for events... The purpose of the script is to setup and create an extension... Nothing more nothing less

Once the extension is created on your indoor panel, you can now receive a call to a PBX , from there you can forward call to HA or any other softphone you like...

It's out of scope for this addon

**Comment by pergolafabio** [comment]
To open door you can use the SDK addon if it works or the ISAPi command like in the community thread as a shell command

**Comment by pepsonEL** [comment]
ok. thanks. But for me is to complicated....

**Comment by pergolafabio** [comment]
Why? You have it now running :+)

You now have a working call sensor, that's what you wanted? ;-)

**Comment by pergolafabio** [comment]
Or do you mean the PBX stuff?

**Comment by pepsonEL** [comment]
What is PBX ?

**Comment by pergolafabio** [comment]
A voip server like asterisk

**Comment by pepsonEL** [comment]
ahhhh no i think about addon like this today beta.....

**Comment by pergolafabio** [comment]
Ok, but anyway, you have your local callsensor now...
If you want to learn SIP, start with the Asterisk addon, they have written some nice wiki pages, also a discord channel, start easy , try calling from user to users. if you manage ,then you can start integrating with this script, so you can receive calls and can actually answer with a Lovelace card

**Comment by pepsonEL** [comment]
Good that new version addon is created for new video intercom but no good that it is no working with old model.... Ok thanks for your and other user  hard work.

**Comment by pergolafabio** [comment]
No problem

**Comment by pergolafabio** [comment]
Sorry, we are limited to the SDK supplied by Hikvision, they need to make support for it, nothing we can do about it ;-(

**Comment by pepsonEL** [comment]
But sometime ago probably i talk by email with HikVision and he tell me that SDK support my model. But it looks that no support.
