### ISSUE TITLE
Make the sensor state stay longer on then 1 sec

### ISSUE THREAD

**Issue by pergolafabio** [pergolafabio/Hikvision-Addons#76]
Seems automation doesn't run for a person on forum, cause the state change is too short, maybe it's indeed better to make them longer, also for testing and troubleshooting

**Comment by pergolafabio** [comment]
What do you think @mion00 , make all sensors 5 ? So it's easier for users to see it's changing?

**Comment by mion00** [comment]
Sounds like a plan, I just have some doubts about what happens if there are two consecutive events triggered in a short time frame, say after two/three seconds while the sensor is stil to go back to off state. :thinking:

**Comment by pergolafabio** [comment]
Hmm, the sleep, it will sleep the whole script? Normally they should arrive afterwards? We can test it when we configure 5 ...

**Comment by mion00** [comment]
In theory I make use of asyncio sleep so that another callback function can run at the same time, but it is all to be tested.

**Comment by pergolafabio** [comment]
changed to 5 , we will see how it goes ...
https://github.com/pergolafabio/Hikvision-Addons/commit/bd24e4c6b3c18efb45b36f81afc712b1f96ae723
