### ISSUE TITLE
DS-K1T341M is not a valid device type

### ISSUE THREAD

**Issue by iory123** [pergolafabio/Hikvision-Addons#79]
May help increase this device type, here are the logs:
  | INFO     | sdk.utils:loadSDK:44 - Using OS: Linux with architecture: x86_64
loop[2] find 2 mac and 0 ip
Traceback (most recent call last):
  File "/app/main.py", line 85, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/main.py", line 40, in main
    doorbell.authenticate()
  File "/app/doorbell.py", line 58, in authenticate
    self._type = DeviceType(self._device_info.wDevType)
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 10510 is not a valid DeviceType

**Comment by mion00** [comment]
Thanks for the report! I'll have a look.
Yeah we are slowly getting to know more and more device types from various
users. Otherwise we are pretty limited in our testing abilities given only
the models we have installed locally. 😅

**Comment by pergolafabio** [comment]
Looks a nice device, it can also do face recognition?

**Comment by mion00** [comment]
@pergolafabio I currently take the `device type` from the big table [here](https://open.hikvision.com/hardware/structures/NET_DVR_DEVICEINFO_V30.html), and I see this code is not present.
You don't have any additional reference doc that may help in this case?

**Comment by pergolafabio** [comment]
Let me check tomorrow, not at home today, maybe TPP site have more info

**Comment by iory123** [comment]
> Looks a nice device, it can also do face recognition?

Yes, it's pretty good to use. 

https://www.hikvision.com/en/products/Access-Control-Products/Face-Recognition-Terminals/Value-Series/ds-k1t341am/

**Comment by pergolafabio** [comment]
Hey, seems TPP is even more behind , no update , keep an eye on it

anway, added FaceAccessTerminal, will update beta soon

https://github.com/pergolafabio/Hikvision-Addons/commit/352098d8095f8956c8f3e8905e709a703ccf7a81
