### ISSUE TITLE
Error while calling ISAPI endpoint: Device does not support this function. Error code:23

### ISSUE THREAD

**Issue by pergolafabio** [pergolafabio/Hikvision-Addons#88]
### What happened?

Some devices dont support calling ISAPI, maybe we should skip that or check deviceinfo  / output with SDK instead of ISAPI
Addon is now not starting up for

For device; DS-KV8102-IM

`Error while calling ISAPI endpoint: Device does not support this function. Error code:23`
For command : 
`xml_string = self._call_isapi("GET", "/ISAPI/System/deviceInfo")`
`xml_string = self._call_isapi("GET", "/ISAPI/System/IO/outputs")`

Or maybe just igonore about, and make that device not supported at all ??

---------------------------------------------

For device: K1T341M 

It doesnt support NET_DVR_RemoteControl , but it does support `/ISAPI/AccessControl/RemoteControl/door/1`

Pff, what a mess

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

1

### Installation type

Home Assistant add-on

**Comment by pergolafabio** [comment]
For the 2 isapi command, maybe fallback to : NET_DVR_DEVICEINFO_V30

I think we only miss firmware version?

**Comment by pepsonEL** [comment]
I can any help you ?

**Comment by mion00** [comment]
Is there an api that could tell us it isapi is supported generally?
That way we could flag the doorbell as not supporting it and revert every action to the SDK from that point on.
Othwerise we risk duplicating every call both to isapi and ask for every minor things. 😅

**Comment by pergolafabio** [comment]
Pfff, getting difficult, or we just drop support for non-isapi models, i only know 1 :-)
Isnt that easier? Lets just focus us on current and new models? Hikvision told me , new models will suppport more and more ISAPI functions

In future we maybe gonna work on camera, thats also ISAPI

**Comment by pergolafabio** [comment]
The only issues left is this one:

`NET_DVR_RemoteControl`, should fall back to:  `/ISAPI/AccessControl/RemoteControl/door/1`

**Comment by pergolafabio** [comment]
Like this one, i think its verry usefull to retrieve for some users, it was asked before on forum

`/ISAPI/VideoIntercom/callerInfo?format=json`

I think we should focus us on ISAPI

**Comment by pergolafabio** [comment]
gonna close for now, since we need to focus on ISAPI!

for opening door for that specific K1T341M device , i used this?

https://github.com/pergolafabio/Hikvision-Addons/commit/38902732d2ef6c2d68e2b88162e9fc5e8e7b5a8f

**Comment by mion00** [comment]
- `/ISAPI/System/deviceInfo` has been accounted for, we now avoid populating the optional data if it is not available
- For `/ISAPI/System/IO/outputs`, this is crucial to display the door switches, since we would need to know the number of them to create a separate switch for each.

I have found out as a fallback `/ISAPI/AccessControl/RemoteControl/door/capabilities`, where we could parse the `max` tag in XML:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<RemoteControlDoor  version="2.0" xmlns="http://www.isapi.org/ver20/XMLSchema">
    <doorNo min="1" max="2"/>
    <cmd opt="open,alwaysOpen,resume"/>
</RemoteControlDoor >
```

**Comment by pergolafabio** [comment]
Yeah, but I think that command will fail too on old devices? I think any ISAPi command will fail

**Comment by pergolafabio** [comment]
But , that command is indeed a better one to use, it's specific for intercoms...

I have the complete isapi guide for intercom

**Comment by pergolafabio** [comment]
Maybe , as a fallback, if that command fails, just use 2 as default? So he can still use beta 10?
