### ISSUE TITLE
Use MQTT input text for testing Isapi calls

### ISSUE THREAD

**Issue by mion00** [pergolafabio/Hikvision-Addons#89]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

It might be useful to define a diagnostic sensor (disabled by default) where the user can input the ISAPI call to be made from the fronted. 
We could write the result back to another diagnostic sensor.

This way it could be possible to instruct users to test out various commands with local doorbell, allowing us to better understand if a feature is supported via their isapi protocol or not in their case. 
See #84 where the reboot button was artificially modified for this case.

Need support from upstream library ha-mqtt-discoverable for this type of sensor.

**Comment by pergolafabio** [comment]
Great idea indeed!

**Comment by pergolafabio** [comment]
or why not just use the stdin service? The isapi helper is already part of the code?

**Comment by mion00** [comment]
Yes I thinked that it could be expanded by that also. The fact is that if we are exposing the addon also to docker users, there is no more stdin available.
If we assume going on that mqtt is our main channel, I would concentrate on that as an input method, since it is available whether via stdin or mqtt inputs.
Just brainstorming here, the inputreader could become in the future just a wrapper that simply writes to mqtt, so the rest of the logic is the same.

**Comment by mion00** [comment]
Given that our architecture is expandable, nothing prohibits us to expose an http service in the future, to accept post request as commands to external systems, then internally we reroute them to the appropriate services. 😉

**Comment by pergolafabio** [comment]
ok, that makes sense indeed

**Comment by mion00** [comment]
At that point in the future we will become a sort of mini home assistant for hikvision devices 😂

**Comment by pergolafabio** [comment]
added in beta 10
