### ISSUE TITLE
Integrate Jpeg snapshot

### ISSUE THREAD

**Issue by mion00** [pergolafabio/Hikvision-Addons#90]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

Integrate the jpeg snapshot from the SDK. 

## Questions
- how to expose the functionality to users? As a mqtt button + mqtt camera? 
- how to know if a device is compatible? Just query the api one time and see the result? 
- Does the SDK save the jpeg in a file or is it in memory?

**Comment by pergolafabio** [comment]
Some reference:

https://community.home-assistant.io/t/add-on-hikvision-doorbell-integration/532796/49

**Comment by pergolafabio** [comment]
just tested this, works perfect!

```
lpJpegPara = NET_DVR_JPEGPARA()
lpJpegPara.wPicSize = 2
lpJpegPara.wPicQuality = 1
addr_jpg = byref(lpJpegPara)
filename = time.strftime("%Y%m%d-%H%M%S") + "_doorbell.jpg"
fullname = filename
response = {'captured': filename}
sJpegPicFileName = bytes(fullname, "ascii")
res = HCNetSDK.NET_DVR_CaptureJPEGPicture(user_id, c_long(1), addr_jpg,sJpegPicFileName)
if res == True:
    print("Image capture - success: {}", fullname)
    os.chmod(fullname, 0o777)
    # client.publish(config["mqtt_topic"] + '/response',
                   # json.dumps(response),
                   # qos=0,
                   # retain=False)
else:
    print("Image capture to {} - error: {}", fullname,HCNetSDK.NET_DVR_GetLastError())
```

**Comment by mion00** [comment]
It's not fair! :cry: 
You said something about firmware updates maybe?
```
[undefined]sdk.utils.SDKError: ('Error while capturing JPEG', 23, 'Device does not support this function.')
```

**Comment by mion00** [comment]
`ds-kd8003-ime1` 2.2.52

**Comment by pergolafabio** [comment]
Ah, maybe that's the reason

**Comment by pergolafabio** [comment]
If it's indeed a firmware issue, then we should keep this on hold, since most doorbells don't have the feature then, they all lack snapshot with ISAPi, it was newly introduced in 2.2.62

**Comment by pergolafabio** [comment]
not needed for now
