### ISSUE TITLE
Allow setting mqtt options

### ISSUE THREAD

**Issue by mion00** [pergolafabio/Hikvision-Addons#93]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

Python can correctly read the mqtt config, but the addon metadata in HA must be updated to allow those options.

**Comment by pergolafabio** [comment]
Hmmn tried the schema like below, without options defined, but it still asks me to input mqtt data

```
# Schema for the options above
schema:
  doorbells:
    - name: str
      ip: str
      username: str
      password: str
      output_relays: "int?"
  mqqt:    
    host: str?
    port: str?
    ssl: str?
    username: str?
    password: str?    
  system:
    log_level: match(^ERROR|WARNING|INFO|DEBUG$)
    sdk_log_level: match(^NONE|ERROR|INFO|DEBUG$)?
```

![image](https://user-images.githubusercontent.com/43251136/226164732-89a50eb5-bbea-417a-ab6c-8957e539dd57.png)

**Comment by pergolafabio** [comment]
Doing it like this, gives me "show unused options, so i can enter mqqt"

```
# Schema for the options above
schema:
  doorbells:
    - name: str
      ip: str
      username: str
      password: str
      output_relays: "int?"
  host: str?
  port: str?
  ssl: str?
  username: str?
  password: str?    
  system:
    log_level: match(^ERROR|WARNING|INFO|DEBUG$)
    sdk_log_level: match(^NONE|ERROR|INFO|DEBUG$)?
```

But then i receive this, when i input some data:

```
2023-03-19 10:06:36.785 | DEBUG    | config:mqtt_config_from_supervisor:36 - Requesting MQTT service configuration to supervisor
Traceback (most recent call last):
  File "/app/main.py", line 91, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/main.py", line 21, in main
    config.load()
  File "/usr/local/lib/python3.10/site-packages/goodconf/__init__.py", line 144, in load
    super().__init__()
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for AppConfig
host
  extra fields not permitted (type=value_error.extra)
password
  extra fields not permitted (type=value_error.extra)
port
  extra fields not permitted (type=value_error.extra)
ssl
  extra fields not permitted (type=value_error.extra)
username
  extra fields not permitted (type=value_error.extra)
```

**Comment by timrosede** [comment]
Did you make a mistake? It should be mqtt not mqqt.

**Comment by pergolafabio** [comment]
i tried changing it, but doesnt help :-(
need @mion00 help here , not sure how to pass this info as optional

**Comment by pergolafabio** [comment]
i need to have it in both options and schema, but that i cant hide to show as optional items

**Comment by pergolafabio** [comment]
this doesnt work:

```
schema:
  doorbells:
    - name: str
      ip: str
      username: str
      password: str
      output_relays: "int?"
  mqtt:
    host: str?
    ssl: bool?
    username: str?
    password: str?  
```

But it works if i add it in options, but then its not optional anymore, it complains about the headsection mqtt: itself

```
Failed to save add-on configuration, Missing option 'mqtt' in root in Hikvision LOCAL (local_hikvision_local). Got {'doorbells': [{'name': 'DS-KH9310', 'ip': '192.168.0.72', 'username': 'admin', 'password': 'xxx'}], 'system': {'log_level': 'INFO', 'sdk_log_level': 'NONE'}}
```

**Comment by timrosede** [comment]
i am still missing this, how can i help?

**Comment by pergolafabio** [comment]
yeah i know, i need @mion00  help here :-)
He will have a look within some time

**Comment by mion00** [comment]
Hi. Hope to be able to come up with a solution soon. I think the library used for the configuration expects a key to be present for mqtt. 🤔

**Comment by timrosede** [comment]
Is it possible to set the mqtt values for the supervisor manual?

**Comment by pergolafabio** [comment]
Yes, it can be configured manually, but then everyone needs to configure it manually, now it was a discovery...

Maybe we need to drop the discovery, so all users should need to configure manually

**Comment by pergolafabio** [comment]
I just tried it, it works, the only thing missing is maybe to produce better errors , line not authorized or server connect issues, with wrong ip/port

**Comment by CV8R** [comment]
I can confirm it works for me now too!

**Comment by pergolafabio** [comment]
added in beta 25
