### ISSUE TITLE
External MQTT Broker

### ISSUE THREAD

**Issue by Marol92** [pergolafabio/Hikvision-Addons#94]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

allow hik add-on to connect and use external mqtt broker

**Comment by pergolafabio** [comment]
Hi , have you tried this?

https://community.home-assistant.io/t/hikvision-doorbell-videointercom-integration/532796/185?u=pergola.fabio

**Comment by mion00** [comment]
I may be wrong, but I suppose those options are ignored at the moment if not declared in the schema of `config.yaml`. See #93

**Comment by pergolafabio** [comment]
Ah ok

**Comment by Marol92** [comment]
> Hi , have you tried this?
> 
> https://community.home-assistant.io/t/hikvision-doorbell-videointercom-integration/532796/185?u=pergola.fabio

yes, but it seems to not affect configuration
![image](https://user-images.githubusercontent.com/77080896/225401890-f4add756-6db9-44df-b09b-a8c380762937.png)

**Comment by pergolafabio** [comment]
Hi, gonna close this one, just subscribe to 93, I try to add it next week
