### ISSUE TITLE
Answering a call via Home Assistant buttons not working

### ISSUE THREAD

**Issue by dragonspy00** [pergolafabio/Hikvision-Addons#99]
### What happened?

Hello, I have a DS-KD8003-IME1 outdoor unit and a DS-KH6320-WTE1 indoor unit. 

I am able to send a reject command to the indoor unit whenever the doorbell is ringing and that is working perfectly fine. However, I want to send an answer command instead so that it doesn't make the hangup/rejection tone at the outdoor unit.

Unfortunately, I cannot get this working so I'm not sure if it's a "bug" or if it's just not supported by the devices I have? I have tried to send the command to both the indoor and outdoor units. 

With the indoor unit, I can an error `Device operation failed` whereas the outdoor unit gets `The data sent to the device is illegal, or the data received from the device error.  E.g. The input data is not supported by the device for remote configuration.`.

Some extra notes: I am running the latest beta version via docker-compose. I am using the automatically created "answer" buttons via Home Assistant. First set of log is answer command to indoor. Second set of logs is sending answer to the outdoor unit.

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

doorbell-v3.0.0-beta.17

### Installation type

Docker container (standalone)

### Relevant log output

```Text
{"log":"\u001b[32m2023-03-28 23:07:01.827\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36mmqtt_input\u001b[0m:\u001b[36m_answer_call_callback\u001b[0m:\u001b[36m113\u001b[0m - \u001b[1mReceived answer command for doorbell: indoor_unit\u001b[0m\r\n","stream":"stdout","time":"2023-03-28T23:07:01.828166192Z"}
{"log":"\u001b[32m2023-03-28 23:07:01.827\u001b[0m | \u001b[34m\u001b[1mDEBUG   \u001b[0m | \u001b[36msdk.utils\u001b[0m:\u001b[36mcall_ISAPI\u001b[0m:\u001b[36m125\u001b[0m - \u001b[34m\u001b[1mRequest body: {\"CallSignal\": {\"cmdType\": \"answer\"}}\u001b[0m\r\n","stream":"stdout","time":"2023-03-28T23:07:01.828509455Z"}
{"log":"[2023-03-28 23:07:01.833][INF] Private connect **masked**:8000 sock=170 this=0xc6963ac cmd=0x117001 port=44550\r\r\n","stream":"stdout","time":"2023-03-28T23:07:01.837411613Z"}
{"log":"\u001b[32m2023-03-28 23:07:01.837\u001b[0m | \u001b[34m\u001b[1mDEBUG   \u001b[0m | \u001b[36msdk.utils\u001b[0m:\u001b[36mcall_ISAPI\u001b[0m:\u001b[36m162\u001b[0m - \u001b[34m\u001b[1mResponse status: {\r\n","stream":"stdout","time":"2023-03-28T23:07:01.838361445Z"}
{"log":"\u0009\"statusCode\":\u0009\"4\",\r\n","stream":"stdout","time":"2023-03-28T23:07:01.838408182Z"}
{"log":"\u0009\"statusString\":\u0009\"Invalid Operation\",\r\n","stream":"stdout","time":"2023-03-28T23:07:01.838421741Z"}
{"log":"\u0009\"subStatusCode\":\u0009\"Unknow\",\r\n","stream":"stdout","time":"2023-03-28T23:07:01.838432449Z"}
{"log":"\u0009\"errorMsg\":\u0009\"noRequest\",\r\n","stream":"stdout","time":"2023-03-28T23:07:01.838442827Z"}
{"log":"\u0009\"errorCode\":\u00091073770506\r\n","stream":"stdout","time":"2023-03-28T23:07:01.83845327Z"}
{"log":"}\u001b[0m\r\n","stream":"stdout","time":"2023-03-28T23:07:01.838463927Z"}
{"log":"\u001b[32m2023-03-28 23:07:01.838\u001b[0m | \u001b[31m\u001b[1mERROR   \u001b[0m | \u001b[36mmqtt_input\u001b[0m:\u001b[36m_answer_call_callback\u001b[0m:\u001b[36m125\u001b[0m - \u001b[31m\u001b[1mError while answering call: ('Error while calling ISAPI /ISAPI/VideoIntercom/callSignal?format=json', 29, 'Device operation failed.')\u001b[0m\r\n","stream":"stdout","time":"2023-03-28T23:07:01.838709979Z"}

{"log":"\u001b[32m2023-03-28 23:07:24.714\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36mmqtt_input\u001b[0m:\u001b[36m_answer_call_callback\u001b[0m:\u001b[36m113\u001b[0m - \u001b[1mReceived answer command for doorbell: front_door\u001b[0m\r\n","stream":"stdout","time":"2023-03-28T23:07:24.715083885Z"}
{"log":"\u001b[32m2023-03-28 23:07:24.714\u001b[0m | \u001b[34m\u001b[1mDEBUG   \u001b[0m | \u001b[36msdk.utils\u001b[0m:\u001b[36mcall_ISAPI\u001b[0m:\u001b[36m125\u001b[0m - \u001b[34m\u001b[1mRequest body: {\"CallSignal\": {\"cmdType\": \"answer\"}}\u001b[0m\r\n","stream":"stdout","time":"2023-03-28T23:07:24.715426543Z"}
{"log":"[2023-03-28 23:07:24.721][INF] Private connect **masked**:8000 sock=170 this=0xc6963ac cmd=0x117001 port=41434\r\r\n","stream":"stdout","time":"2023-03-28T23:07:24.727712375Z"}
{"log":"\u001b[32m2023-03-28 23:07:24.748\u001b[0m | \u001b[34m\u001b[1mDEBUG   \u001b[0m | \u001b[36msdk.utils\u001b[0m:\u001b[36mcall_ISAPI\u001b[0m:\u001b[36m162\u001b[0m - \u001b[34m\u001b[1mResponse status: {\r\n","stream":"stdout","time":"2023-03-28T23:07:24.749045381Z"}
{"log":"\u0009\"requestURL\":\u0009\"/ISAPI/VideoIntercom/callSignal\",\r\n","stream":"stdout","time":"2023-03-28T23:07:24.749109794Z"}
{"log":"\u0009\"statusCode\":\u00096,\r\n","stream":"stdout","time":"2023-03-28T23:07:24.749123402Z"}
{"log":"\u0009\"statusString\":\u0009\"Invalid Content\",\r\n","stream":"stdout","time":"2023-03-28T23:07:24.749134Z"}
{"log":"\u0009\"subStatusCode\":\u0009\"badXmlContent\",\r\n","stream":"stdout","time":"2023-03-28T23:07:24.749145173Z"}
{"log":"\u0009\"errorCode\":\u00091610612739,\r\n","stream":"stdout","time":"2023-03-28T23:07:24.749155926Z"}
{"log":"\u0009\"errorMsg\":\u0009\"Wrong XMLcontent\"\r\n","stream":"stdout","time":"2023-03-28T23:07:24.749166474Z"}
{"log":"}\u001b[0m\r\n","stream":"stdout","time":"2023-03-28T23:07:24.749176942Z"}
{"log":"\u001b[32m2023-03-28 23:07:24.748\u001b[0m | \u001b[31m\u001b[1mERROR   \u001b[0m | \u001b[36mmqtt_input\u001b[0m:\u001b[36m_answer_call_callback\u001b[0m:\u001b[36m125\u001b[0m - \u001b[31m\u001b[1mError while answering call: ('Error while calling ISAPI /ISAPI/VideoIntercom/callSignal?format=json', 11, 'The data sent to the device is illegal, or the data received from the device error.  E.g. The input data is not supported by the device for remote configuration.')\u001b[0m\r\n","stream":"stdout","time":"2023-03-28T23:07:24.749322566Z"}
{"log":"[2023-03-28 23:07:24.747][DBG] SimpleSTDCommandToDvr with out cmd[PUT /ISAPI/VideoIntercom/callSignal?format=json], input size[37], max segment length[262144]\r\r\n","stream":"stdout","time":"2023-03-28T23:07:24.758004435Z"}

```

**Comment by pergolafabio** [comment]
Hi, yes, that's normal, it doesn't do anything indeed, it's maybe for future use to start talking with two way audio, but thets not implemented yet

Maybe it's indeed better to remove it now, untill it has some purpose :-)

**Comment by pergolafabio** [comment]
What do you want Todo with the answer command? Answering on indoor?

**Comment by dragonspy00** [comment]
Currently I have a door sensor and when the door is opened, the automation will send a "reject" command to stop the doorbell from ringing. But this gives an annoying rejection tone at the doorbell.

I was hoping to modify the automation to do an answer and then immediately followed by a hangup to bypass the rejection tone.

(This is what I manually do on the indoor unit if I'm walking past it to get to the door in order to bypass the rejection tone).

**Comment by dragonspy00** [comment]
Thanks heaps for your reply! If it's not yet implemented then might I suggest updating it in the BETA documentation? It's currently documented with "Unknown" which is a little bit ambiguous.

**Comment by pergolafabio** [comment]
Ah ok makes sense , yeah I also have a ZigBee door sensor to stop indeed ringing on all devices when door opened manually, it was indeed frustrating :-)

I also have an 8003, I tested answer before and it worked on my setup, no reject tone, 
But sending answer only works if there is actually a ringing state, otherwise you see indeed an error, and it lust send to indoor... Outdoor doesn't accept callsignal commands when there is an indoor attached...

Have you tried sending 'answer' while it was actually ringing?

**Comment by pergolafabio** [comment]
I do have another indoor, I have 9510 model

**Comment by dragonspy00** [comment]
Yeah, my tests have been with the doorbell in a ringing state and the answer command doesn't work for either indoor or outdoor units.

_Outdoor doesn't accept callsignal commands when there is an indoor attached..._

Ahh... since I have an indoor attached, I will have to wait for your implementation of answer command on indoor unit. Assuming that's even possible of course.

**Comment by pergolafabio** [comment]
But actually I was still testing the answer command, to actually really make an answer on an indoor panel, without pressing the button on it... For now it just sends a very basic payload to it, but it can be extended with like room nr etc... But no time to test it yet....

See here.... I can give instructions if you want to test how to send a more complete payload?

https://github.com/pergolafabio/Hikvision-Addons/issues/87#issuecomment-1464959052

**Comment by pergolafabio** [comment]
> Yeah, my tests have been with the doorbell in a ringing state and the answer command doesn't work for either indoor or outdoor units.
> 
> _Outdoor doesn't accept callsignal commands when there is an indoor attached..._
> 
> Ahh... since I have an indoor attached, I will have to wait for your implementation of answer command on indoor unit. Assuming that's even possible of course.

Yes , you can do that already, you can setup multiple devices, just also add your indoor to the config.yaml as a second device , that will create a second MQTT device that you can use to send commands too

**Comment by dragonspy00** [comment]
Yes, I have both devices setup and have been testing by using the buttons that are automatically created in HomeAssistant.

I'm a dev too so I can give the extended payloads a try. I assume they're to be sent to the indoor unit via this endpoint:
http://{indoor_IP}/ISAPI/VideoIntercom/callSignal?format=json

**Comment by pergolafabio** [comment]
Ah ok yes indeed, but the problem is, there is no port 80 open on indoor units, I have found a way to send ISAPI with SDK using port 8000 instead ... I'd you go to the MQTT device, there is an diagnostic entity, called isapi helper, you need to enable it first and then restart HA...

Then you can use it in service tools to send ISAPI...

The format is like:

"PUT /Isapi/... Payload

The payload is optional, foe commands using GET

**Comment by pergolafabio** [comment]
Keep me posted, I only tested with the basic payload, when I send answer to indoor, it actually answers, bur it also aborts immediately after it

**Comment by pergolafabio** [comment]
For more references, download this one, there is an videointercom one inside , you can see all Isapi commands, also to GET the callsignal capabilities doe your devices...

https://www.dropbox.com/s/obppstvpvxja9l7/isapi.zip?dl=0


But remember, you need to use SDK to send Isapi commands,for some reason hikvision didn't open port 80 on indoor devices

**Comment by dragonspy00** [comment]
Ah thanks heaps mate. I'll have a play with it in my spare time and keep you posted. 

It is indeed annoying that we have to go through SDK which in turn means going through the ISAPI helper you created in HA. Would have made testing much easier via Postman :)

**Comment by pergolafabio** [comment]
Yeah I know, it was a real struggle to find this all out, but I'll quite happy what I have found already to make this all happen:-)

I really like the reject one, I did it first by using Hikconnect cloud by reverse engineering the Hikconnect code, but local approach is much better

**Comment by dragonspy00** [comment]
I had a play with it today trying to send all the optional parameters in the callSignal JSON request but getting text too long errors in HA. Seems like the text_input in HA only supports maximum of 255 chars. 

Is there another way to invoke the ISAPI request via SDK through another method like MQTT instead of through HA?

**Comment by pergolafabio** [comment]
Crap, wel, look at this example script, those are the ones I started with, you can just run it once, but you need to run this on an debian system, like the add-ons, or copy paste it inside the docker and run it from there, so it loads the SDK (path)

https://github.com/pergolafabio/Hikvision-Addons/blob/dev/hikvision-doorbell/examples/hik_isapi_callsignal.py

**Comment by pergolafabio** [comment]
Have you made some progress? i'm interested in this too, would be cool if we can actually make the answer work on the indoor panel

**Comment by dragonspy00** [comment]
I haven't been able to spend much time on it unfortunately.

Planning to look into it over the Easter long weekend :)

**Comment by dragonspy00** [comment]
Spent a good few hours on it today with various types of payloads but unfortunately no dice.
Keep getting `Invalid Operation` errors even with well formed payloads.

I tried the following:
- Retrieving all the parameters such as floor, unit, room, etc through iVMS as well as through `GET /ISAPI/VideoIntercom/deviceId` 
- Setting all the optional parameters in the `CallSignal` JSON with the data retrieved from first step
- Swapping the `src` and `target` around
- Documentation makes a note that `"devIndex": /*optional, integer, device serial No.*/` so tried putting in the last few digits of my device serial numbers since the full serial is a string.

Nothing worked :(

Example payload I was sending:
```{
    "CallSignal": {
        "cmdType": "answer",
        "src": {
	    "periodNumber": 1,
            "buildingNumber": 1,
            "unitNumber": 1,
            "floorNumber": 0,
            "roomNumber": 1,
            "devIndex": //removed,
            "communityNumber": "0",
            "unitType": "indoor"
        },
        "target": {
	    "periodNumber": 1,
            "buildingNumber": 1,
            "unitNumber": 1,
            "floorNumber": 1,
            "roomNumber": 1,
            "devIndex": //removed,
            "unitType": "outdoor"
        }
    }
}
```

**Comment by pergolafabio** [comment]
Are you using that custom script I posted earlier to send to indoor?  You escaped the quote?

` inPutBuffer = "{\"CallSignal\":{\"cmdType\":\"reject\"}}" `


And did you also pressed everytime the doorbutton, because invalid operation can also occur because there was no actual ringing...


Same happens with the reject, if you send reject, when no ringing you  also see in addon log , invalid operation, code 29

**Comment by dragonspy00** [comment]
Yep, using your python script via Debian - Json correctly formatted with quotes escaped when pasted into the script.

And yeah, I uninstalled the indoor and outdoor unit to have it next to me for the day to test whilst in the ringing state.

Reject works fine - No matter what parameters I put for `src` and `target`. So I feel like those optional parameters don't really do anything.

Unfortunately, answer command (or any other command) just refuses to work for me. Even tried testing hangUp command when it was in the middle of a call.

**Comment by pergolafabio** [comment]
Ah crap, what kind of indoor device do you have? I remember sending answer to my indoor without an error from addon, it did actually answer, it stopped ringing, but I was not able to speak to my indoor, the call was ended immediately afterwards....

I just thought because of the wrong payload...

I try again later if I also see operation failed in logs

**Comment by dragonspy00** [comment]
I've got the DS-KH6320-WTE1.

I'm thinking maybe the answer command only works if I have Hik-Connect/Cloud enabled? 

I've got the cameras in their own VLAN and its locked down pretty tight with no internet connectivity. I don't really want to open up their access but I might look into creating a new sandboxed environment with internet to rule it out.

**Comment by pergolafabio** [comment]
Hmm, don't think there is a relationship with Hikconnect...

Maybe it's only Intended for indoor to indoor calls? (Intercom)

**Comment by pergolafabio** [comment]
just quickly tested with addon itself, indeed 29 error on answering

`2023-04-07 08:56:42.798 | ERROR    | mqtt_input:_answer_call_callback:125 - Error while answering call: ('Error while calling ISAPI /ISAPI/VideoIntercom/callSignal?format=json', 29, 'Device operation failed.')`

Will do also some more testing later with script

**Comment by pergolafabio** [comment]
gonna close for now

**Comment by pergolafabio** [comment]
Hmm, got mail back from hikvsion, seems not possible, all though I don't believe it :-)

**Comment by pergolafabio** [comment]
hey @dragonspy00 , someone else figured it out, seems the device needs to be connected to Hikconnect in order to make the "answer" command work! just wanted to let you know!

https://github.com/pergolafabio/Hikvision-Addons/issues/149

**Comment by dragonspy00** [comment]
> Hmm, don't think there is a relationship with Hikconnect...

Ah I knew I was onto something initially! Thanks for the update mate, I can confirm that it does work when connected to Hikconnect. 

I see in the other issue that people are commenting that it will keep working when disconnected from the internet up until the next reboot.

I'll need to experiment a bit more as I don't like giving the device access to the internet.

**Comment by pergolafabio** [comment]
Yeah , you can maybe join other thread and post your findings...
